import { C, pd, es } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- PLATON (pagination de Stephanus) ----------
C('plat-caverne', T, "République VII : que signifie la sortie de la caverne ?",
  "L'ascension de l'âme du sensible (ombres, opinion) vers l'intelligible, jusqu'à l'Idée du Bien (le soleil). Le philosophe doit ensuite redescendre éclairer les prisonniers.",
  { a: ['Platon'], o: 'République', n: ['la vérité', 'la raison'], s: [es('Platon, République, VII, 514a-517c ; 519c-521b')] }),
C('plat-soleil', T, "République VI : quelle analogie relie le soleil et l'Idée du Bien ?",
  "Le soleil rend visibles les choses sensibles et permet leur croissance ; le Bien donne aux Idées leur intelligibilité et leur être, tout en étant « au-delà de l'essence » (509b).",
  { a: ['Platon'], o: 'République', n: ['la vérité'], s: [es('Platon, République, VI, 507b-509c')] }),
C('plat-ligne', T, "Comment la ligne divisée hiérarchise-t-elle les degrés de connaissance ?",
  "Deux domaines : le sensible (imagination, croyance) et l'intelligible (pensée discursive, intellection). Chaque segment est à son voisin dans un même rapport de clarté et de vérité.",
  { a: ['Platon'], o: 'République', n: ['la vérité', 'la raison'], s: [es('Platon, République, VI, 509d-511e')] }),
C('plat-justice', T, "Comment la République définit-elle la justice dans la cité et dans l'âme ?",
  "Dans la cité : chacun accomplit la tâche qui lui revient. Dans l'âme : la raison commande, aidée du cœur (thumos), aux appétits. La justice est une harmonie.",
  { a: ['Platon'], o: 'République', n: ['la justice'], s: [es('Platon, République, IV, 433a-b ; 441c-444a')] }),
C('plat-gyges', T, "République II : que veut montrer le mythe de l'anneau de Gygès ?",
  "Glaucon suppose qu'à l'abri de tout châtiment, même le juste agirait injustement : la justice ne serait qu'une contrainte. Socrate devra prouver qu'elle est un bien en soi.",
  { a: ['Platon'], o: 'République', n: ['la justice', 'le devoir'], s: [es('Platon, République, II, 359a-360d')] }),
C('plat-menon', T, "Que montre l'interrogation de l'esclave dans le Ménon ?",
  "Que connaître, c'est se ressouvenir : guidé par de simples questions, l'esclave trouve la construction du carré double. L'âme immortelle a déjà contemplé les vérités.",
  { a: ['Platon'], o: 'Ménon', n: ['la vérité'], s: [es('Platon, Ménon, 81a-86c (esclave : 82b-85b)')] }),
C('plat-gorgias', T, "Pourquoi Socrate compare-t-il la rhétorique à la cuisine dans le Gorgias ?",
  "Ce sont des routines de flatterie qui visent le plaisir sans connaître le bien. La cuisine imite la médecine, la rhétorique imite la justice, sans savoir véritable.",
  { a: ['Platon'], o: 'Gorgias', n: ['le langage', 'la justice'], s: [es('Platon, Gorgias, 462b-465e')] }),
C('plat-phedre-ecriture', T, "Que reproche Socrate à l'écriture dans le Phèdre ?",
  "Elle donne l'apparence du savoir et affaiblit la mémoire ; elle ne peut ni répondre aux questions ni se défendre. Le vrai discours s'inscrit dans l'âme (mythe de Theuth).",
  { a: ['Platon'], o: 'Phèdre', n: ['le langage', 'la vérité'], s: [es('Platon, Phèdre, 274c-277a')] }),
C('plat-banquet', T, "Quelle est la progression de l'amour dans le discours de Diotime (Banquet) ?",
  "Du beau corps particulier à tous les beaux corps, puis aux belles âmes, aux lois, aux sciences, jusqu'au Beau en soi, éternel et unique.",
  { a: ['Platon'], o: 'Banquet', n: ['le bonheur', 'la vérité'], s: [es('Platon, Banquet, 209e-212a')] }),
C('plat-apologie', T, "En quoi consiste la « sagesse » de Socrate dans l'Apologie ?",
  "Une sagesse simplement humaine : savoir qu'il ne sait pas ce qu'il ne sait pas. Elle naît de l'énigme de l'oracle de Delphes et fonde sa mission d'examen d'autrui.",
  { a: ['Platon'], o: 'Apologie de Socrate', n: ['la vérité'], s: [es('Platon, Apologie de Socrate, 20d-23b')] }),
C('plat-protagoras', T, "Dans le mythe de Prométhée (Protagoras), que manque-t-il encore aux hommes pourvus de la technique ?",
  "L'art politique : sans lui ils s'entre-détruisent. Zeus envoie par Hermès la pudeur (aidôs) et la justice (dikè), à partager entre tous.",
  { a: ['Platon'], o: 'Protagoras', n: ['la technique', "l'État"], s: [es('Platon, Protagoras, 320c-322d')] }),

// ---------- ARISTOTE (pagination de Bekker) ----------
C('aris-bonheur', T, "Comment Aristote définit-il le bonheur (eudaimonia) dans l'Éthique à Nicomaque ?",
  "Le bien suprême, fin recherchée pour elle-même : une activité de l'âme conforme à la vertu la plus parfaite, dans une vie accomplie.",
  { a: ['Aristote'], o: 'Éthique à Nicomaque', n: ['le bonheur'], s: [es('Aristote, Éthique à Nicomaque, I, 1-2 (1094a) ; I, 6 (1098a16-18)')] }),
C('aris-vertu', T, "Qu'est-ce que la vertu morale selon Aristote ?",
  "Une disposition acquise (hexis) à choisir le juste milieu relatif à nous, déterminé par la raison comme le déterminerait l'homme sensé (phronimos).",
  { a: ['Aristote'], o: 'Éthique à Nicomaque', n: ['le devoir', 'le bonheur'], s: [es('Aristote, Éthique à Nicomaque, II, 6 (1106b36-1107a2)')] }),
C('aris-animal-politique', T, "Pourquoi l'homme est-il un « animal politique » (Politiques, I, 2) ?",
  "La cité est naturelle. Seul l'homme a le logos, qui manifeste le juste et l'injuste ; hors de la cité, on est une bête ou un dieu.",
  { a: ['Aristote'], o: 'Politiques', n: ["l'État", 'le langage', 'la nature'], s: [es('Aristote, Politiques, I, 2 (1253a1-18)')] }),
C('aris-quatre-causes', T, "Quelles sont les quatre causes d'Aristote ?",
  "Matérielle (de quoi), formelle (essence), efficiente (d'où vient le mouvement), finale (en vue de quoi). Exemple de la statue : bronze, forme, sculpteur, but.",
  { a: ['Aristote'], o: 'Physique', n: ['la nature', 'la technique'], s: [es('Aristote, Physique, II, 3 (194b16-195a3) ; Métaphysique, Δ, 2 (1013a24-b3)')] }),
C('aris-acte-puissance', T, "Que distingue Aristote par « en puissance » et « en acte » ?",
  "La puissance est la capacité d'être ou de devenir autre ; l'acte est sa réalisation. La statue est en puissance dans le bloc, en acte une fois sculptée.",
  { a: ['Aristote'], o: 'Métaphysique', n: ['la nature'], s: [es('Aristote, Métaphysique, Θ, 6 (1048a25-b9)')] }),
C('aris-poetique', T, "Pourquoi la poésie est-elle « plus philosophique » que l'histoire (Poétique, 9) ?",
  "L'histoire dit ce qui a eu lieu ; la poésie dit ce qui pourrait avoir lieu selon le vraisemblable et le nécessaire. Elle vise donc l'universel.",
  { a: ['Aristote'], o: 'Poétique', n: ["l'art", 'la vérité'], s: [es('Aristote, Poétique, 9 (1451a36-b11)')] }),
C('aris-metaphysique-a', T, "Comment s'ouvre la Métaphysique d'Aristote ?",
  "Par la thèse que tous les hommes désirent naturellement savoir ; signe : le plaisir des sensations, surtout de la vue, aimée pour elle-même.",
  { a: ['Aristote'], o: 'Métaphysique', n: ['la raison', 'la vérité'], s: [es('Aristote, Métaphysique, A, 1 (980a21-27)')] }),
C('aris-temps', T, "Comment Aristote définit-il le temps (Physique IV) ?",
  "Le nombre du mouvement selon l'avant et l'après : le temps n'existe pas sans un changement que l'âme peut dénombrer.",
  { a: ['Aristote'], o: 'Physique', n: ['le temps'], s: [es('Aristote, Physique, IV, 11 (219b1-2)')] }),
C('aris-contemplation', T, "Pourquoi la vie contemplative est-elle la plus heureuse (Éthique à Nicomaque, X) ?",
  "Elle est l'activité de la partie la plus haute de nous (l'intellect), la plus continue, la plus autosuffisante, et aimée pour elle-même.",
  { a: ['Aristote'], o: 'Éthique à Nicomaque', n: ['le bonheur'], s: [es('Aristote, Éthique à Nicomaque, X, 7 (1177a12-b1)')] }),

// ---------- DESCARTES ----------
C('desc-bon-sens', T, "Comment s'ouvre le Discours de la méthode ?",
  "Le bon sens est la chose du monde la mieux partagée ; nos opinions divergent parce que nous conduisons mal notre raison. D'où la nécessité d'une méthode.",
  { a: ['Descartes'], o: 'Discours de la méthode', n: ['la raison'], s: [pd('Descartes, Discours de la méthode, I (AT VI, 1-2)')] }),
C('desc-regles', T, "Quelles sont les quatre règles de la méthode (Discours, II) ?",
  "Évidence (ne recevoir que le clair et distinct), analyse (diviser), ordre (du simple au complexe), dénombrement (revues générales).",
  { a: ['Descartes'], o: 'Discours de la méthode', n: ['la raison', 'la science'], s: [pd('Descartes, Discours de la méthode, II (AT VI, 18-19)')] }),
C('desc-morale-provision', T, "Quelles sont les maximes de la morale par provision (Discours, III) ?",
  "Obéir aux lois et coutumes ; être ferme et résolu dans ses actions ; se vaincre plutôt que la fortune (changer ses désirs plutôt que l'ordre du monde) ; cultiver sa raison.",
  { a: ['Descartes'], o: 'Discours de la méthode', n: ['le devoir', 'le bonheur'], s: [pd('Descartes, Discours de la méthode, III (AT VI, 22-28)')] }),
C('desc-doute', T, "Quelles sont les étapes du doute dans la Méditation première ?",
  "Erreurs des sens, puis rêve, puis hypothèse du Dieu trompeur ou du malin génie. Le doute est hyperbolique et méthodique : il vise un fondement certain.",
  { a: ['Descartes'], o: 'Méditations métaphysiques', n: ['la vérité', 'la raison'], s: [pd('Descartes, Méditations métaphysiques, I (AT IX-1, 13-18)')] }),
C('desc-cogito', T, "Pourquoi le cogito résiste-t-il au doute (Méditation seconde) ?",
  "Même trompé par un malin génie, il faut que je sois pour être trompé : « je suis, j'existe » est vrai chaque fois que je le pense.",
  { a: ['Descartes'], o: 'Méditations métaphysiques', n: ['la conscience', 'la vérité'], s: [pd('Descartes, Méditations métaphysiques, II (AT IX-1, 19)')] }),
C('desc-cit-cogito', 'citation', "Qui écrit « Je pense, donc je suis », et où ?",
  "Descartes, Discours de la méthode, IV (AT VI, 32). La forme latine « ego cogito, ergo sum » figure dans les Principes de la philosophie, I, art. 7.",
  { a: ['Descartes'], o: 'Discours de la méthode', n: ['la conscience'], s: [pd('Descartes, Discours de la méthode, IV (AT VI, 32) ; Principes de la philosophie, I, art. 7')] }),
C('desc-cire', T, "Que démontre l'exemple du morceau de cire (Méditation seconde) ?",
  "Que je connais la cire par l'inspection de l'esprit seul, non par les sens ni l'imagination, puisque toutes ses qualités sensibles changent quand elle fond.",
  { a: ['Descartes'], o: 'Méditations métaphysiques', n: ['la raison'], s: [pd('Descartes, Méditations métaphysiques, II (AT IX-1, 23-25)')] }),
C('desc-infini', T, "Comment Descartes prouve-t-il l'existence de Dieu par l'idée d'infini (Méditation troisième) ?",
  "J'ai en moi l'idée d'un être infini et parfait ; étant fini, je ne peux en être la cause. Seul un être infini peut l'avoir mise en moi.",
  { a: ['Descartes'], o: 'Méditations métaphysiques', n: ['la religion', 'la raison'], s: [pd('Descartes, Méditations métaphysiques, III (AT IX-1, 30-41)')] }),
C('desc-veracite', T, "Quel rôle joue la véracité divine, et quelle objection lui oppose-t-on ?",
  "Dieu, parfait, n'est pas trompeur : ce que je conçois clairement et distinctement est vrai. Objection classique : le « cercle » (prouver Dieu par l'évidence, l'évidence par Dieu).",
  { a: ['Descartes'], o: 'Méditations métaphysiques', n: ['la vérité', 'la religion'], s: [pd('Descartes, Méditations métaphysiques, IV-V ; Secondes réponses'), pd('Descartes, Quatrièmes objections (Arnauld)')] }),
C('desc-liberte', T, "Comment Descartes distingue-t-il liberté et indifférence ?",
  "L'indifférence est le plus bas degré de la liberté. Plus ma volonté est portée par l'évidence du vrai et du bien, plus je suis libre.",
  { a: ['Descartes'], o: 'Méditations métaphysiques', n: ['la liberté'], s: [pd('Descartes, Méditations métaphysiques, IV ; Lettre à Mesland, 9 février 1645')] }),
C('desc-union', T, "Comment Descartes pense-t-il l'union de l'âme et du corps ?",
  "Deux substances distinctes, mais unies : je ne suis pas dans mon corps comme un pilote en son navire. L'union est une notion primitive, connue par la vie et les conversations.",
  { a: ['Descartes'], o: 'Méditations métaphysiques', n: ['la conscience', 'la nature'], s: [pd('Descartes, Méditations métaphysiques, VI ; Lettre à Élisabeth, 21 mai 1643')] }),
C('desc-generosite', T, "Qu'est-ce que la générosité chez Descartes (Passions de l'âme) ?",
  "Savoir que seul le libre arbitre nous appartient vraiment, et avoir la ferme résolution d'en bien user. Elle est la clef des autres vertus et remède aux passions.",
  { a: ['Descartes'], o: "Les Passions de l'âme", n: ['la liberté', 'le devoir'], s: [pd("Descartes, Les Passions de l'âme, art. 153-161")] }),

// ---------- KANT (Akademie-Ausgabe) ----------
C('kant-lumieres', T, "Comment Kant définit-il les Lumières ?",
  "La sortie de l'homme de sa minorité, dont il est lui-même responsable : l'incapacité de se servir de son entendement sans la conduite d'autrui. Devise : sapere aude.",
  { a: ['Kant'], o: "Qu'est-ce que les Lumières ?", n: ['la raison', 'la liberté'], s: [pd("Kant, Beantwortung der Frage : Was ist Aufklärung ? (1784), AK VIII, 35")] }),
C('kant-cit-sapere', 'citation', "Quelle est la devise des Lumières selon Kant ?",
  "« Sapere aude ! » (ose te servir de ton propre entendement), reprise d'Horace : Kant, Qu'est-ce que les Lumières ?, AK VIII, 35.",
  { a: ['Kant'], o: "Qu'est-ce que les Lumières ?", n: ['la raison'], s: [pd('Kant, Was ist Aufklärung ?, AK VIII, 35')] }),
C('kant-copernic', T, "Qu'est-ce que la « révolution copernicienne » de Kant ?",
  "Ce n'est plus la connaissance qui se règle sur les objets, mais les objets (comme phénomènes) qui se règlent sur les conditions a priori de notre connaissance.",
  { a: ['Kant'], o: 'Critique de la raison pure', n: ['la science', 'la raison'], s: [pd('Kant, Critique de la raison pure, préface de la 2e éd. (B XVI)')] }),
C('kant-intuition-concept', T, "Que signifie : sans concepts, les intuitions sont aveugles ; sans intuitions, les concepts sont vides ?",
  "Connaître exige deux sources : la sensibilité, qui donne des intuitions, et l'entendement, qui pense par concepts. L'une sans l'autre ne fournit aucune connaissance.",
  { a: ['Kant'], o: 'Critique de la raison pure', n: ['la raison', 'la science'], s: [pd('Kant, Critique de la raison pure, Logique transcendantale, introduction (A 51 / B 75)')] }),
C('kant-phenomene', T, "Quelle distinction Kant établit-il entre phénomène et chose en soi ?",
  "Nous ne connaissons les choses que telles qu'elles nous apparaissent dans l'espace et le temps (formes a priori de la sensibilité), non telles qu'elles sont en soi.",
  { a: ['Kant'], o: 'Critique de la raison pure', n: ['la vérité', 'la science'], s: [pd('Kant, Critique de la raison pure, Esthétique transcendantale')] }),
C('kant-bonne-volonte', T, "Qu'est-ce qui est bon sans restriction selon Kant ?",
  "Seule une bonne volonté. Elle est bonne par son vouloir, non par ses effets ni par son aptitude à atteindre un but.",
  { a: ['Kant'], o: 'Fondements de la métaphysique des mœurs', n: ['le devoir'], s: [pd('Kant, Fondements de la métaphysique des mœurs, section I, AK IV, 393')] }),
C('kant-devoir', T, "Quelle différence entre agir conformément au devoir et agir par devoir ?",
  "Le commerçant qui ne surfait pas ses prix par intérêt agit conformément au devoir, non par devoir. Seul le respect de la loi morale donne valeur morale à l'acte.",
  { a: ['Kant'], o: 'Fondements de la métaphysique des mœurs', n: ['le devoir'], s: [pd('Kant, Fondements de la métaphysique des mœurs, section I, AK IV, 397-398')] }),
C('kant-imperatif', T, "Quelles sont les principales formules de l'impératif catégorique ?",
  "Loi universelle (agis selon la maxime que tu peux vouloir loi universelle), loi de la nature, humanité comme fin en soi, autonomie (volonté législatrice).",
  { a: ['Kant'], o: 'Fondements de la métaphysique des mœurs', n: ['le devoir', 'la liberté'], s: [pd('Kant, Fondements de la métaphysique des mœurs, section II, AK IV, 421 ; 429 ; 431')] }),
C('kant-humanite', T, "Que prescrit la formule de l'humanité ?",
  "Traiter l'humanité, en sa personne comme en celle d'autrui, toujours en même temps comme une fin, jamais simplement comme un moyen.",
  { a: ['Kant'], o: 'Fondements de la métaphysique des mœurs', n: ['le devoir', 'la justice'], s: [pd('Kant, Fondements de la métaphysique des mœurs, section II, AK IV, 429')] }),
C('kant-anthropologie', T, "Que cherche l'Anthropologie du point de vue pragmatique ?",
  "Non ce que la nature fait de l'homme, mais ce que l'homme, être libre, fait ou peut et doit faire de lui-même.",
  { a: ['Kant'], o: "Anthropologie d'un point de vue pragmatique", n: ['la nature', 'la liberté'], s: [pd("Kant, Anthropologie d'un point de vue pragmatique (1798), préface, AK VII, 119")] }),
C('kant-gout', T, "Quelles sont les caractéristiques du jugement de goût (Critique de la faculté de juger) ?",
  "Plaisir désintéressé ; universalité sans concept ; finalité sans fin ; nécessité d'une adhésion exemplaire. Il n'est ni connaissance ni simple agrément.",
  { a: ['Kant'], o: 'Critique de la faculté de juger', n: ["l'art"], s: [pd('Kant, Critique de la faculté de juger, Analytique du beau, §§1-22')] }),
C('kant-insociable', T, "Qu'est-ce que l'« insociable sociabilité » ?",
  "Le penchant des hommes à entrer en société, joint à une résistance constante qui menace de la dissoudre. Cet antagonisme développe leurs dispositions.",
  { a: ['Kant'], o: "Idée d'une histoire universelle d'un point de vue cosmopolitique", n: ["l'État", 'la nature'], s: [pd("Kant, Idée d'une histoire universelle d'un point de vue cosmopolitique (1784), 4e proposition, AK VIII, 20")] }),
C('kant-paix', T, "Quels sont les trois articles définitifs du Projet de paix perpétuelle ?",
  "Constitution républicaine dans chaque État ; droit des gens fondé sur une fédération d'États libres ; droit cosmopolitique limité à l'hospitalité universelle.",
  { a: ['Kant'], o: 'Projet de paix perpétuelle', n: ["l'État", 'la justice'], s: [pd('Kant, Zum ewigen Frieden (1795), 2e section, AK VIII, 349-360')] }),

// ---------- ROUSSEAU ----------
C('rous-cit-libre', 'citation', "De qui est « L'homme est né libre, et partout il est dans les fers » ?",
  "Rousseau, Du contrat social, I, 1. La suite : comment ce changement s'est-il fait ? Il l'ignore ; ce qui peut le rendre légitime, il croit pouvoir le résoudre.",
  { a: ['Rousseau'], o: 'Du contrat social', n: ['la liberté', "l'État"], s: [pd('Rousseau, Du contrat social, I, 1')] }),
C('rous-probleme', T, "Quel est le problème fondamental auquel répond le contrat social ?",
  "Trouver une forme d'association qui protège chacun avec toute la force commune, et par laquelle chacun, s'unissant à tous, n'obéisse pourtant qu'à lui-même.",
  { a: ['Rousseau'], o: 'Du contrat social', n: ['la liberté', "l'État", 'la justice'], s: [pd('Rousseau, Du contrat social, I, 6')] }),
C('rous-volonte-generale', T, "Volonté générale et volonté de tous : quelle différence ?",
  "La volonté générale ne regarde que l'intérêt commun ; la volonté de tous est la somme des volontés particulières, ou intérêt privé.",
  { a: ['Rousseau'], o: 'Du contrat social', n: ["l'État", 'la justice'], s: [pd('Rousseau, Du contrat social, II, 3')] }),
C('rous-representation', T, "Pourquoi Rousseau rejette-t-il la représentation politique ?",
  "La souveraineté, exercice de la volonté générale, est inaliénable et ne peut être représentée. Les députés ne sont que des commissaires ; le peuple anglais n'est libre que pendant l'élection.",
  { a: ['Rousseau'], o: 'Du contrat social', n: ["l'État", 'la liberté'], s: [pd('Rousseau, Du contrat social, II, 1 ; III, 15')] }),
C('rous-amour-propre', T, "Amour de soi et amour-propre : que distingue Rousseau ?",
  "L'amour de soi est le sentiment naturel de conservation. L'amour-propre est relatif : né en société, il pousse à se comparer aux autres et à vouloir leur préférence.",
  { a: ['Rousseau'], o: "Discours sur l'origine et les fondements de l'inégalité", n: ['la nature', 'le bonheur'], s: [pd("Rousseau, Discours sur l'inégalité, note XV (2e partie)")] }),
C('rous-perfectibilite', T, "Qu'est-ce que la perfectibilité chez Rousseau ?",
  "La faculté de se perfectionner, propre à l'homme et qui le distingue de l'animal. Elle est la source de ses progrès comme de ses malheurs.",
  { a: ['Rousseau'], o: "Discours sur l'origine et les fondements de l'inégalité", n: ['la nature', 'le temps'], s: [pd("Rousseau, Discours sur l'inégalité, 1re partie")] }),
C('rous-propriete', T, "Comment débute la seconde partie du Discours sur l'inégalité ?",
  "Par le premier qui, ayant enclos un terrain, dit « ceci est à moi » et trouva des gens assez simples pour le croire : le vrai fondateur de la société civile.",
  { a: ['Rousseau'], o: "Discours sur l'origine et les fondements de l'inégalité", n: ['la justice', "l'État"], s: [pd("Rousseau, Discours sur l'inégalité, 2e partie, début")] }),
C('rous-education-negative', T, "Qu'est-ce que l'éducation négative (Émile, II) ?",
  "Ne pas enseigner la vertu ni la vérité, mais garantir le cœur du vice et l'esprit de l'erreur, et laisser l'enfant apprendre par l'expérience des choses.",
  { a: ['Rousseau'], o: 'Émile ou De l’éducation', n: ['la nature'], s: [pd("Rousseau, Émile ou De l'éducation, II")] }),
C('rous-conscience', T, "Comment Rousseau caractérise-t-il la conscience morale (Profession de foi du vicaire savoyard) ?",
  "Comme un instinct divin, guide sûr du bien et du mal, distinct de la raison qui peut nous égarer : elle fait de l'homme un être moral.",
  { a: ['Rousseau'], o: 'Émile ou De l’éducation', n: ['la conscience', 'le devoir'], s: [pd("Rousseau, Émile, IV, Profession de foi du vicaire savoyard")] }),
C('rous-religion-civile', T, "Quels sont les dogmes de la religion civile (Contrat social, IV, 8) ?",
  "Existence d'une divinité, vie à venir, bonheur des justes et châtiment des méchants, sainteté du contrat et des lois. Seule l'intolérance est proscrite.",
  { a: ['Rousseau'], o: 'Du contrat social', n: ['la religion', "l'État"], s: [pd('Rousseau, Du contrat social, IV, 8')] }),
];
