import { C, pd, es } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- HEGEL ----------
C('heg-histoire-liberte', T, "Comment Hegel définit-il le sens de l'histoire universelle (Introduction à la philosophie de l'histoire) ?",
  "Comme le progrès dans la conscience de la liberté : l'Orient savait qu'un seul est libre, le monde gréco-romain que quelques-uns le sont, le monde germanique que tous le sont.",
  { a: ['Hegel'], o: "Leçons sur la philosophie de l'histoire (Introduction)", n: ['la liberté', 'le temps', "l'État"], s: [pd("Hegel, Vorlesungen über die Philosophie der Geschichte, Einleitung (trad. fr. à préciser)")] }),
C('heg-ruse', T, "Qu'est-ce que la « ruse de la raison » ?",
  "La raison laisse les passions des individus agir pour elle : les grands hommes réalisent à leur insu l'Idée, et paient souvent ce rôle de leur bonheur.",
  { a: ['Hegel'], o: "Leçons sur la philosophie de l'histoire (Introduction)", n: ['la raison', 'le temps'], s: [pd("Hegel, Philosophie de l'histoire, Introduction, section sur les passions et les grands hommes")] }),
C('heg-rationnel-reel', T, "Que signifie la formule hégélienne sur le rationnel et l'effectif (préface des Principes de la philosophie du droit) ?",
  "Non que tout ce qui existe soit bon, mais que la raison se réalise dans l'effectif. Philosopher, c'est saisir son temps dans la pensée.",
  { a: ['Hegel'], o: 'Principes de la philosophie du droit', n: ['la raison', 'le temps', 'la vérité'], s: [pd('Hegel, Principes de la philosophie du droit, préface')] }),
C('heg-maitre-esclave', T, "Quel est le retournement de la dialectique du maître et de l'esclave ?",
  "Le maître dépend de l'esclave, dont la reconnaissance est celle d'un non-libre. L'esclave, par la crainte et le travail qui forme la chose, accède à la conscience de soi.",
  { a: ['Hegel'], o: "Phénoménologie de l'esprit", n: ['le travail', 'la conscience', 'la liberté'], s: [pd("Hegel, Phénoménologie de l'esprit, IV, A (« Indépendance et dépendance de la conscience de soi »)")] }),
C('heg-reconnaissance', T, "Pourquoi la conscience de soi a-t-elle besoin d'autrui, selon Hegel ?",
  "Elle n'est ce qu'elle est que reconnue par une autre conscience de soi. D'où la lutte pour la reconnaissance, où chacun cherche à être reconnu comme libre.",
  { a: ['Hegel'], o: "Phénoménologie de l'esprit", n: ['la conscience', 'la liberté'], s: [pd("Hegel, Phénoménologie de l'esprit, IV, A")] }),
C('heg-droit-plan', T, "Quels sont les trois moments des Principes de la philosophie du droit ?",
  "Le droit abstrait (propriété, contrat), la moralité subjective, la vie éthique (famille, société civile, État).",
  { a: ['Hegel'], o: 'Principes de la philosophie du droit', n: ['la justice', "l'État", 'le devoir'], s: [pd('Hegel, Principes de la philosophie du droit, plan général (§§33, 105, 141)')] }),
C('heg-etat', T, "Pourquoi l'État est-il, pour Hegel, plus que la société civile ?",
  "La société civile est le système des besoins, où domine l'intérêt particulier. L'État est la réalité de l'Idée éthique, où liberté individuelle et liberté substantielle se concilient.",
  { a: ['Hegel'], o: 'Principes de la philosophie du droit', n: ["l'État", 'la liberté'], s: [pd('Hegel, Principes de la philosophie du droit, §§182-188 ; §§257-258')] }),
C('heg-art', T, "Quelle place Hegel accorde-t-il à l'art dans l'esprit absolu ?",
  "L'art est la première forme de l'esprit absolu : présentation sensible de l'Idée. Il est dépassé par la religion puis la philosophie (thèse dite de la « fin de l'art »).",
  { a: ['Hegel'], o: 'Esthétique', n: ["l'art", 'la religion'], s: [pd("Hegel, Esthétique, Introduction ; Encyclopédie des sciences philosophiques, §§553-577")] }),

// ---------- NIETZSCHE ----------
C('niet-morale-esclaves', T, "Qu'appelle Nietzsche la morale des esclaves ?",
  "Une morale née du ressentiment des faibles : ils nomment « mauvais » le puissant et « bon » leur impuissance. Renversement des valeurs aristocratiques.",
  { a: ['Nietzsche'], o: 'Généalogie de la morale', n: ['le devoir', 'la justice'], s: [pd('Nietzsche, Zur Genealogie der Moral, I, §§7, 10-11 (trad. fr. à préciser)')] }),
C('niet-dieu-mort', T, "Que signifie « Dieu est mort » ?",
  "Un constat culturel, non une thèse athée de plus : la croyance en Dieu n'est plus crédible et ruine les valeurs qui reposaient sur elle. Risque : le nihilisme.",
  { a: ['Nietzsche'], o: 'Le Gai Savoir', n: ['la religion', 'la vérité'], s: [pd('Nietzsche, Die fröhliche Wissenschaft, §125 ; §343')] }),
C('niet-eternel-retour', T, "Quelle épreuve pose la pensée de l'éternel retour (Gai Savoir, §341) ?",
  "Pourrais-je vouloir revivre infiniment la même vie ? C'est le critère de l'affirmation de la vie (amor fati), non une doctrine cosmologique à démontrer.",
  { a: ['Nietzsche'], o: 'Le Gai Savoir', n: ['le temps', 'le bonheur'], s: [pd('Nietzsche, Die fröhliche Wissenschaft, §341')] }),
C('niet-metamorphoses', T, "Quelles sont les trois métamorphoses de l'esprit dans Zarathoustra ?",
  "Le chameau (qui porte les fardeaux), le lion (qui dit non et conquiert sa liberté), l'enfant (innocence, oubli, commencement, jeu créateur).",
  { a: ['Nietzsche'], o: 'Ainsi parlait Zarathoustra', n: ['la liberté'], s: [pd('Nietzsche, Also sprach Zarathustra, I, « Des trois métamorphoses »')] }),
C('niet-surhomme', T, "Que désigne le surhomme dans le Prologue de Zarathoustra ?",
  "Le sens de la terre : ce que l'homme doit surmonter, comme le singe est pour l'homme une honte. Il s'oppose au « dernier homme », conservateur et satisfait.",
  { a: ['Nietzsche'], o: 'Ainsi parlait Zarathoustra', n: ['la nature'], s: [pd('Nietzsche, Also sprach Zarathustra, Prologue, §§3-5')] }),
C('niet-verite-metaphores', T, "Que devient la vérité dans « Sur la vérité et le mensonge au sens extra-moral » ?",
  "Une multitude mobile de métaphores et d'anthropomorphismes : des illusions dont on a oublié qu'elles le sont, usées comme des pièces devenues simple métal.",
  { a: ['Nietzsche'], o: 'Sur la vérité et le mensonge au sens extra-moral', n: ['la vérité', 'le langage'], s: [pd('Nietzsche, Über Wahrheit und Lüge im aussermoralischen Sinne (1873), §1')] }),
C('niet-perspectivisme', T, "Qu'affirme le perspectivisme de Nietzsche (Généalogie, III, §12) ?",
  "Il n'y a qu'un voir en perspective, un « connaître » en perspective : plus nous laissons d'yeux parler, plus notre « objectivité » est complète.",
  { a: ['Nietzsche'], o: 'Généalogie de la morale', n: ['la vérité', 'la science'], s: [pd('Nietzsche, Zur Genealogie der Moral, III, §12')] }),
C('niet-devenir-soi', T, "Que veut dire « devenir ce que l'on est » chez Nietzsche ?",
  "Non révéler une essence donnée, mais se constituer en donnant style à son caractère. Sous-titre d'Ecce homo, écho de Pindare repris dans le Gai Savoir §270.",
  { a: ['Nietzsche'], o: 'Ecce homo', n: ['la conscience', 'la liberté'], s: [pd('Nietzsche, Ecce homo, sous-titre ; Die fröhliche Wissenschaft, §270 ; §290')] }),
C('niet-fragments', 'methode', "Pourquoi faut-il être prudent avec les Fragments posthumes de Nietzsche ?",
  "Ce sont des notes non destinées à publication. La compilation « La Volonté de puissance » est une construction posthume ; on cite l'édition Colli-Montinari (date + numéro du fragment).",
  { a: ['Nietzsche'], o: 'Fragments posthumes', s: [es('Nietzsche, Nachgelassene Fragmente, éd. Colli-Montinari (KGW / KSA)')] , note: "Chronologie de l'édition à recouper avec la préface de l'édition française (Gallimard)." }),
C('niet-apollinien', T, "Qu'opposent l'apollinien et le dionysiaque dans La Naissance de la tragédie ?",
  "L'apollinien : forme, mesure, rêve, belle apparence. Le dionysiaque : ivresse, démesure, dissolution de l'individu. La tragédie naît de leur union.",
  { a: ['Nietzsche'], o: 'La Naissance de la tragédie', n: ["l'art"], s: [pd('Nietzsche, Die Geburt der Tragödie (1872), §§1-2')] }),

// ---------- FREUD ----------
C('freud-topiques', T, "Quelles sont la première et la seconde topique freudiennes ?",
  "Première : inconscient, préconscient, conscient. Seconde (1923) : ça, moi, surmoi ; le moi est en grande partie inconscient et soumis à trois maîtres.",
  { a: ['Freud'], o: 'Le Moi et le Ça', n: ["l'inconscient", 'la conscience'], s: [pd('Freud, Das Ich und das Es (1923), chap. II et V ; Métapsychologie, « L’inconscient » (1915)')] }),
C('freud-blessures', T, "Quelles sont les trois blessures narcissiques infligées à l'humanité ?",
  "Cosmologique (Copernic), biologique (Darwin), psychologique (Freud) : le moi n'est pas maître dans sa propre maison.",
  { a: ['Freud'], o: 'Une difficulté de la psychanalyse', n: ["l'inconscient", 'la science'], s: [pd('Freud, Eine Schwierigkeit der Psychoanalyse (1917)')] }),
C('freud-reve', T, "Comment Freud explique-t-il le rêve ?",
  "Comme accomplissement déguisé d'un désir refoulé. Le travail du rêve (condensation, déplacement) transforme le contenu latent en contenu manifeste.",
  { a: ['Freud'], o: "L'Interprétation du rêve", n: ["l'inconscient"], s: [pd('Freud, Die Traumdeutung (1900), chap. II-IV, VI')] }),
C('freud-refoulement', T, "Qu'est-ce que le refoulement ?",
  "L'opération qui écarte de la conscience une représentation pulsionnelle inacceptable. Le refoulé fait retour de façon déguisée : symptômes, rêves, actes manqués.",
  { a: ['Freud'], o: 'Métapsychologie', n: ["l'inconscient"], s: [pd('Freud, Die Verdrängung (1915)')] }),
C('freud-actes-manques', T, "Que montrent les actes manqués (Psychopathologie de la vie quotidienne) ?",
  "Lapsus, oublis, méprises ont un sens : ils sont des compromis entre une intention consciente et une intention refoulée, preuve de l'inconscient chez le sujet normal.",
  { a: ['Freud'], o: 'Psychopathologie de la vie quotidienne', n: ["l'inconscient", 'le langage'], s: [pd('Freud, Zur Psychopathologie des Alltagslebens (1901)')] }),
C('freud-pulsions', T, "Quel est le dualisme pulsionnel de l'Au-delà du principe de plaisir ?",
  "Pulsions de vie (Éros, liaison) contre pulsions de mort (retour à l'inorganique, répétition). Freud les introduit à partir de la compulsion de répétition.",
  { a: ['Freud'], o: 'Au-delà du principe de plaisir', n: ["l'inconscient", 'le bonheur'], s: [pd('Freud, Jenseits des Lustprinzips (1920)')] }),
C('freud-malaise', T, "Pourquoi la civilisation engendre-t-elle un malaise selon Freud ?",
  "Elle exige le renoncement pulsionnel (sexualité, agressivité) : le surmoi retourne l'agressivité contre le moi, d'où un sentiment de culpabilité croissant.",
  { a: ['Freud'], o: 'Le Malaise dans la culture', n: ['le bonheur', "l'État"], s: [pd('Freud, Das Unbehagen in der Kultur (1930), chap. III et VII')] }),
C('freud-sublimation', T, "Qu'est-ce que la sublimation ?",
  "Le détournement d'une énergie pulsionnelle vers un but non sexuel socialement valorisé (création artistique, recherche intellectuelle).",
  { a: ['Freud'], o: 'Un souvenir d’enfance de Léonard de Vinci', n: ["l'art", "l'inconscient"], s: [pd('Freud, Eine Kindheitserinnerung des Leonardo da Vinci (1910) ; Das Unbehagen in der Kultur, chap. II')] }),

// ---------- BERGSON ----------
C('berg-duree', T, "Que distingue Bergson entre durée et temps spatialisé ?",
  "Le temps des horloges juxtapose des instants homogènes ; la durée est continuité qualitative où les états se pénètrent, saisie par la conscience immédiate.",
  { a: ['Bergson'], o: 'Essai sur les données immédiates de la conscience', n: ['le temps', 'la conscience'], s: [es('Bergson, Essai sur les données immédiates de la conscience (1889), chap. II')] }),
C('berg-liberte', T, "Quand un acte est-il libre selon Bergson ?",
  "Quand il émane de la personnalité tout entière et l'exprime, comme le fruit mûr. Le déterminisme naît d'une confusion entre durée et espace.",
  { a: ['Bergson'], o: 'Essai sur les données immédiates de la conscience', n: ['la liberté', 'le temps'], s: [es('Bergson, Essai sur les données immédiates de la conscience, chap. III')] }),
C('berg-memoire', T, "Quelle différence entre souvenir pur et mémoire-habitude (Matière et mémoire) ?",
  "La mémoire-habitude est un mécanisme moteur acquis par répétition ; le souvenir pur est représentation d'un événement unique, conservé et virtuel, actualisé par le besoin présent.",
  { a: ['Bergson'], o: 'Matière et mémoire', n: ['le temps', 'la conscience'], s: [es('Bergson, Matière et mémoire (1896), chap. II')] }),
C('berg-intuition', T, "Qu'est-ce que l'intuition bergsonienne ?",
  "Une méthode : sympathie qui coïncide avec ce qu'un objet a d'unique, en opposition à l'analyse qui le traduit en éléments déjà connus.",
  { a: ['Bergson'], o: 'La Pensée et le mouvant', n: ['la vérité', 'la science'], s: [es('Bergson, Introduction à la métaphysique (1903), in La Pensée et le mouvant')] }),
C('berg-rire', T, "Quelle est la thèse du Rire ?",
  "Le rire punit socialement du « mécanique plaqué sur du vivant » : raideur, automatisme, inattention à la vie.",
  { a: ['Bergson'], o: 'Le Rire', n: ["l'art"], s: [es('Bergson, Le Rire (1900), chap. I')] }),
C('berg-elan-vital', T, "Que désigne l'élan vital dans L'Évolution créatrice ?",
  "Le courant de création qui traverse la matière et se ramifie en directions divergentes (végétal, instinct, intelligence) : l'évolution n'est ni mécanique ni finalisée.",
  { a: ['Bergson'], o: "L'Évolution créatrice", n: ['la nature', 'le temps'], s: [es("Bergson, L'Évolution créatrice (1907), chap. II")] }),
C('berg-morale', T, "Quelle différence entre morale close et morale ouverte (Deux Sources) ?",
  "Close : obligation sociale, pression d'habitudes, cohésion du groupe. Ouverte : élan d'amour de l'humanité porté par des personnalités exemplaires (les mystiques).",
  { a: ['Bergson'], o: 'Les Deux Sources de la morale et de la religion', n: ['le devoir', 'la religion'], s: [es('Bergson, Les Deux Sources de la morale et de la religion (1932), chap. I et IV')] }),

// ---------- SARTRE ----------
C('sart-cit-existence', 'citation', "Quelle formule résume l'existentialisme sartrien ?",
  "« L'existence précède l'essence » : l'homme existe d'abord, se définit ensuite par ses actes (L'existentialisme est un humanisme, 1946).",
  { a: ['Sartre'], o: "L'existentialisme est un humanisme", n: ['la liberté'], s: [es("Sartre, L'existentialisme est un humanisme (1946)")] }),
C('sart-condamne-libre', T, "Pourquoi l'homme est-il « condamné à être libre » ?",
  "Il n'a pas choisi d'exister mais, une fois jeté dans le monde, il est responsable de tout ce qu'il fait ; il ne peut se réfugier ni dans une nature ni dans des excuses.",
  { a: ['Sartre'], o: "L'existentialisme est un humanisme", n: ['la liberté', 'le devoir'], s: [es("Sartre, L'existentialisme est un humanisme ; L'Être et le néant, IV")] }),
C('sart-mauvaise-foi', T, "Qu'est-ce que la mauvaise foi (exemple du garçon de café) ?",
  "Se mentir à soi-même en se réduisant à un rôle (être « garçon de café » comme une chose) pour fuir sa liberté. Elle nie la transcendance ou la facticité.",
  { a: ['Sartre'], o: "L'Être et le néant", n: ['la conscience', "l'inconscient", 'la liberté'], s: [es("Sartre, L'Être et le néant (1943), I, chap. II")] }),
C('sart-pour-soi', T, "Que distinguent l'en-soi et le pour-soi ?",
  "L'en-soi est l'être plein des choses, identique à lui-même. Le pour-soi est la conscience : néant qui se rapporte à l'être, toujours ce qu'il n'est pas et n'étant pas ce qu'il est.",
  { a: ['Sartre'], o: "L'Être et le néant", n: ['la conscience'], s: [es("Sartre, L'Être et le néant, introduction et I")] }),
C('sart-regard', T, "Quel rôle joue le regard d'autrui dans L'Être et le néant ?",
  "Il me révèle comme objet pour un autre (honte) : autrui est le médiateur indispensable entre moi et moi-même, et menace ma liberté.",
  { a: ['Sartre'], o: "L'Être et le néant", n: ['la conscience', 'la liberté'], s: [es("Sartre, L'Être et le néant, III, chap. I, IV")] }),
C('sart-cit-enfer', 'citation', "D'où vient « L'enfer, c'est les autres » ?",
  "Huis clos (1944), scène V. Sartre précisera que la formule vise des rapports faussés par le jugement d'autrui, non tout rapport à autrui.",
  { a: ['Sartre'], o: 'Huis clos', n: ['la conscience'], s: [es('Sartre, Huis clos (1944), scène V')] }),
C('sart-engagement', T, "Pourquoi choisir pour soi, c'est choisir pour l'humanité (L'existentialisme est un humanisme) ?",
  "En me choisissant, je crée une image de l'homme tel que je juge qu'il doit être. D'où l'angoisse, l'abandon et le désespoir comme conditions de l'action responsable.",
  { a: ['Sartre'], o: "L'existentialisme est un humanisme", n: ['le devoir', 'la liberté'], s: [es("Sartre, L'existentialisme est un humanisme")] }),

// ---------- ARENDT ----------
C('aren-vita-activa', T, "Quelle distinction Arendt établit-elle entre labeur, travail et action ?",
  "Labeur : cycle biologique de la vie. Travail : fabrication d'un monde durable d'objets. Action : agir avec d'autres par la parole, condition de la politique et de la pluralité.",
  { a: ['Arendt'], o: "Condition de l'homme moderne", n: ['le travail', 'la technique', 'la liberté'], s: [es("Arendt, Condition de l'homme moderne (The Human Condition, 1958), chap. III-V")] }),
C('aren-natalite', T, "Qu'est-ce que la natalité chez Arendt ?",
  "Le fait que chaque naissance est un nouveau commencement : condition ontologique de l'action et de la liberté, capacité d'interrompre le cours automatique des choses.",
  { a: ['Arendt'], o: "Condition de l'homme moderne", n: ['la liberté', 'le temps'], s: [es("Arendt, Condition de l'homme moderne, chap. V, §§24-25")] }),
C('aren-banalite', T, "Que signifie la « banalité du mal » (Eichmann à Jérusalem) ?",
  "Le mal peut être commis par un homme ordinaire, sans haine ni monstruosité, à cause d'une absence de pensée : incapacité de se placer du point de vue d'autrui.",
  { a: ['Arendt'], o: 'Eichmann à Jérusalem', n: ['la conscience', 'le devoir', 'la justice'], s: [es('Arendt, Eichmann à Jérusalem (1963), épilogue et postface')] }),
C('aren-totalitarisme', T, "Qu'est-ce qui distingue le totalitarisme d'une tyrannie ordinaire ?",
  "Il repose sur la terreur et l'idéologie : il ne vise pas seulement à contrôler mais à transformer l'espèce humaine, en supprimant spontanéité et pluralité.",
  { a: ['Arendt'], o: 'Les Origines du totalitarisme', n: ["l'État", 'la liberté'], s: [es('Arendt, Les Origines du totalitarisme (1951), 3e partie, chap. XIII')] }),
C('aren-verite-politique', T, "Vérité de fait et opinion : que défend Arendt dans « Vérité et politique » ?",
  "Les vérités de fait sont fragiles et menacées par le mensonge organisé. Le domaine politique repose sur l'opinion, mais l'opinion ne peut sacrifier les faits.",
  { a: ['Arendt'], o: 'La Crise de la culture', n: ['la vérité', "l'État"], s: [es('Arendt, « Vérité et politique », in La Crise de la culture (1961 ; 1964 pour cet essai)')] }),
C('aren-education', T, "Quel double rôle Arendt donne-t-elle à l'éducation (« La crise de l'éducation ») ?",
  "Protéger l'enfant du monde et le monde de l'enfant : transmettre un monde commun, tout en préservant la possibilité du neuf que porte chaque génération.",
  { a: ['Arendt'], o: 'La Crise de la culture', n: ['le temps'], s: [es("Arendt, « La crise de l'éducation », in La Crise de la culture")] }),
C('aren-pouvoir-violence', T, "Comment Arendt distingue-t-elle pouvoir et violence ?",
  "Le pouvoir naît de l'action concertée et dépend du consentement ; la violence est instrumentale et se passe du nombre. Là où l'un domine pleinement, l'autre disparaît.",
  { a: ['Arendt'], o: 'Du mensonge à la violence', n: ["l'État", 'la justice'], s: [es('Arendt, On Violence (1970) / Du mensonge à la violence, section II')] }),
];
