import { C, pd, es, of, se } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Auteurs tombés récemment (compléments) ----------
C('simo-concretisation', T, "Qu'est-ce que la « concrétisation » de l'objet technique selon Simondon ?",
  "Le passage d'un objet abstrait (éléments juxtaposés) à un objet concret dont les fonctions se soutiennent mutuellement dans un système cohérent, comme un moteur refroidi par ses propres ailettes.",
  { a: ['Simondon'], o: 'Du mode d’existence des objets techniques', n: ['la technique'], s: [es("Simondon, Du mode d'existence des objets techniques (1958), 1re partie, chap. I")] }),
C('simo-culture', T, "Que reproche Simondon à la culture à l'égard des objets techniques ?",
  "De les traiter comme de simples ustensiles, sans reconnaître leur réalité humaine : elle oppose culture et technique, et engendre une aliénation. Il faut intégrer la technicité à la culture.",
  { a: ['Simondon'], o: 'Du mode d’existence des objets techniques', n: ['la technique', 'le travail'], s: [es("Simondon, Du mode d'existence des objets techniques, introduction")] }),
C('simo-technicite', T, "Simondon : que désigne la « technicité » et comment se rattache-t-elle aux autres modes d'existence ?",
  "Un mode fondamental de rapport au monde, issu du déphasage d'un mode magique unitaire (avec la religion). La 3e partie (« Essence de la technicité ») en étudie la genèse.",
  { a: ['Simondon'], o: 'Du mode d’existence des objets techniques', n: ['la technique', 'la religion'], s: [es("Simondon, Du mode d'existence des objets techniques, 3e partie"), of("Programme du CAPES/CAFEP : 3e partie, chap. II (sujet de l'écrit 2025, à recouper avec le rapport de jury)")], note: "Titre exact du chapitre II de la 3e partie non vérifié." }),
C('spin-tp-comprendre', 'citation', "Quelle est la règle de méthode du Traité politique (I, 4) ?",
  "« Non ridere, non lugere, neque detestari, sed intelligere » : ni rire, ni pleurer, ni détester, mais comprendre les actions humaines.",
  { a: ['Spinoza'], o: 'Traité politique', n: ["l'État", 'la raison'], s: [pd('Spinoza, Tractatus politicus, I, §4')] }),
C('spin-tp-droit', T, "Pour Spinoza, que sont le droit naturel et le droit de l'État (Traité politique) ?",
  "Le droit naturel de chacun est sa puissance. Le droit de l'État (imperium) est la puissance de la multitude, conduite comme par une seule pensée.",
  { a: ['Spinoza'], o: 'Traité politique', n: ["l'État", 'la justice', 'la nature'], s: [pd('Spinoza, Tractatus politicus, II, §§4 ; III, §2')] }),
C('spin-tp-paix', T, "Comment Spinoza définit-il la paix (Traité politique, V, 4) ?",
  "Non l'absence de guerre, mais une vertu, qui naît de la force d'âme ; un État dont les sujets ne se battent pas, mais n'agissent que par inertie, est une solitude.",
  { a: ['Spinoza'], o: 'Traité politique', n: ["l'État", 'la liberté'], s: [pd('Spinoza, Tractatus politicus, V, §4')] }),
C('spin-conatus', T, "Qu'est-ce que le conatus (Éthique III) ?",
  "L'effort par lequel chaque chose persévère dans son être : c'est son essence actuelle. Désir, joie et tristesse se définissent par rapport à cet effort.",
  { a: ['Spinoza'], o: 'Éthique', n: ['le bonheur', 'la nature'], s: [pd('Spinoza, Éthique, III, prop. 6-7 ; définitions des affects')] }),
C('spin-liberte', T, "Comment Spinoza conçoit-il la liberté ?",
  "Est libre ce qui agit par la seule nécessité de sa nature. L'illusion du libre arbitre vient de l'ignorance des causes ; la liberté humaine croît avec la connaissance adéquate.",
  { a: ['Spinoza'], o: 'Éthique', n: ['la liberté', 'la raison'], s: [pd('Spinoza, Éthique, I, déf. 7 ; Lettre LVIII à Schuller')] }),

// ---------- Autres auteurs du programme ----------
C('pasc-cit-coeur', 'citation', "De qui est « Le cœur a ses raisons que la raison ne connaît point » ?",
  "Pascal, Pensées (fragment 277 chez Brunschvicg, 423 chez Lafuma). Le cœur connaît les premiers principes par sentiment ; ce n'est pas une opposition à la raison.",
  { a: ['Pascal'], o: 'Pensées', n: ['la raison', 'la religion'], s: [pd('Pascal, Pensées, Brunschvicg 277 = Lafuma 423')] }),
C('pasc-divertissement', T, "Qu'est-ce que le divertissement chez Pascal ?",
  "L'agitation qui détourne l'homme de la pensée de sa condition misérable : il ne sait pas rester au repos dans une chambre.",
  { a: ['Pascal'], o: 'Pensées', n: ['le bonheur', 'le temps'], s: [pd('Pascal, Pensées, Brunschvicg 139 = Lafuma 136')] }),
C('hobb-cit-loup', 'citation', "D'où vient « L'homme est un loup pour l'homme » ?",
  "Hobbes, De Cive, épître dédicatoire (« homo homini lupus », emprunt à Plaute). Dans l'état de nature, guerre de tous contre tous (Léviathan, XIII).",
  { a: ['Hobbes'], o: 'De Cive', n: ["l'État", 'la nature'], s: [pd('Hobbes, De Cive, épître dédicatoire ; Léviathan, XIII')] }),
C('lock-identite', T, "Comment Locke définit-il l'identité personnelle ?",
  "Par la conscience : une personne est un être pensant qui se reconnaît le même à divers moments et lieux, en lien avec ses souvenirs, non avec la substance.",
  { a: ['Locke'], o: 'Essai sur l’entendement humain', n: ['la conscience', 'le temps'], s: [pd("Locke, Essai sur l'entendement humain, II, chap. 27, §9")] }),
C('hume-causalite', T, "Que soutient Hume sur la causalité ?",
  "Nous n'observons que la succession constante de deux événements, jamais un lien nécessaire : l'idée de cause vient de l'habitude, non de la raison.",
  { a: ['Hume'], o: 'Enquête sur l’entendement humain', n: ['la science', 'la raison'], s: [pd("Hume, Enquête sur l'entendement humain, sections IV-VII")] }),
C('marx-thesexi', T, "Quelle est la onzième thèse sur Feuerbach ?",
  "Les philosophes n'ont fait qu'interpréter le monde de différentes manières ; ce qui importe, c'est de le transformer.",
  { a: ['Marx'], o: 'Thèses sur Feuerbach', n: ['le travail', 'la vérité'], s: [pd('Marx, Thesen über Feuerbach (1845), thèse XI')], note: 'Formulation de la traduction à contrôler.' }),
C('marx-alienation', T, "Comment Marx décrit-il le travail aliéné (Manuscrits de 1844) ?",
  "Le travailleur est dépossédé du produit, de l'acte de production, de son essence générique et d'autrui : le travail devient un moyen de subsistance, non l'expression de soi.",
  { a: ['Marx'], o: 'Manuscrits de 1844', n: ['le travail', 'la liberté'], s: [pd('Marx, Ökonomisch-philosophische Manuskripte (1844), Premier manuscrit, « Le travail aliéné »')] }),
C('epic-plaisirs', T, "Comment Épicure classe-t-il les désirs (Lettre à Ménécée) ?",
  "Naturels et nécessaires (boire, manger), naturels non nécessaires, ni naturels ni nécessaires (vains). Le bonheur consiste à limiter ses désirs : absence de douleur et de trouble.",
  { a: ['Épicure'], o: 'Lettre à Ménécée', n: ['le bonheur', 'la nature'], s: [pd('Épicure, Lettre à Ménécée, §§127-132 (Diogène Laërce, X)')] }),
C('mach-verite-effective', T, "Que signifie la « vérité effective de la chose » chez Machiavel (Le Prince, XV) ?",
  "S'en tenir à ce qui est réellement, non à l'imagination : le prince qui veut toujours être bon se perd parmi tant de méchants ; il doit savoir n'être pas bon.",
  { a: ['Machiavel'], o: 'Le Prince', n: ["l'État", 'le devoir'], s: [pd('Machiavel, Il Principe (1532), chap. XV')] }),
];
