import { C, pd, es, of, se } from './dsl.mjs';
const PROG = of('Programme de philosophie des classes terminales générales et technologiques, BO spécial n° 8 du 25 juillet 2019');
const N = 'notion';
const rep = (id, q, r, s = []) => C(id, 'repere', q, r, { s: [PROG, ...s], note: "L'énoncé exact des repères est à contrôler dans le BO (accès au texte officiel impossible pendant la rédaction)." });
export default [
// ---------- 17 notions ----------
C('not-art', N, "L'art : quelles questions poser ?",
  "Art et technique (tekhnè) ; imitation, expression, création ; jugement de goût subjectif ou universel ? Pistes : Aristote (Poétique), Kant (jugement de goût), Hegel (art et esprit absolu).",
  { n: ["l'art"], a: ['Kant', 'Hegel', 'Aristote'], s: [PROG, es('Kant, Critique de la faculté de juger, §§1-22, 43-46'), es('Aristote, Poétique, 9')] }),
C('not-bonheur', N, "Le bonheur : but de l'existence ou illusion ?",
  "Eudaimonia (vie accomplie, Aristote), ataraxie (Épicure), idéal de l'imagination et non de la raison (Kant). Enjeu : le bonheur peut-il être visé directement ? Est-il compatible avec la morale ?",
  { n: ['le bonheur'], a: ['Aristote', 'Épicure', 'Kant'], s: [PROG, es('Aristote, Éthique à Nicomaque, I ; Kant, Fondements de la métaphysique des mœurs, II, AK IV, 418')] }),
C('not-conscience', N, "La conscience : psychologique et morale, quelles distinctions ?",
  "Conscience de soi et du monde (cogito, intentionnalité de Husserl) ; conscience morale (jugement sur nos actes, Rousseau). Limites : l'inconscient (Freud), la mauvaise foi (Sartre).",
  { n: ['la conscience'], a: ['Descartes', 'Husserl', 'Rousseau'], s: [PROG, pd('Descartes, Méditations, II'), es('Husserl, Idées directrices pour une phénoménologie (1913), §84')] }),
C('not-devoir', N, "Le devoir : obligation morale ou contrainte sociale ?",
  "Kant : devoir = nécessité d'agir par respect de la loi morale, autonome. Autres pistes : Aristote (vertu), utilitarisme (Bentham, Mill), Durkheim (contrainte sociale).",
  { n: ['le devoir'], a: ['Kant', 'Mill'], s: [PROG, pd('Kant, Fondements de la métaphysique des mœurs, I-II')] }),
C('not-etat', N, "L'État : qu'est-ce qui fonde sa légitimité ?",
  "Contrat (Hobbes : sécurité ; Locke : droits naturels ; Rousseau : volonté générale). Critiques : Marx (instrument d'une classe), Weber (monopole de la violence physique légitime).",
  { n: ["l'État"], a: ['Hobbes', 'Locke', 'Rousseau', 'Weber'], s: [PROG, pd('Hobbes, Léviathan, XVII ; Locke, Second traité du gouvernement civil'), es('Weber, Le savant et le politique (1919)')] }),
C('not-inconscient', N, "L'inconscient : comment penser ce qui échappe à la conscience ?",
  "Leibniz (petites perceptions), Freud (refoulement, topiques). Objections : Alain, Sartre (la conscience est transparente à elle-même ; mauvaise foi plutôt qu'inconscient).",
  { n: ["l'inconscient"], a: ['Leibniz', 'Freud', 'Sartre', 'Alain'], s: [PROG, pd('Leibniz, Nouveaux essais sur l’entendement humain, préface'), pd("Freud, Métapsychologie, « L'inconscient » (1915)")] }),
C('not-justice', N, "La justice : légalité, égalité, équité ?",
  "Aristote : justice distributive (proportionnelle) et corrective (arithmétique) ; équité comme correction de la loi. Rawls : voile d'ignorance et principes de justice comme équité.",
  { n: ['la justice'], a: ['Aristote', 'Rawls'], s: [PROG, es('Aristote, Éthique à Nicomaque, V, 1-10 ; 14 (1137b)'), es('Rawls, Théorie de la justice (1971), §§3, 24')] }),
C('not-langage', N, "Le langage : simple outil de communication ?",
  "Aristote : le logos fait l'homme politique. Descartes : le langage prouve la différence homme-machine et homme-animal (Discours, V). Wittgenstein : la signification est un usage.",
  { n: ['le langage'], a: ['Aristote', 'Descartes', 'Wittgenstein'], s: [PROG, es('Aristote, Politiques, I, 2'), pd('Descartes, Discours de la méthode, V (AT VI, 56-57)'), es('Wittgenstein, Recherches philosophiques, §43')] }),
C('not-liberte', N, "La liberté : indépendance, autonomie, libre arbitre ?",
  "Libre arbitre (Descartes) contre nécessité (Spinoza) ; autonomie (Kant) ; liberté située et responsable (Sartre) ; liberté politique (Rousseau, Arendt). Problème : quelle liberté est compatible avec des déterminismes ?",
  { n: ['la liberté'], a: ['Descartes', 'Spinoza', 'Kant', 'Sartre'], s: [PROG, pd('Descartes, Méditations, IV ; Spinoza, Éthique, I, déf. 7')] }),
C('not-nature', N, "La nature : essence, ensemble des êtres ou opposée à la culture ?",
  "Physis : principe interne du mouvement (Aristote, Physique II, 1). Nature et culture : Rousseau (état de nature), Lévi-Strauss (la prohibition de l'inceste, seuil entre nature et culture).",
  { n: ['la nature'], a: ['Aristote', 'Rousseau', 'Lévi-Strauss'], s: [PROG, es('Aristote, Physique, II, 1 (192b8-23)'), es('Lévi-Strauss, Les Structures élémentaires de la parenté (1949), chap. I-II')] }),
C('not-raison', N, "La raison : faculté de connaître, de juger, de bien agir ?",
  "Raison théorique et pratique (Kant) ; principe de raison suffisante (Leibniz, Monadologie §32) ; la raison est-elle « esclave des passions » (Hume, Traité II, 3, 3) ?",
  { n: ['la raison'], a: ['Kant', 'Leibniz', 'Hume'], s: [PROG, pd('Leibniz, Monadologie, §32'), pd('Hume, Traité de la nature humaine, II, 3, 3')] }),
C('not-religion', N, "La religion : croyance, pratique, institution ?",
  "Lucrèce : source de maux. Spinoza : critique de la superstition (TTP). Kant : religion dans les limites de la simple raison. Marx : « opium du peuple ». Durkheim : sacré et profane.",
  { n: ['la religion'], a: ['Lucrèce', 'Spinoza', 'Kant', 'Marx', 'Durkheim'], s: [PROG, pd('Lucrèce, De rerum natura, I, 62-101 ; Marx, Contribution à la critique de la philosophie du droit de Hegel, introduction'), es('Durkheim, Les Formes élémentaires de la vie religieuse (1912)')] }),
C('not-science', N, "La science : qu'est-ce qui la distingue de l'opinion ou de la croyance ?",
  "Comte (positivisme, trois états) ; Bachelard (obstacle épistémologique, rupture avec le sens commun) ; Popper (réfutabilité comme critère).",
  { n: ['la science'], a: ['Comte', 'Bachelard', 'Popper'], s: [PROG, es("Bachelard, La Formation de l'esprit scientifique (1938)"), es('Popper, La Logique de la découverte scientifique (1934 ; 1959 pour la trad. anglaise)')] }),
C('not-technique', N, "La technique : moyen neutre ou milieu qui transforme l'homme ?",
  "Protagoras (Prométhée), Simondon (l'objet technique comme réalité humaine), Jonas (responsabilité face aux pouvoirs de la technique), Arendt (labeur, travail, action).",
  { n: ['la technique'], a: ['Platon', 'Simondon', 'Jonas'], s: [PROG, es('Platon, Protagoras, 320c-322d'), es('Jonas, Le Principe responsabilité (1979)')] }),
C('not-temps', N, "Le temps : réalité, mesure ou forme de la conscience ?",
  "Aristote (nombre du mouvement) ; Augustin (« Qu'est-ce donc que le temps ? », Confessions XI, 14) ; Kant (forme a priori de la sensibilité) ; Bergson (durée).",
  { n: ['le temps'], a: ['Aristote', 'Augustin', 'Kant', 'Bergson'], s: [PROG, es('Aristote, Physique, IV, 10-14'), pd('Augustin, Confessions, XI, 14-28')] }),
C('not-travail', N, "Le travail : peine, aliénation ou réalisation de soi ?",
  "Hegel : le travail forme l'homme. Marx : travail aliéné. Arendt : distinction labeur/travail. Weil : travail non servile, attention et pensée (Réflexions sur les causes de la liberté).",
  { n: ['le travail'], a: ['Hegel', 'Marx', 'Arendt', 'Weil'], s: [PROG, pd("Hegel, Phénoménologie de l'esprit, IV, A"), es("Arendt, Condition de l'homme moderne"), es("Weil, Réflexions sur les causes de la liberté et de l'oppression sociale (1934)")] }),
C('not-verite', N, "La vérité : correspondance, cohérence, évidence ?",
  "Aristote : dire de ce qui est qu'il est (Métaphysique Γ, 7, 1011b26). Descartes : évidence. Nietzsche : la vérité comme illusion utile. Arendt : vérité de fait et politique.",
  { n: ['la vérité'], a: ['Aristote', 'Descartes', 'Nietzsche', 'Arendt'], s: [PROG, es('Aristote, Métaphysique, Γ, 7 (1011b26-27)'), pd('Nietzsche, Über Wahrheit und Lüge im aussermoralischen Sinne')] }),

// ---------- Repères ----------
rep('rep-fait-droit', "Repère : en fait / en droit", "En fait : ce qui est constaté. En droit : ce qui est légitime ou doit être, selon une norme. Ex. : l'esclavage a existé en fait ; on peut contester qu'il soit fondé en droit (Rousseau, CS I, 4)."),
rep('rep-legal-legitime', "Repère : légal / légitime", "Légal : conforme à la loi positive. Légitime : conforme à un principe de justice ou de raison. Une loi peut être légale sans être légitime."),
rep('rep-obligation-contrainte', "Repère : obligation / contrainte", "La contrainte s'exerce par la force sur les corps ; l'obligation lie la volonté par un devoir reconnu. Rousseau : la force ne fait pas droit (CS I, 3)."),
rep('rep-croire-savoir', "Repère : croire / savoir", "Croire : adhérer sans preuve suffisante ; savoir : posséder des raisons objectives et communicables. Platon distingue doxa et épistèmè (République V-VI)."),
rep('rep-persuader-convaincre', "Repère : persuader / convaincre", "Persuader : agir sur les affects et l'adhésion, parfois par la rhétorique. Convaincre : obtenir l'assentiment par des raisons. Cf. Platon, Gorgias."),
rep('rep-expliquer-comprendre', "Repère : expliquer / comprendre", "Expliquer : relier un fait à ses causes (sciences de la nature). Comprendre : saisir un sens du point de vue de l'agent (sciences humaines, Weber)."),
rep('rep-acte-puissance', "Repère : en acte / en puissance", "En puissance : ce qui peut être ; en acte : ce qui est réalisé. Aristote, Métaphysique, Θ."),
rep('rep-contingent-necessaire', "Repère : contingent / nécessaire / possible", "Nécessaire : ne peut pas ne pas être ; contingent : peut être ou ne pas être ; possible : ce qui n'est pas contradictoire. Leibniz distingue vérités de raison et de fait."),
rep('rep-origine-fondement', "Repère : origine / fondement", "L'origine désigne un commencement dans le temps ; le fondement, une justification logique ou de droit. Ne pas confondre genèse et valeur (Nietzsche, Généalogie de la morale)."),
rep('rep-universel', "Repère : universel / général / particulier / singulier", "Universel : vaut pour tous sans exception, en droit. Général : vaut le plus souvent, par induction. Particulier : une partie d'une classe ; singulier : un individu unique."),
rep('rep-transcendant-immanent', "Repère : transcendant / immanent", "Transcendant : extérieur et supérieur à ce qu'il fonde. Immanent : intérieur à son objet. Ex. : Dieu transcendant (Descartes) ou immanent (Spinoza, Deus sive Natura)."),
rep('rep-analogie', "Repère : ressemblance / analogie", "Ressemblance : partage de propriétés communes ; analogie : identité de rapports entre des termes différents (A est à B ce que C est à D)."),
rep('rep-cause-fin', "Repère : cause / fin", "Cause : ce qui produit un effet, en amont. Fin : ce en vue de quoi on agit, en aval. Aristote : causalité efficiente et finale (Physique II, 3)."),
rep('rep-exemple-preuve', "Repère : exemple / preuve", "Un exemple illustre ; il ne prouve pas, sauf en mathématiques (contre-exemple ou exemple existentiel). En dissertation : l'exemple doit être analysé."),
rep('rep-intuitif-discursif', "Repère : intuitif / discursif", "Intuitif : connaissance immédiate ; discursif : par raisonnement, étape par étape (Descartes, Règles pour la direction de l'esprit III)."),

// ---------- HLP (à vérifier dans le BO HLP) ----------
C('hlp-themes-premiere', 'hlp', "HLP, classe de première : quels sont les deux thèmes du programme ?",
  "Semestre 1 : « Les pouvoirs de la parole ». Semestre 2 : « Les représentations du monde ».",
  { s: [of('Programme de l’enseignement de spécialité Humanités, littérature et philosophie, classe de première, BO spécial du 22 janvier 2019')], note: "Intitulés à contrôler dans le BO." }),
C('hlp-themes-terminale', 'hlp', "HLP, classe terminale : quels sont les deux thèmes du programme ?",
  "Semestre 1 : « La recherche de soi ». Semestre 2 : « L'humanité en question ».",
  { s: [of('Programme HLP, classe terminale, BO spécial n° 8 du 25 juillet 2019')], note: "Intitulés à contrôler dans le BO." }),
C('hlp-pouvoirs', 'hlp', "HLP « Les pouvoirs de la parole » : quels axes d'étude ?",
  "L'art de la parole (rhétorique) ; l'autorité de la parole ; la parole en action (engagement, résistance).",
  { s: [of('Programme HLP, première, BO spécial du 22 janvier 2019')], note: "Intitulés des axes à contrôler dans le BO." }),
C('hlp-representations', 'hlp', "HLP « Les représentations du monde » : quels axes d'étude ?",
  "Découverte du monde et pluralité des cultures ; décrire, figurer, imaginer ; l'homme et l'animal.",
  { s: [of('Programme HLP, première, BO spécial du 22 janvier 2019')], note: "Intitulés des axes à contrôler dans le BO." }),
C('hlp-recherche-soi', 'hlp', "HLP « La recherche de soi » : quels axes d'étude ?",
  "Les expressions de la sensibilité ; les métamorphoses du moi ; éducation, transmission et émancipation.",
  { s: [of('Programme HLP, terminale, BO spécial n° 8 du 25 juillet 2019')], note: "Intitulés des axes à contrôler dans le BO." }),
C('hlp-humanite', 'hlp', "HLP « L'humanité en question » : quels axes d'étude ?",
  "Création, continuités et ruptures ; histoire et violence ; l'humain et ses limites.",
  { s: [of('Programme HLP, terminale, BO spécial n° 8 du 25 juillet 2019')], note: "Intitulés des axes à contrôler dans le BO." }),
];
