import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Condillac (p. 91), Smith (p. 465-466), Bentham (p. 52) ----------
D('d-cond-sensualisme', T, "Quel est le rôle du langage chez Condillac ?",
  "Fondamental : les signes, institution humaine arbitraire, assurent le passage des idées issues de la sensation aux idées abstraites. Nominaliste, il affirme que les idées abstraites et générales ne sont que des dénominations ; la science est « une langue bien faite ».",
  { a: ['Condillac', 'Locke'], n: ['le langage', 'la science'], o: 'Logique', art: 'Condillac', p: '91' }),
D('d-smit-sympathie', T, "Sur quoi repose la vie en société selon la Théorie des sentiments moraux ?",
  "Sur la sympathie : Smith critique le pessimisme (égoïsme comme ressort, Hobbes, Mandeville). La vertu procède d'une réaction spontanée aux misères et succès d'autrui ; chacun cherche l'approbation d'autrui pour pouvoir s'aimer soi-même.",
  { a: ['Smith', 'Hobbes'], n: ['le devoir', 'le bonheur'], o: 'Théorie des sentiments moraux', art: 'Smith', p: '465' }),
D('d-smit-main-invisible', T, "Qu'est-ce que la « main invisible » dans La Richesse des nations ?",
  "Les hommes, mus par l'amour de soi, contribuent sans le savoir ni le vouloir à la prospérité générale : la concurrence des intérêts établit un ordre harmonieux (division du travail, accumulation du capital, expansion des marchés).",
  { a: ['Smith'], n: ['le travail', 'la justice'], o: 'La Richesse des nations', art: 'Smith', p: '465-466' }),
D('d-smit-coherence', T, "Les deux ouvrages de Smith sont-ils contradictoires ?",
  "Non : moraliste avant d'être économiste, Smith montre que le sujet a besoin d'autrui pour acquérir une valeur à ses propres yeux. Il défend la liberté du commerce et s'oppose au protectionnisme et aux monopoles.",
  { a: ['Smith'], n: ['le travail', 'le bonheur'], o: 'La Richesse des nations', art: 'Smith', p: '465-466' }),
D('d-bent-utilitarisme', T, "Qu'est-ce que l'utilitarisme de Bentham ?",
  "Le principe d'utilité juge toute action selon l'augmentation ou la diminution du plaisir qu'elle procure : morale hédoniste, arithmétique des plaisirs et des peines visant le maximum de bonheur pour l'humanité.",
  { a: ['Bentham'], n: ['le bonheur', 'le devoir', 'la justice'], o: 'Introduction aux principes de la morale et de la législation', art: 'Bentham', p: '52' }),
D('d-bent-animaux', T, "Que dit Bentham à propos des animaux ?",
  "La question n'est pas de savoir s'ils pensent ou parlent, mais s'ils souffrent. Il est devenu une référence de la cause animale.",
  { a: ['Bentham'], n: ['la nature', 'le devoir'], art: 'Bentham', p: '52' }),

// ---------- Schopenhauer (p. 450-451) ----------
D('d-scho-representation', T, "Que signifie « le monde est ma représentation » ?",
  "Reprenant phénomène/chose en soi de Kant, le monde perçu est apparence (maya). Derrière lui, accessible par l'intuition, le monde en soi est sans causalité ni raison : une volonté aveugle, un « vouloir-vivre ».",
  { a: ['Schopenhauer', 'Kant'], n: ['la vérité', 'la nature'], o: 'Le Monde comme volonté et comme représentation', art: 'Schopenhauer', p: '450-451' }),
D('d-scho-desir', T, "Pourquoi le désir est-il tragique et douloureux selon Schopenhauer ?",
  "Il est l'expression consciente du vouloir-vivre : l'homme croit servir ses intérêts alors qu'il sert l'espèce (sexualité) ; et il est manque, donc insatiable.",
  { a: ['Schopenhauer'], n: ['le bonheur'], o: 'Le Monde comme volonté et comme représentation', art: 'Schopenhauer', p: '451' }),
D('d-scho-salut', T, "Quelles voies de salut Schopenhauer indique-t-il ?",
  "L'art (contemplation désintéressée, « suspension du vouloir-vivre »), la pitié (compassion qui fait renoncer à l'égoïsme), enfin philosophie et ascétisme menant à la négation du vouloir-vivre (nirvâna). Nietzsche combattra ce nihilisme mystique.",
  { a: ['Schopenhauer', 'Nietzsche'], n: ["l'art", 'le bonheur', 'le devoir'], art: 'Schopenhauer', p: '451' }),

// ---------- Comte (p. 89-90), Cournot (p. 106-107), Feuerbach (p. 184) ----------
D('d-comt-trois-etats', T, "Quelle est la loi des trois états de Comte ?",
  "L'esprit humain est théologien en sa jeunesse, métaphysicien en son adolescence, positif en sa maturité. L'état positif renonce aux causes premières ou finales pour établir, par observation et expérience, les relations constantes entre les phénomènes.",
  { a: ['Comte'], n: ['la science', 'le temps', 'la vérité'], o: 'Cours de philosophie positive', art: 'Comte', p: '89' }),
D('d-comt-classification', T, "Comment Comte classe-t-il les sciences ?",
  "Six sciences fondamentales (mathématiques, astronomie, physique, chimie, biologie, sociologie) par complexité croissante. Chaque ordre est irréductible au précédent ; la sociologie, dernière-née, est première en dignité.",
  { a: ['Comte'], n: ['la science'], o: 'Cours de philosophie positive', art: 'Comte', p: '89' }),
D('d-comt-philosophie-positive', T, "Quelle est la mission de la philosophie positive et de la sociologie ?",
  "La sociologie (« physique sociale ») fait de l'humanité un objet de science. La philosophie n'a pas d'objet propre : elle unifie le savoir (synthèse objective et subjective) ; le philosophe est le « spécialiste des généralités ».",
  { a: ['Comte'], n: ['la science', "l'État"], art: 'Comte', p: '89' }),
D('d-cour-hasard', T, "Comment Cournot définit-il le hasard ?",
  "Un « concours de causes indépendantes » : les événements fortuits sont sans raison (nécessité) mais non sans cause, et non dus à notre ignorance. Le hasard peut être traité scientifiquement, contre l'intelligence laplacienne.",
  { a: ['Cournot'], n: ['la science', 'la raison'], art: 'Cournot', p: '106-107' }),
D('d-cour-rationalisme', T, "Quelle est l'idée de Cournot sur les rapports science-philosophie ?",
  "Elles doivent s'allier sans se confondre (contre le scientisme) : sans la science, la philosophie s'égare ; sans la philosophie, la science s'épuise en rigueur stérile. La raison doit devenir régulatrice et critique. (Cournot fut recteur de l'académie de Dijon de 1854 à 1862.)",
  { a: ['Cournot'], n: ['la science', 'la raison'], art: 'Cournot', p: '106-107' }),
D('d-feue-humanisme', T, "Que défend l'« humanisme athée » de Feuerbach ?",
  "L'homme sensible est l'origine et la fin de toute réalité : contre Hegel, l'essence de l'homme est le sentiment (l'amour), non l'esprit. La vraie philosophie est sensualiste et matérialiste.",
  { a: ['Feuerbach', 'Hegel'], n: ['la nature', 'la raison'], o: 'L’Essence du christianisme', art: 'Feuerbach', p: '184' }),
D('d-feue-religion', T, "Comment Feuerbach explique-t-il la religion ?",
  "Son essence est l'aliénation : l'homme transfère à une réalité transcendante (Dieu) des qualités qui n'appartiennent qu'au genre humain (la bonté). La philosophie rend à l'humanité ses prédicats.",
  { a: ['Feuerbach'], n: ['la religion'], o: 'L’Essence du christianisme', art: 'Feuerbach', p: '184' }),
];
