import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Tocqueville (p. 497), Mill (p. 330), Kierkegaard (p. 277-278) ----------
D('d-tocq-democratie', T, "Comment Tocqueville définit-il la démocratie ?",
  "Comme un système social (égalité comme valeur essentielle, participation de tous, mobilité sociale) doublé d'une mentalité individualiste : croyance en l'égalité intellectuelle et passion de la sécurité et du bien-être, au revers égoïste.",
  { a: ['Tocqueville'], n: ["l'État", 'la justice', 'la liberté'], o: 'De la démocratie en Amérique', art: 'Tocqueville', p: '497' }),
D('d-tocq-despotisme', T, "Quels périls menacent la démocratie selon Tocqueville ?",
  "La « tyrannie de la majorité » (l'avis majoritaire devient norme intériorisée, d'où conformisme) et un État tutélaire, nouveau despotisme « doux » et « bienveillant », issu de l'atomisation de la société.",
  { a: ['Tocqueville'], n: ["l'État", 'la liberté'], o: 'De la démocratie en Amérique', art: 'Tocqueville', p: '497' }),
D('d-tocq-contrepoids', T, "Quels contrepoids Tocqueville espère-t-il ?",
  "La démocratie politique (institutions représentatives, séparation des pouvoirs, pluralisme), surtout la liberté d'association et les pouvoirs intermédiaires, qui donnent une éducation civique, et la presse libre.",
  { a: ['Tocqueville'], n: ["l'État", 'la liberté'], o: 'De la démocratie en Amérique', art: 'Tocqueville', p: '497' }),
D('d-mill-utilitarisme', T, "En quoi l'utilitarisme de Mill diffère-t-il de celui de Bentham ?",
  "1. Qualité des plaisirs (les plaisirs de l'esprit valent mieux que les charnels), non seulement quantité. 2. Tant que bonheur privé et bien public divergent, le sacrifice de l'individu est la plus haute vertu : utilitarisme altruiste.",
  { a: ['Mill', 'Bentham'], n: ['le bonheur', 'le devoir', 'la justice'], o: "L'Utilitarisme", art: 'Mill', p: '330' }),
D('d-mill-liberalisme', T, "Quelles œuvres de Mill marquent le libéralisme et le féminisme ?",
  "De la liberté (1859), Le Gouvernement représentatif (1861), De l'assujettissement des femmes (1869) : socialiste libéral, il s'engage pour les droits des femmes, notamment le droit de vote.",
  { a: ['Mill'], n: ['la liberté', "l'État", 'la justice'], o: 'De la liberté', art: 'Mill', p: '330' }),
D('d-kier-existence', T, "Pourquoi Kierkegaard s'oppose-t-il à l'esprit de système hégélien ?",
  "Le système abstrait et universalisant délaisse l'existant singulier, sa situation concrète et ses responsabilités. Il regarde tout sous l'espèce de l'éternité et rend l'existence du penseur extérieure à sa pensée.",
  { a: ['Kierkegaard', 'Hegel'], n: ['la conscience', 'le temps', 'la vérité'], art: 'Kierkegaard', p: '277' }),
D('d-kier-angoisse-desespoir', T, "Angoisse et désespoir chez Kierkegaard : qu'est-ce que c'est ?",
  "L'angoisse : l'état d'un être condamné à choisir sans savoir que choisir, faute de réponses humaines. Le désespoir : impossibilité d'être soi et de ne pas l'être, née de la distance entre soi et soi. Ils sont appel de l'absolu.",
  { a: ['Kierkegaard'], n: ['la conscience', 'le bonheur'], o: 'Le Concept d’angoisse', art: 'Kierkegaard', p: '277' }),
D('d-kier-stades', T, "Quels sont les stades de l'existence chez Kierkegaard ?",
  "Esthétique (jouissance dans l'instant, Don Juan), éthique (choix durable dans le temps, mariage), religieux (relation à l'éternité, saut dans la foi). L'ironie et l'humour sont des stades intermédiaires.",
  { a: ['Kierkegaard'], n: ['le temps', 'le devoir', 'la religion'], o: 'Étapes sur le chemin de la vie', art: 'Kierkegaard', p: '277-278' }),
D('d-kier-foi', T, "Que signifie la « suspension téléologique de l'éthique dans la foi » ?",
  "Le stade religieux exige un saut : comme Abraham, qui garde ses rôles mais les soumet aux décrets divins. Il est un rapport singulier au divin, injustifiable au regard de l'éthique, qui permet pourtant de vivre l'éthique pleinement.",
  { a: ['Kierkegaard'], n: ['la religion', 'le devoir'], o: 'Crainte et Tremblement', art: 'Kierkegaard', p: '278' }),

// ---------- Marx (p. 316-317), Engels (p. 155), James (p. 263), Durkheim (p. 141-142) ----------
D('d-marx-origines', T, "Aux trois traditions dont Marx est issu, laquelle s'ajoute à quelle nationalité ?",
  "Socialisme français, économie anglaise (Smith, Ricardo), philosophie allemande (Feuerbach, Hegel).",
  { a: ['Marx'], n: ['le travail'], art: 'Marx', p: '316' }),
D('d-marx-lutte-classes', T, "Que dit le Manifeste du parti communiste ?",
  "Écrit avec Engels : nécessité historique de la révolution communiste à partir de la lutte des classes, antagonisme moderne bourgeoisie/prolétariat, dont la victoire abolira la propriété privée bourgeoise et l'exploitation du travail.",
  { a: ['Marx', 'Engels'], n: ["l'État", 'le travail', 'la justice'], o: 'Manifeste du parti communiste', art: 'Marx', p: '316' }),
D('d-marx-plus-value', T, "Comment Le Capital explique-t-il l'exploitation ?",
  "Pour que le capitaliste réalise son profit, une partie de la force de travail dépensée par l'ouvrier n'est pas rémunérée : c'est le surtravail (plus-value). Il y a exploitation parce qu'il y a extorsion de surtravail.",
  { a: ['Marx'], n: ['le travail', 'la justice'], o: 'Le Capital', art: 'Marx', p: '316' }),
D('d-marx-materialisme', T, "Qu'est-ce que le matérialisme historique ?",
  "Les forces motrices de l'histoire résident dans l'organisation matérielle des sociétés (modes de production), non dans les idées, qui relèvent de l'idéologie : « ce n'est pas la conscience qui détermine l'existence, mais l'existence sociale qui détermine la conscience ».",
  { a: ['Marx'], n: ['le temps', 'la conscience', 'la vérité'], o: "L'Idéologie allemande", art: 'Marx', p: '316' }),
D('d-marx-dialectique', T, "Marx est-il déterministe ? Et en quoi sa dialectique diffère-t-elle de celle de Hegel ?",
  "Les écrits politiques sont volontaristes, d'autres textes déterministes (succession esclavagisme, féodalisme, bourgeoisie, communisme). Hegel situe la dialectique dans les idées ; Marx dans les contradictions entre forces productives et rapports sociaux.",
  { a: ['Marx', 'Hegel'], n: ['le temps', 'la liberté'], art: 'Marx', p: '316' }),
D('d-marx-jeune-mur', T, "Y a-t-il une rupture entre le jeune Marx et le Marx du Capital ?",
  "Avant 1846 : philosophie de l'« homme total » et critique de l'aliénation (religion, État). Ensuite : analyse économique de l'exploitation. La rupture ne doit pas être exagérée, car l'aliénation dépend de conditions sociales que Le Capital analyse.",
  { a: ['Marx'], n: ['le travail', 'la religion'], art: 'Marx', p: '317' }),
D('d-enge-dialectique-nature', T, "Quelle contribution propre Engels apporte-t-il au marxisme ?",
  "Il confronte le marxisme aux sciences sociales, historiques et naturelles (Dialectique de la nature, Anti-Dühring) : le matérialisme dialectique comme synthèse du savoir, ce qui a servi la vulgate stalinienne.",
  { a: ['Engels'], n: ['la science', 'la nature'], o: 'Dialectique de la nature', art: 'Engels', p: '155' }),
D('d-jame-pragmatisme', T, "Que soutient James sur la vérité ?",
  "Pragmatisme : la vérité est indissociable de l'expérience, relative aux procédures de vérification, à la communauté, au contexte ; un événement plutôt qu'une propriété inhérente. Formule : le vrai est ce qui est avantageux pour la pensée.",
  { a: ['James'], n: ['la vérité'], o: 'Le Pragmatisme', art: 'James', p: '263' }),
D('d-durk-fait-social', T, "Qu'est-ce qu'un fait social et comment l'étudier selon Durkheim ?",
  "Ce qui « exerce une contrainte sur l'individu » ; il faut le traiter comme une chose, c'est-à-dire l'observer de l'extérieur, sans illusion de compréhension immédiate, avec une méthode proche des sciences exactes.",
  { a: ['Durkheim'], n: ['la science', 'la nature'], o: 'Les Règles de la méthode sociologique', art: 'Durkheim', p: '141-142' }),
D('d-durk-division-travail', T, "Que soutient De la division du travail social ?",
  "Le volume et la densité de la population expliquent la différenciation sociale croissante et la prépondérance de la « solidarité organique ».",
  { a: ['Durkheim'], n: ['le travail', "l'État"], o: 'De la division du travail social', art: 'Durkheim', p: '142' }),
D('d-durk-suicide', T, "Comment Durkheim explique-t-il le suicide ?",
  "Par des « courants suicidogènes », tendances sociales au suicide qui s'incarnent dans des individus : explication strictement sociologique.",
  { a: ['Durkheim'], n: ['la science'], o: 'Le Suicide', art: 'Durkheim', p: '142' }),
D('d-durk-religion', T, "Quelle est l'essence de la religion selon Durkheim ?",
  "La division du monde entre sacré et profane ; c'est la société elle-même, réalité qui nous dépasse, qui est l'objet du culte. La religion témoigne de la transcendance de la conscience collective sur les consciences individuelles.",
  { a: ['Durkheim'], n: ['la religion'], o: 'Les Formes élémentaires de la vie religieuse', art: 'Durkheim', p: '142' }),
];
