import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Husserl (p. 233-234) ----------
D('d-huss-science-rigoureuse', T, "Quel est le projet de Husserl face à la crise du début du XXe siècle ?",
  "Instituer la philosophie comme science rigoureuse contre le psychologisme (les lois logiques réduites aux lois psychologiques), le positivisme et le relativisme, en réhabilitant le vécu et le concret sans renoncer à la rigueur.",
  { a: ['Husserl'], n: ['la science', 'la vérité', 'la raison'], art: 'Husserl', p: '234' }),
D('d-huss-choses-elles-memes', T, "Que signifie « revenir aux choses elles-mêmes » ?",
  "Décrire, avant toute explication, comment quelque chose se donne à une conscience, comme phénomène. Les phénomènes ne sont pas de simples apparences : la phénoménologie est une description des essences.",
  { a: ['Husserl'], n: ['la conscience', 'la vérité'], art: 'Husserl', p: '234' }),
D('d-huss-eidetique', T, "Que sont la variation eidétique et l'intentionnalité ?",
  "Variation eidétique : faire varier imaginairement les prises de vue pour dégager l'invariant (l'essence). Intentionnalité : corrélation entre l'acte de conscience (noèse) et l'objet visé (noème) ; l'essence n'est pas séparable de l'acte qui la vise.",
  { a: ['Husserl'], n: ['la conscience', 'la vérité'], art: 'Husserl', p: '234' }),

// ---------- Alain (p. 11-12) ----------
D('d-alai-references', T, "Que retient Alain de Platon, Descartes et Kant ?",
  "De Platon : la philosophie dépasse l'opinion, même vraie. De Descartes : le doute contre la crédulité, la volonté, la conscience comme fondement (d'où son refus de l'inconscient freudien, « fantôme mythologique »). De Kant : la critique de la connaissance et la morale du devoir.",
  { a: ['Alain', 'Platon', 'Descartes', 'Kant'], n: ['la conscience', "l'inconscient", 'le devoir'], art: 'Alain', p: '11' }),
D('d-alai-perception', T, "Pourquoi « percevoir, c'est juger » chez Alain ?",
  "Devant un dé, on ne touche que des arêtes et des faces ; c'est le jugement qui les réunit en un cube. La perception est déjà une fonction d'entendement : les apparences ne trompent pas en elles-mêmes (le bâton brisé se juge par les lois optiques).",
  { a: ['Alain'], n: ['la vérité', 'la science'], art: 'Alain', p: '11' }),
D('d-alai-imagination', T, "Comment Alain définit-il l'imagination ?",
  "Comme une perception fausse : sauf l'imagination créatrice qui produit l'œuvre d'art, elle est « une folle » (Malebranche), qui ne produit pas des images mais de l'imaginaire, et déchaîne les passions.",
  { a: ['Alain', 'Malebranche'], n: ["l'art", 'la raison'], art: 'Alain', p: '11-12' }),

// ---------- Mauss, Russell, Jaspers, Bachelard ----------
D('d-maus-fait-social-total', T, "Qu'est-ce qu'un « phénomène social total » (Mauss) ?",
  "Un fait qu'on ne peut isoler de ses aspects biologique, psychologique, social : dans l'Essai sur le don (potlatch), l'échange économique est indissociable de ses dimensions juridique (donner, recevoir, rendre), politique et religieuse.",
  { a: ['Mauss'], n: ['le travail', 'la religion', 'la justice'], o: 'Essai sur le don', art: 'Mauss', p: '320-321' }),
D('d-russ-logicisme', T, "Quel est le projet logiciste de Russell ?",
  "Avec Whitehead, réduire les mathématiques (surtout l'arithmétique) à des principes logiques fondamentaux, les énoncés mathématiques étant de pures tautologies.",
  { a: ['Russell'], n: ['la science', 'la raison'], art: 'Russell', p: '438' }),
D('d-russ-atomisme', T, "Qu'est-ce que l'atomisme logique ?",
  "Contre l'idéalisme totalisant, les faits sont indépendants les uns des autres ; tout complexe est composé de choses simples, chaque fait étant représenté par une proposition atomique, les propositions complexes n'en étant que des combinaisons.",
  { a: ['Russell'], n: ['le langage', 'la vérité'], art: 'Russell', p: '438' }),
D('d-russ-verite', T, "Comment Russell définit-il la vérité ?",
  "Comme correspondance entre une croyance et un fait qui la vérifie, contre la cohérence de l'idéalisme. Problème de l'inférence non déductive (Hume) : il faut hiérarchiser les croyances selon leur degré de certitude.",
  { a: ['Russell', 'Hume'], n: ['la vérité', 'la science'], art: 'Russell', p: '438' }),
D('d-jasp-existence', T, "Que sont l'existence et les situations-limites chez Jaspers ?",
  "L'existence est « une qualité possible » que la vie peut acquérir : elle ne se décrit pas, mais s'éclaire. La liberté existentielle reste bornée par les situations-limites (naissance, mort, souffrance).",
  { a: ['Jaspers'], n: ['la liberté', 'la conscience'], art: 'Jaspers', p: '265' }),
D('d-jasp-verite-communication', T, "Quel lien Jaspers établit-il entre vérité et communication ?",
  "La vérité absolue est inaccessible ; ses modes (« englobant ») sont pluriels. Son principe est la communication illimitée : la raison instaure le dialogue de toutes les pensées et traditions.",
  { a: ['Jaspers'], n: ['la vérité', 'la raison', 'le langage'], art: 'Jaspers', p: '265-266' }),
D('d-jasp-paix', T, "Quelles conditions de la paix Jaspers énonce-t-il après 1945 ?",
  "Une conversion éthique (pas de paix extérieure sans paix intérieure) et un droit international : respect des traités, renoncement à la souveraineté absolue des États, protection des droits de l'homme par une autorité supranationale.",
  { a: ['Jaspers'], n: ["l'État", 'la justice'], art: 'Jaspers', p: '266' }),
D('d-bach-rupture', T, "Quelle idée du progrès scientifique Bachelard défend-il ?",
  "Les acquis se font par ruptures, de façon discontinue (crises de la relativité, du déterminisme, des ensembles) : la raison, ouverte à l'avenir, remet en question ses principes (Le Nouvel Esprit scientifique).",
  { a: ['Bachelard'], n: ['la science', 'la raison', 'le temps'], o: 'Le Nouvel Esprit scientifique', art: 'Bachelard', p: '45' }),
D('d-bach-obstacles', T, "Que sont les obstacles épistémologiques ?",
  "Des obstacles intérieurs à la pensée, dans les profondeurs inconscientes et culturelles du psychisme (La Formation de l'esprit scientifique). Il faut désapprendre le mécanisme, la science-spectacle, la réduction au simple.",
  { a: ['Bachelard'], n: ['la science', "l'inconscient"], o: "La Formation de l'esprit scientifique", art: 'Bachelard', p: '45-46' }),
D('d-bach-imagination', T, "Quelle est la double face de l'œuvre de Bachelard ?",
  "Science (philosophie du non, surrationalisme) et poésie : il réhabilite l'imagination créatrice, « toute en avenir », par la psychanalyse des images. Les deux sont unies par le refus du dogmatisme. (Il a enseigné à l'université de Dijon de 1930 à 1940.)",
  { a: ['Bachelard'], n: ["l'art", 'la science', 'la raison'], o: 'La Psychanalyse du feu', art: 'Bachelard', p: '45-46' }),
];
