import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Weber (p. 530), Aron (p. 32-33) ----------
D('d-webe-neutralite', T, "Qu'est-ce que la neutralité axiologique chez Weber ?",
  "Le savant doit mettre entre parenthèses ses valeurs le temps d'examiner les faits, pour rester objectif ; le politique, lui, défend des valeurs. La science porte sur ce qui est : elle ne dit pas à quelles valeurs se vouer.",
  { a: ['Weber'], n: ['la science', 'la vérité', "l'État"], o: 'Le Savant et le Politique', art: 'Weber', p: '530' }),
D('d-webe-ethique-protestante', T, "Quelle thèse défend L'Éthique protestante et l'esprit du capitalisme ?",
  "Le protestantisme, en sanctifiant le travail régulier, a favorisé le capitalisme. La valeur travail viendrait de la sécularisation de l'ascèse chrétienne par le travail, développement qui a fini par vider le travail de son sens religieux.",
  { a: ['Weber'], n: ['le travail', 'la religion'], o: "L'Éthique protestante et l'esprit du capitalisme", art: 'Weber', p: '530' }),
D('d-webe-domination', T, "Quels sont les trois principes de légitimité de la domination selon Weber ?",
  "La tradition (on obéit car il en a toujours été ainsi), le charisme (foi en la valeur exceptionnelle de celui qui commande) et la légalité (foi en la conformité juridique des ordres, domaine de la bureaucratie moderne).",
  { a: ['Weber'], n: ["l'État", 'la justice'], o: 'Économie et Société', art: 'Weber', p: '530' }),
D('d-webe-desenchantement', T, "Que désigne le désenchantement du monde chez Weber ?",
  "La rationalisation dont les religions sont un vecteur, de la magie vers l'éthique, s'achevant à l'époque moderne.",
  { a: ['Weber'], n: ['la religion', 'la raison', 'le temps'], art: 'Weber', p: '530' }),
D('d-aron-types-ideaux', T, "Comment Aron oppose-t-il démocratie et totalitarisme ?",
  "Deux « types idéaux » : régime constitutionnel pluraliste contre régime de parti monopolistique excluant toute liberté, formelle et réelle. Les libertés sont réalisées, même imparfaitement, dans les sociétés pluralistes, garantes du droit à la vérité.",
  { a: ['Aron', 'Arendt'], n: ["l'État", 'la liberté', 'la vérité'], o: 'Essai sur les libertés', art: 'Aron', p: '32-33' }),
D('d-aron-histoire', T, "Quelle conception de l'histoire défend Aron ?",
  "Post-idéologique : l'histoire ne peut prétendre à l'objectivité univoque des autres sciences. Il s'oppose au déterminisme marxiste comme au relativisme historique ; la fin de l'histoire (Kant) est un principe régulateur.",
  { a: ['Aron', 'Kant'], n: ['le temps', 'la vérité'], o: "Introduction à la philosophie de l'histoire", art: 'Aron', p: '32' }),

// ---------- Levinas (p. 292), Beauvoir (p. 50), Lévi-Strauss (p. 293) ----------
D('d-levi-ethique', T, "Pourquoi l'éthique est-elle « philosophie première » pour Levinas ?",
  "Seule la relation à autrui est une véritable « ouverture vers l'infini » ; la métaphysique et la religion n'ont de sens qu'à partir d'elle. La rencontre du visage d'autrui est l'expérience par excellence de la transcendance.",
  { a: ['Levinas'], n: ['le devoir', 'la religion'], o: 'Totalité et Infini', art: 'Levinas', p: '292' }),
D('d-levi-humanisme', T, "En quoi consiste le « nouvel humanisme » de Levinas ?",
  "Il ne repose plus sur une essence invariable de l'homme ni sur la raison abstraite, mais sur le dévouement, l'ouverture et la responsabilité : l'humain apparaît lorsqu'un sujet répond d'autrui avant de se soucier de lui-même, dans une relation désintéressée et dissymétrique.",
  { a: ['Levinas'], n: ['le devoir', 'la conscience'], o: "Humanisme de l'autre homme", art: 'Levinas', p: '292' }),
D('d-beau-condition', T, "Que signifie « on ne naît pas femme : on le devient » ?",
  "Aucun destin biologique, psychique ou économique ne définit la femme : c'est la civilisation qui élabore le « féminin ». L'histoire s'écrit au masculin, la femme étant l'Autre. Le but : que les sexes deviennent des semblables, à égalité.",
  { a: ['Beauvoir'], n: ['la nature', 'la liberté', 'la justice'], o: 'Le Deuxième Sexe', art: 'Beauvoir', p: '50' }),
D('d-beau-ambiguite', T, "Quelle morale Beauvoir tire-t-elle de l'existentialisme ?",
  "Une morale de l'ambiguïté, non de l'absurde ni du « tout est permis » : l'homme authentique assume sa liberté en voulant que les autres soient libres, ce qui rejoint la politique dans la lutte contre l'oppression.",
  { a: ['Beauvoir', 'Sartre'], n: ['la liberté', 'le devoir'], o: "Pour une morale de l'ambiguïté", art: 'Beauvoir', p: '50' }),
D('d-levi-strauss-nature-culture', T, "Pourquoi la prohibition de l'inceste est-elle centrale chez Lévi-Strauss ?",
  "La nature est l'universel spontané, la culture la règle relative ; or l'interdit de l'inceste est une règle sociale mais universelle : point d'articulation entre nature et culture, témoin de la règle de l'échange (don et réciprocité).",
  { a: ['Lévi-Strauss'], n: ['la nature', 'le langage'], o: 'Les Structures élémentaires de la parenté', art: 'Lévi-Strauss', p: '293' }),
D('d-levi-strauss-structuralisme', T, "Qu'est-ce que le structuralisme de Lévi-Strauss ?",
  "Emprunter à la linguistique sa méthode : construire des modèles abstraits (structures) qui donnent la primauté au système sur les éléments. Mythes, masques, relations économiques répondent à une logique combinatoire et se traitent scientifiquement.",
  { a: ['Lévi-Strauss'], n: ['le langage', 'la science'], art: 'Lévi-Strauss', p: '293' }),
D('d-levi-strauss-pensee-sauvage', T, "Que montre La Pensée sauvage ?",
  "Que la pensée dite primitive n'est pas prélogique : rites, totems, systèmes matrimoniaux témoignent d'une approche classificatrice, systématique, anticipant nos démarches scientifiques.",
  { a: ['Lévi-Strauss'], n: ['la science', 'la raison', 'la religion'], o: 'La Pensée sauvage', art: 'Lévi-Strauss', p: '293-294' }),
];
