import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Merleau-Ponty (p. 325-326), Simone Weil (p. 532), Hersch (p. 221-222), Ricœur (p. 434-435) ----------
D('d-merl-etre-au-monde', T, "Que signifie « être-au-monde » chez Merleau-Ponty ?",
  "L'homme concret n'est ni un en-soi ni un pour-soi mais un mixte : conscience incarnée et engagée dans le temps. Un « Je perçois » et non un « Je pense » désincarné ; la phénoménologie décrit le monde plutôt que de l'expliquer.",
  { a: ['Merleau-Ponty'], n: ['la conscience', 'la nature'], o: 'Phénoménologie de la perception', art: 'Merleau-Ponty', p: '325-326' }),
D('d-merl-corps-propre', T, "Qu'est-ce que le corps propre ?",
  "Non un édifice de molécules interchangeables mais un sujet habitant la nature : un ensemble de significations incarnées, présent au monde qu'il partage avec d'autres consciences dans l'intersubjectivité.",
  { a: ['Merleau-Ponty'], n: ['la conscience', 'la nature'], o: 'Phénoménologie de la perception', art: 'Merleau-Ponty', p: '326' }),
D('d-merl-intermonde', T, "Qu'est-ce que l'intermonde chez Merleau-Ponty ?",
  "L'entrelacs de significations entre les consciences : « histoire, symbolisme et vérité à faire », monde des institutions et du langage, tissu des relations intersubjectives ; la relation à autrui est réciprocité conflictuelle et communication inachevée.",
  { a: ['Merleau-Ponty'], n: ['le langage', 'la vérité', 'le temps'], art: 'Merleau-Ponty', p: '326' }),
D('d-weil-travail-libre', T, "Quand le travail est-il libre selon Simone Weil ?",
  "Quand on n'obéit pas aux ordres d'un autre et que conception et exécution ne sont pas séparées. La condition ouvrière, machinale et épuisante, illustre le malheur.",
  { a: ['Weil'], n: ['le travail', 'la liberté'], o: 'Oppression et Liberté', art: 'Weil (Simone)', p: '532' }),
D('d-weil-obligation', T, "Pourquoi Simone Weil préfère-t-elle l'obligation aux droits ?",
  "Les besoins de l'âme déterminent l'obligation, fondement de l'action morale et politique et notion inconditionnée. Le droit est lié à des situations de partage et d'échange, des situations « commerciales ».",
  { a: ['Weil'], n: ['le devoir', 'la justice'], o: 'L’Enracinement', art: 'Weil (Simone)', p: '532' }),
D('d-weil-attention', T, "Qu'est-ce que l'« attention pure » chez Simone Weil ?",
  "L'effort intellectuel qui fait disparaître le moi au profit de l'apparition du réel, analogue à l'abandon de la volonté dans le domaine religieux et à la contemplation esthétique.",
  { a: ['Weil'], n: ['la religion', "l'art", 'la vérité'], o: 'La Pesanteur et la Grâce', art: 'Weil (Simone)', p: '532' }),
D('d-hers-liberte', T, "Quelle est la conviction centrale de Jeanne Hersch ?",
  "« La liberté est le centre de toute l'affaire philosophique » : elle réfléchit aux conditions politiques, culturelles et sociales de la liberté, et à une éducation qui forme le sens des responsabilités.",
  { a: ['Hersch', 'Jaspers'], n: ['la liberté', "l'État"], art: 'Hersch', p: '221-222' }),
D('d-hers-droits', T, "Que montre Le Droit d'être un homme (1968) ?",
  "Que le concept de droits de l'homme, même s'il n'est pas encore universel, correspond à une attente exprimée par tous les hommes, dans toutes les cultures. Pour Hersch, l'étonnement est le ressort de toute philosophie.",
  { a: ['Hersch'], n: ['la justice', "l'État"], o: "Le Droit d'être un homme", art: 'Hersch', p: '222' }),
D('d-rico-hermeneutique', T, "Que signifie « le symbole donne à penser » (Ricœur) ?",
  "L'herméneutique est l'art d'interpréter : il s'agit de chercher à partir des symboles à se comprendre soi-même, car aucune représentation de soi ne passe sans médiation de signes, symboles et textes.",
  { a: ['Ricœur'], n: ['le langage', 'la conscience'], art: 'Ricœur', p: '434' }),
D('d-rico-identite-narrative', T, "Qu'est-ce que l'identité narrative ?",
  "Se raconter est le plus sûr moyen de se connaître ; narrativité et temporalité s'épaulent. La triple mimêsis : préfiguration (action comme récit en puissance), configuration (synthèse narrative), refiguration (lecture qui enrichit la compréhension de soi).",
  { a: ['Ricœur'], n: ['le temps', 'le langage', 'la conscience'], o: 'Temps et Récit', art: 'Ricœur', p: '434-435' }),
D('d-rico-ethique', T, "Quels sont les trois moments de l'agir éthique selon Ricœur ?",
  "L'éthique (visée de la vie bonne), la morale (normes obligatoires), la sagesse pratique qui articule les deux. Formule : viser la vraie vie avec et pour l'autre dans des institutions justes.",
  { a: ['Ricœur'], n: ['le devoir', 'la justice'], art: 'Ricœur', p: '435' }),
];
