import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Moyen Âge : Augustin (p. 38-39), Avicenne (p. 42), Averroès (p. 42), Anselme (p. 22), Maïmonide (p. 310), Ockham (p. 363-364) ----------
D('d-augu-conversion', T, "Comment Augustin comprend-il la conversion ?",
  "Après l'égarement, il constate que la quête des objets du désir laisse anxieux et frustré : la sérénité vient d'un retour sur soi, loin des biens corruptibles, et le désir s'apaise en trouvant son véritable objet, l'absolu (Dieu).",
  { a: ['Augustin'], n: ['le bonheur', 'la religion'], o: 'Confessions', art: 'Augustin', p: '38' }),
D('d-augu-temps', T, "En quoi la conception augustinienne du temps diffère-t-elle de celle de Platon ?",
  "Platon voit le temps comme chute et dégradation ; Augustin le conçoit comme lieu de création et de rédemption possible pour les êtres finis, que Dieu peut tirer du néant et de la finitude.",
  { a: ['Augustin', 'Platon'], n: ['le temps', 'la religion'], o: 'Confessions', art: 'Augustin', p: '38-39' }),
D('d-augu-foi-raison', T, "Comment Augustin articule-t-il foi, autorité et raison ?",
  "La raison seule ne mène pas à la vérité : « la foi précède la quête de Dieu ». L'autorité (Christ, Écriture, Église) n'est pas démission de l'intelligence : « la foi cherche, l'intellect trouve ».",
  { a: ['Augustin'], n: ['la raison', 'la religion', 'la vérité'], art: 'Augustin', p: '39' }),
D('d-augu-deux-cites', T, "Quelles sont les deux cités d'Augustin ?",
  "La cité terrestre, fondée sur l'amour de soi jusqu'au mépris de Dieu ; la cité céleste, fondée sur l'amour de Dieu jusqu'au mépris de soi, qui regroupe toutes les nations respectant Dieu et sa loi.",
  { a: ['Augustin'], n: ["l'État", 'la religion'], o: 'La Cité de Dieu', art: 'Augustin', p: '39' }),
D('d-avic-transmission', T, "Pourquoi Avicenne est-il important pour l'Occident ?",
  "Il puise à l'ismaélisme, au néoplatonisme et surtout à l'aristotélisme (via les commentaires d'Al Farabi) : grâce à lui l'Occident connaît le néoplatonisme islamique et les grands thèmes d'Aristote.",
  { a: ['Avicenne', 'Aristote'], n: ['la raison', 'la science'], o: 'Livre des directives et remarques', art: 'Avicenne', p: '42' }),
D('d-aver-accord', T, "Quel accord Averroès cherche-t-il entre philosophie et religion ?",
  "« La vérité ne saurait contredire la vérité » : rien dans l'aristotélisme bien compris ne contredit le Coran. Trois types d'arguments : oratoires, théologiques, démonstratifs (philosophes) ; le Coran, sous forme d'exhortation, reste accessible à tous.",
  { a: ['Averroès', 'Aristote'], n: ['la religion', 'la raison', 'la vérité'], o: 'Traité décisif', art: 'Averroès', p: '42' }),
D('d-aver-intellect', T, "Quelle thèse d'Averroès sur l'intellect a été combattue au Moyen Âge ?",
  "Il existe une intelligence séparée, la même pour tous : pas d'immortalité des âmes individuelles, et Dieu ne connaît que l'universel. Rejetée par le catholicisme (averroïsme), notamment par Thomas d'Aquin.",
  { a: ['Averroès', 'Thomas d’Aquin'], n: ['la religion', 'la conscience'], art: 'Averroès', p: '42' }),
D('d-ansel-ontologique', T, "Quel est l'argument de Saint Anselme sur l'existence de Dieu ?",
  "Dieu est « ce dont rien de plus grand ne peut être conçu » ; on ne peut penser un tel être sans lui accorder l'existence, sinon ce ne serait pas lui. Kant l'appellera argument ontologique ; on le retrouve chez Descartes.",
  { a: ['Anselme', 'Kant', 'Descartes'], n: ['la religion', 'la raison'], o: 'Proslogion', art: 'Anselme', p: '22' }),
D('d-ansel-foi', T, "Que signifie « la foi en quête d'intelligence » ?",
  "Une foi éclairée vaut mieux qu'une foi aveugle : les articles de foi restent des mystères au-dessus de la raison, mais non contraires à elle, puisque Dieu est rationnellement compréhensible.",
  { a: ['Anselme'], n: ['la religion', 'la raison'], o: 'Monologion', art: 'Anselme', p: '22' }),
D('d-maim-guide', T, "Quel est le but du Guide des égarés de Maïmonide ?",
  "Remettre les égarés sur le droit chemin en montrant que foi et raison, loin de s'opposer, se consolident : connaître Dieu, cultiver son intelligence et comprendre la nature relèvent d'un même dessein. Il est délibérément difficile d'accès.",
  { a: ['Maïmonide'], n: ['la religion', 'la raison'], o: 'Le Guide des égarés', art: 'Maïmonide', p: '310' }),
D('d-ockh-universaux', T, "Que défend Ockham dans la querelle des universaux ?",
  "Une position proche du nominalisme : les universaux ne sont que des concepts sans contenu objectif ; seuls les singuliers sont réels. Exemple : il y a des pères et des enfants, mais pas la paternité en soi.",
  { a: ['Ockham'], n: ['la vérité', 'le langage'], art: 'Ockham', p: '363' }),
D('d-ockh-rasoir', T, "Qu'est-ce que le rasoir d'Ockham ?",
  "Un principe d'économie de la pensée : il ne faut pas multiplier les hypothèses non nécessaires. Il ouvre la « voie moderne » et une déconstruction de la métaphysique.",
  { a: ['Ockham'], n: ['la science', 'la raison'], art: 'Ockham', p: '363' }),
D('d-ockh-politique', T, "Quelles conséquences politiques Ockham tire-t-il de la contingence de l'ordre du monde ?",
  "L'ordre du monde aurait pu être autre : seule la révélation donne des certitudes, toute médiation (pape, princes) est superflue. Séparation des pouvoirs spirituel et temporel ; toute autorité procède du consentement des hommes (ébauche du contrat).",
  { a: ['Ockham'], n: ["l'État", 'la religion', 'la liberté'], art: 'Ockham', p: '363-364' }),
];
