import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Thomas d'Aquin (p. 495-496), Sénèque (p. 455-456), Nâgârjuna (p. 347), Sextus (p. 461), Zhuangzi (p. 538-539), présocratiques (p. 401-402), Zénon (p. 538) ----------
D('d-thom-foi-raison', T, "Quelle position Thomas d'Aquin adopte-t-il face à Aristote redécouvert ?",
  "Il refuse de choisir entre la Bible (Création, foi surnaturelle) et Aristote lu par Averroès : la philosophie ne s'oppose pas à la foi, dont elle est la « servante ». Résoudre les problèmes de foi par la seule autorité, c'est avoir la vérité « dans une tête vide ».",
  { a: ['Thomas d’Aquin', 'Aristote', 'Averroès'], n: ['la religion', 'la raison'], o: 'Somme théologique', art: 'Thomas d’Aquin', p: '495' }),
D('d-thom-creation-liberte', T, "Que réaffirme Thomas d'Aquin contre Averroès ?",
  "L'unité de l'âme et du corps, l'immortalité personnelle de l'âme, la liberté de l'homme (compatible avec la Création : Dieu est assez puissant pour créer des êtres autonomes). La Création implique la contingence du monde.",
  { a: ['Thomas d’Aquin', 'Averroès'], n: ['la liberté', 'la religion', 'la conscience'], o: 'Somme contre les Gentils', art: 'Thomas d’Aquin', p: '495' }),
D('d-thom-prudence', T, "Que devient la sagesse morale chez Thomas d'Aquin ?",
  "Une « prudence » : intelligence pratique éclairée par la foi, qui tente de réconcilier Augustin et Aristote sur les questions morales.",
  { a: ['Thomas d’Aquin'], n: ['le devoir', 'le bonheur'], art: 'Thomas d’Aquin', p: '495' }),
D('d-sene-nature-fortune', T, "Quelle originalité présente le stoïcisme de Sénèque ?",
  "Il reprend l'opposition entre la nature (en nous) et la fortune (extérieure), mais en moraliste non doctrinaire : art de vivre, sans ignorer l'inquiétude ; la sagesse est rare, le bonheur consiste peut-être à se tenir à l'écart des pires vicissitudes.",
  { a: ['Sénèque'], n: ['le bonheur', 'la nature'], art: 'Sénèque', p: '455' }),
D('d-sene-presente', T, "Où Sénèque cherche-t-il le Souverain Bien ?",
  "Dans la cura, conscience attentive qui saisit l'occasion : le bonheur tient à la capacité de vivre intensément le temps présent, en renonçant à se libérer du devenir. Il assimile finalement la seule vertu au Souverain Bien.",
  { a: ['Sénèque'], n: ['le temps', 'le bonheur'], art: 'Sénèque', p: '456' }),
D('d-sene-universalite', T, "Quelle idée Sénèque promeut-il sur la condition humaine ?",
  "L'universalité de la condition humaine, jusqu'à défendre les esclaves ; la nécessité d'un maître spirituel, peu d'hommes ayant seuls la force d'être sages ; la tension entre carrière politique et vie contemplative.",
  { a: ['Sénèque'], n: ['le devoir', 'la justice'], art: 'Sénèque', p: '456' }),
D('d-nagar-vacuite', T, "Qu'est-ce que la vacuité (Nâgârjuna) ?",
  "Il n'y a aucune substance ni réalité indépendante des phénomènes : tout ce qui apparaît est illusoire, à commencer par le « je ». Nâgârjuna n'est pourtant pas nihiliste : il se tient au milieu (madhyamaka) et ne nie pas une réalité ultime, au-delà de toute formulation logique.",
  { a: ['Nâgârjuna'], n: ['la vérité', 'la conscience', 'le langage'], o: 'Stances du milieu par excellence', art: 'Nâgârjuna', p: '347' }),
D('d-nagar-jugement', T, "Pourquoi Nâgârjuna s'exprime-t-il par paradoxes ?",
  "Pour déconstruire les convictions véhiculées par le langage ordinaire et suggérer l'ineffable : « ni être ni non-être… il est nécessaire de suspendre son jugement ». Ce scepticisme va avec la compassion et le respect de tous les êtres sensibles.",
  { a: ['Nâgârjuna'], n: ['le langage', 'la raison', 'la religion'], art: 'Nâgârjuna', p: '347' }),
D('d-sext-scepticisme', T, "Qu'est-ce que le scepticisme pyrrhonien selon Sextus Empiricus ?",
  "Face aux contradictions entre doctrines dogmatiques (aporie), on continue de chercher en suspendant son assentiment (épochê). La voie sceptique est « chercheuse, suspensive, aporétique et pyrrhonienne » ; le sceptique n'affirme pas même que le réel est inconnaissable.",
  { a: ['Sextus Empiricus'], n: ['la vérité', 'la raison'], o: 'Esquisses pyrrhoniennes', art: 'Sextus Empiricus', p: '461' }),
D('d-sext-ataraxie', T, "Comment vit le sceptique et où trouve-t-il l'ataraxie ?",
  "Il suspend son assentiment sur ce que sont les choses mais suit les règles de la vie quotidienne sans soutenir d'opinion. Il atteint, sans l'avoir cherchée, la tranquillité de l'âme. Montaigne s'en est directement inspiré.",
  { a: ['Sextus Empiricus', 'Montaigne'], n: ['le bonheur', 'la vérité'], o: 'Esquisses pyrrhoniennes', art: 'Sextus Empiricus', p: '461' }),
D('d-zhua-tao', T, "Qu'est-ce que le Tao chez Zhuangzi ?",
  "Le principe générateur de l'essence et de l'existence de l'Univers, un « souffle » unique qui produit la vie par condensation et la mort par dispersion. Le Tao est le tout, un, éternel, à la fois chemin et but du sage.",
  { a: ['Zhuangzi'], n: ['la nature', 'la vérité'], o: 'Zhuangzi', art: 'Zhuangzi', p: '538-539' }),
D('d-zhua-opposition', T, "Que signifie le dépassement des oppositions chez Zhuangzi ?",
  "Soi et l'autre, possible et impossible, vrai et faux ne s'opposent plus : c'est le « pivot du Tao ». Il n'y a pas relativisme : chaque opinion porte une vérité partielle, et la vérité du tout apparaît par illumination.",
  { a: ['Zhuangzi'], n: ['la vérité', 'la raison'], o: 'Zhuangzi', art: 'Zhuangzi', p: '539' }),
D('d-zhua-non-agir', T, "Qu'est-ce que le non-agir taoïste ?",
  "Diminuer son action jusqu'à ne rien faire : « en ne faisant rien, il n'y a rien qui ne se fasse ». Empiriquement, le saint accepte son sort ; ce fatalisme a été critiqué par d'autres écoles chinoises.",
  { a: ['Zhuangzi'], n: ['la liberté', 'le travail'], o: 'Zhuangzi', art: 'Zhuangzi', p: '539' }),
D('d-pres-naissance', T, "Qu'ont de nouveau les présocratiques ?",
  "Ils renoncent aux dieux ou aux forces magiques pour expliquer le monde et cherchent un principe naturel, une substance primordiale (phusiologoi). Ils substituent des cosmogonies aux théologies astrales : premiers efforts pour représenter l'Univers comme ordre naturel saisissable par l'esprit.",
  { a: ['présocratiques'], n: ['la nature', 'la science', 'la raison'], art: 'présocratiques', p: '401-402' }),
D('d-pres-succession', T, "Quelle est la succession retenue des présocratiques ?",
  "Milésiens (Thalès, Anaximandre, Anaximène), Pythagore, Héraclite, Éléates (Xénophane, Parménide, Zénon), Empédocle, Anaxagore, atomistes (Leucippe, Démocrite). Thalès : l'eau ; Anaximène : l'air.",
  { a: ['présocratiques'], n: ['la nature'], art: 'présocratiques', p: '401' }),
D('d-pres-xenophane', T, "Que critique Xénophane ?",
  "L'anthropomorphisme religieux : « si les bœufs savaient dessiner… les bœufs donneraient aux dieux une forme bovine ». La façon de se représenter le divin exige une plus grande rigueur.",
  { a: ['présocratiques'], n: ['la religion', 'la raison'], art: 'présocratiques', p: '402' }),
D('d-zeno-paradoxes', T, "Que sont les paradoxes de Zénon d'Élée et où est la faille selon Aristote ?",
  "Un mobile ne peut atteindre le terme (il faut parcourir la moitié, puis la moitié de la moitié…) ; Achille ne rattrape pas la tortue. Aristote en relève la faille : une représentation trompeuse du temps comme addition d'instants.",
  { a: ['présocratiques', 'Aristote'], n: ['le temps', 'la raison'], art: 'Zénon (d’Élée)', p: '538' }),
];
