import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Aristote (p. 30-32) ----------
D('d-aris-empirisme', T, "En quoi la méthode d'Aristote s'oppose-t-elle à celle de Platon ?",
  "Elle est empirique : les principes se découvrent en suivant l'expérience. Aristote refuse un monde intelligible séparé et distingue dans toute chose une forme et une matière.",
  { a: ['Aristote', 'Platon'], n: ['la science'], art: 'Aristote', p: '30' }),
D('d-aris-forme-matiere', T, "Que sont la forme et la matière chez Aristote ?",
  "La forme fait que la chose est ce qu'elle est ; la matière en est le support, indéterminée et capable de changement (puissance). Statue de Zeus : marbre (matière), traits du dieu (forme).",
  { a: ['Aristote'], n: ['la nature', "l'art"], art: 'Aristote', p: '30-31' }),
D('d-aris-syllogisme', T, "Qu'est-ce que le syllogisme et pourquoi Aristote invente-t-il la logique formelle ?",
  "Raisonnement qui, à partir de prémisses, rend la conclusion nécessaire, indépendamment du contenu. Pour Aristote il doit aussi révéler la cause réelle du fait : la science porte sur le général et le nécessaire.",
  { a: ['Aristote'], n: ['la raison', 'la science'], o: 'Organon', art: 'Aristote', p: '31' }),
D('d-aris-metaphysique', T, "Quel est l'objet de la métaphysique selon Aristote ?",
  "L'être en tant qu'être, les premiers principes et premières causes. L'être se dit en plusieurs sens (catégories : substance, qualité, quantité…). Le divin est acte pur, premier moteur immobile.",
  { a: ['Aristote'], n: ['la vérité'], o: 'Métaphysique', art: 'Aristote', p: '31' }),
D('d-aris-mouvement', T, "Comment Aristote définit-il le mouvement et le cosmos ?",
  "Le mouvement est le passage de la puissance à l'acte, donc une imperfection. Le monde supralunaire ne connaît que le mouvement circulaire parfait ; le monde sublunaire est soumis à la génération et à la corruption.",
  { a: ['Aristote'], n: ['la nature', 'le temps'], o: 'Physique', art: 'Aristote', p: '31' }),
D('d-aris-ame', T, "Quels sont les trois types d'âme distingués par Aristote ?",
  "Végétative (plantes), sensitive (animaux), rationnelle (homme). L'âme est entéléchie : principe d'organisation du vivant.",
  { a: ['Aristote'], n: ['la nature', 'la conscience'], art: 'Aristote', p: '31' }),
D('d-aris-gouvernements', T, "Comment Aristote traite-t-il les régimes politiques par rapport à Platon ?",
  "Il distingue monarchie, aristocratie et république, mais cherche pour chacun les conditions concrètes de réalisation et de stabilité, au lieu de les hiérarchiser selon leur ressemblance avec la cité idéale.",
  { a: ['Aristote', 'Platon'], n: ["l'État"], o: 'Politiques', art: 'Aristote', p: '32' }),
D('d-aris-esclavage', T, "Quelle limite les auteurs du dictionnaire relèvent-ils dans la politique d'Aristote ?",
  "Comme il conçoit la cité comme un organisme aux fonctions propres, il tient l'esclavage et l'inégalité des sexes pour naturels.",
  { a: ['Aristote'], n: ["l'État", 'la nature', 'la justice'], o: 'Politiques', art: 'Aristote', p: '32' }),

// ---------- Épictète, Épicure (p. 157-159) ----------
D('d-epict-dependre', T, "Quelle distinction ouvre le Manuel d'Épictète ?",
  "Il y a des choses qui dépendent de nous (opinions, jugements, volonté, désirs) et d'autres non (corps, richesse, honneurs, événements). Seules les premières sont vraiment nôtres et relèvent du bien et du mal.",
  { a: ['Épictète'], n: ['la liberté', 'le bonheur'], o: 'Manuel', art: 'Épictète', p: '157' }),
D('d-epict-liberte', T, "Comment Épictète définit-il la liberté ?",
  "Elle consiste à vouloir que les choses arrivent non comme il nous plaît, mais comme elles arrivent : accepter l'ordre immuable du monde en le pensant comme nécessaire, et rester digne.",
  { a: ['Épictète'], n: ['la liberté', 'la nature'], o: 'Entretiens', art: 'Épictète', p: '157' }),
D('d-epict-desirs', T, "Pourquoi la morale d'Épictète est-elle un travail progressif sur soi ?",
  "Il faut maîtriser ses désirs pour ne pas poursuivre de faux biens. On y arrive par exercice, en commençant par les petites choses : « on devient philosophe comme on devient athlète ».",
  { a: ['Épictète'], n: ['le bonheur', 'le devoir'], art: 'Épictète', p: '157-158' }),
D('d-epic-trois-parties', T, "Quelles sont les trois parties de la philosophie d'Épicure et pourquoi leur ordre compte-t-il ?",
  "Canonique (critères de vérité), physique (explication de la nature), morale (vie heureuse). L'éthique est le but ; la physique en est la base, la canonique donne la connaissance de la nature.",
  { a: ['Épicure'], n: ['la vérité', 'la nature', 'le bonheur'], art: 'Épicure', p: '158' }),
D('d-epic-sensation', T, "Pourquoi Épicure fait-il des sensations le critère de la vérité ?",
  "Les corps émettent des simulacres qui rencontrent nos sens : la sensation nous met en contact avec les choses mêmes et n'est donc ni subjective ni trompeuse.",
  { a: ['Épicure'], n: ['la vérité', 'la science'], art: 'Épicure', p: '158' }),
D('d-epic-atomisme', T, "Quelle est la physique d'Épicure ?",
  "Atomisme (suivant Démocrite) : atomes se mouvant dans le vide ; « rien ne naît de rien ». L'âme est matérielle, l'ordre du monde est dû au hasard, les dieux existent mais se désintéressent des hommes.",
  { a: ['Épicure'], n: ['la nature', 'la religion'], art: 'Épicure', p: '158' }),
D('d-epic-mort', T, "Pourquoi Épicure affirme-t-il que la mort n'est rien pour nous ?",
  "L'âme est matérielle : la mort est décomposition et privation de sensation. Quand nous existons, la mort n'est pas là ; quand elle est là, nous n'existons plus. On est ainsi délivré des craintes.",
  { a: ['Épicure'], n: ['le bonheur', 'le temps'], art: 'Épicure', p: '158-159' }),
D('d-epic-hedonisme', T, "L'hédonisme d'Épicure est-il une apologie de la jouissance ?",
  "Non : il prône un juste règlement des plaisirs. Le bonheur est ataraxie (absence de trouble) ; la vie du sage est tempérante, contemplative et vertueuse. Le sens courant d'« épicurisme » déforme la doctrine.",
  { a: ['Épicure'], n: ['le bonheur'], art: 'Épicure ; épicurisme', p: '159' }),
];
