import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Descartes (p. 119-121) ----------
D('d-desc-mathesis', T, "Pourquoi Descartes retient-il les mathématiques et quelle idée en tire-t-il ?",
  "Pour la clarté de leurs idées et la certitude de leurs raisons. Il conçoit une « mathématique universelle » : tous les objets doivent s'enchaîner comme des théorèmes, l'unité du savoir venant de l'unité de l'esprit.",
  { a: ['Descartes'], n: ['la raison', 'la science'], art: 'Descartes', p: '119' }),
D('d-desc-evidence', T, "Quel est le principe de la méthode cartésienne et comment se relie-t-il aux trois autres règles ?",
  "L'évidence : n'admettre comme vrai que ce dont la certitude s'impose à un esprit attentif. Puis analyse (diviser), synthèse (du simple au complexe), récapitulation (parcourir toute la chaîne des raisons).",
  { a: ['Descartes'], n: ['la vérité', 'la raison'], o: 'Discours de la méthode', art: 'Descartes', p: '119' }),
D('d-desc-erreur', T, "Comment Descartes explique-t-il la possibilité de l'erreur ?",
  "La volonté (pouvoir de juger) est infinie et dépasse les bornes de l'entendement fini, qui ne conçoit clairement que peu de choses. L'erreur manifeste donc notre libre arbitre.",
  { a: ['Descartes'], n: ['la liberté', 'la vérité'], o: 'Méditations métaphysiques', art: 'Descartes', p: '119-120' }),
D('d-desc-doute-methodique', T, "En quoi le doute cartésien diffère-t-il du doute sceptique ?",
  "Il est provisoire et méthodique : un moyen d'accéder au vrai, non une règle de sagesse comme la suspension du jugement sceptique. Fonction critique : séparer la certitude de l'opinion.",
  { a: ['Descartes'], n: ['la vérité', 'la raison'], art: 'Descartes', p: '120' }),
D('d-desc-cogito-moments', T, "Quels sont les trois moments de la certitude du cogito ?",
  "1. « Je suis, j'existe » : le doute la suppose. 2. Je ne suis certain d'exister que pour autant que je pense. 3. Je suis une chose pensante (res cogitans). La conscience devient le fondement de toute vérité.",
  { a: ['Descartes'], n: ['la conscience', 'la vérité'], art: 'Descartes', p: '120' }),
D('d-desc-dualisme', T, "Que suivent du cogito, selon le dictionnaire : innéisme et dualisme ?",
  "Les idées claires et distinctes sont innées. Âme (pensée, immatérielle) et corps (étendue, mécanisme) sont deux substances aux essences opposées : le monde matériel est une machine, soumise à l'investigation mathématique.",
  { a: ['Descartes'], n: ['la conscience', 'la nature'], art: 'Descartes', p: '120' }),
D('d-desc-creation-continuee', T, "Comment Descartes concilie-t-il monde-machine et existence de Dieu ?",
  "Le monde étant un pur mécanisme, il ne saurait exister par lui-même : il est suspendu à la création divine (création continuée). La nature-machine implique un ingénieur divin.",
  { a: ['Descartes'], n: ['la religion', 'la science', 'la nature'], art: 'Descartes', p: '120' }),
D('d-desc-arbre', T, "Quelle place occupe la morale dans l'arbre du savoir cartésien ?",
  "Métaphysique = racines, physique = tronc, mécanique, médecine et morale = branches. La morale définitive se déduira du savoir constitué ; en attendant, on suit une morale par provision (règles de prudence).",
  { a: ['Descartes'], n: ['le devoir', 'la science'], art: 'Descartes', p: '120' }),
D('d-desc-passions', T, "Comment Descartes traite-t-il les passions ?",
  "Elles résultent de mouvements involontaires du corps et sont subies par l'âme ; leurs représentations sont confuses. Il ne s'agit pas de les supprimer mais de les modérer par la raison et de les utiliser dans notre intérêt.",
  { a: ['Descartes'], n: ['le bonheur', 'la raison'], o: "Les Passions de l'âme", art: 'Descartes', p: '120-121' }),

// ---------- Kant (p. 273-275) ----------
D('d-kant-critique', T, "Que signifient « philosophie critique » et « transcendantal » chez Kant ?",
  "Critique : examen des pouvoirs de la raison et des limites où ils s'exercent légitimement. Transcendantal : qui s'interroge sur les conditions de possibilité de la connaissance et de l'action.",
  { a: ['Kant'], n: ['la raison', 'la science'], art: 'Kant', p: '273' }),
D('d-kant-dogmatisme', T, "Pourquoi le criticisme se distingue-t-il du dogmatisme et du scepticisme ?",
  "La raison est naturellement dogmatique (elle connaît sans examiner ses droits) ; le scepticisme (Hume) la condamne. Le criticisme veut un « tribunal de la raison » posant la question de droit, non seulement de fait.",
  { a: ['Kant', 'Hume'], n: ['la raison', 'la vérité'], art: 'Kant', p: '273' }),
D('d-kant-jugements', T, "Quel type de jugements fonde les sciences selon Kant ?",
  "Des jugements synthétiques a priori : les mathématiques sont a priori sans être analytiques ; les lois physiques informent sur le réel mais valent universellement et nécessairement, ce que l'expérience n'enseigne pas.",
  { a: ['Kant'], n: ['la science', 'la raison'], o: 'Critique de la raison pure', art: 'Kant', p: '273-274' }),
D('d-kant-facultes', T, "Comment Kant articule-t-il sensibilité et entendement, et où est l'objectivité de la connaissance ?",
  "Par la sensibilité, les objets sont donnés en intuitions ; par l'entendement, ils sont pensés et liés. L'objectivité vient du sujet transcendantal : l'esprit humain en général, non tel ou tel individu.",
  { a: ['Kant'], n: ['la raison', 'la science'], o: 'Critique de la raison pure', art: 'Kant', p: '274' }),
D('d-kant-metaphysique', T, "Pourquoi la métaphysique est-elle une « illusion inévitable » selon Kant ?",
  "L'âme, le monde comme totalité et Dieu ne sont pas des objets de connaissance mais des idées de la raison, représentant chacune un inconditionné. La raison veut les traiter en objets, d'où l'illusion.",
  { a: ['Kant'], n: ['la raison', 'la religion'], o: 'Critique de la raison pure', art: 'Kant', p: '274' }),
D('d-kant-jugement-reflechissant', T, "Qu'est-ce que le jugement réfléchissant dans la Critique de la faculté de juger ?",
  "Un jugement qui ne détermine pas un objet par un concept mais exprime subjectivement l'ordre que nous devons admettre dans les objets : jugement téléologique (finalité) et jugement de goût (beau).",
  { a: ['Kant'], n: ["l'art", 'la nature'], o: 'Critique de la faculté de juger', art: 'Kant', p: '274'}),
D('d-kant-postulats', T, "Que sont les postulats de la raison pratique ?",
  "L'existence de Dieu, l'immortalité de l'âme et la liberté : pas des objets de connaissance mais des exigences de la morale. Les principes de la religion sont sauvés pour des raisons rationnelles, non religieuses.",
  { a: ['Kant'], n: ['la religion', 'le devoir', 'la liberté'], o: 'Critique de la raison pratique', art: 'Kant', p: '275' }),
D('d-kant-histoire', T, "Quelle finalité Kant assigne-t-il à l'histoire ?",
  "L'humanité, privée d'instinct, se développe dans la société par le travail et la culture ; l'histoire l'éduque vers le règne de la loi et la paix universelle (société des nations), sans que la justice publique soit jamais acquise.",
  { a: ['Kant'], n: ["l'État", 'la justice', 'le temps'], o: 'Projet de paix perpétuelle', art: 'Kant', p: '275' }),

// ---------- Rousseau (p. 436-437) ----------
D('d-rous-mal', T, "D'où vient le mal social selon Rousseau ?",
  "Ni du péché originel ni de Dieu : l'homme s'est dénaturé, corrompu par sa liberté et sa perfectibilité. Le mal, c'est l'amour-propre, la servitude, l'hypocrisie ; l'état de nature n'est qu'une hypothèse montrant que le mal n'est pas inné.",
  { a: ['Rousseau'], n: ['la nature', 'la liberté'], o: "Discours sur l'origine et les fondements de l'inégalité", art: 'Rousseau', p: '436-437' }),
D('d-rous-perfectibilite-difference', T, "En quoi la perfectibilité chez Rousseau diffère-t-elle de celle de Kant ou Condorcet ?",
  "Elle n'est pas source de progrès mais de dénaturation, dont la vie en société est le terme désastreux.",
  { a: ['Rousseau', 'Kant'], n: ['le temps', 'la nature'], art: 'Rousseau', p: '437' }),
D('d-rous-legitimite', T, "Qu'est-ce qui, selon Rousseau, peut légitimer l'autorité politique ?",
  "Ni l'autorité paternelle, ni Dieu, ni la force (un fait, sans rapport avec le droit) : seule une convention fondamentale, pacte d'association par lequel le peuple se constitue et dont la volonté générale exerce la souveraineté.",
  { a: ['Rousseau'], n: ["l'État", 'la justice'], o: 'Du contrat social', art: 'Rousseau', p: '437' }),
D('d-rous-liberte-politique', T, "Comment obéir à la loi peut-il laisser aussi libre qu'auparavant ?",
  "Le sujet qui obéit à la loi publique obéit à la loi qu'il s'est lui-même fixée, comme citoyen participant à la souveraineté. Cette liberté politique, morale, est plus digne de l'homme que la liberté naturelle.",
  { a: ['Rousseau'], n: ['la liberté', "l'État"], o: 'Du contrat social', art: 'Rousseau', p: '437' }),
D('d-rous-pessimisme', T, "Pourquoi Rousseau ne croit-il pas à un salut collectif ?",
  "Le Contrat ne dit pas ce que l'humanité est, mais ce qu'elle aurait pu devenir avec un meilleur usage de sa perfectibilité. Le salut ne peut être qu'individuel : l'œuvre de l'éducation (Émile).",
  { a: ['Rousseau'], n: ["l'État", 'la nature'], o: 'Émile', art: 'Rousseau', p: '437' }),
D('d-rous-morale-coeur', T, "Que signifie une « morale du cœur » chez Rousseau ?",
  "La conscience est instinct divin, sentiment immédiat et universel, non morale raisonneuse ; le sentiment moral est cependant raisonnable et préfigure la raison pratique de Kant. L'homme naturel, capable de pitié, a des germes de moralité.",
  { a: ['Rousseau', 'Kant'], n: ['la conscience', 'le devoir'], o: 'Émile', art: 'Rousseau', p: '437' }),
D('d-rous-religion-naturelle', T, "Quelle religion défend le Vicaire savoyard ?",
  "La religion naturelle : Dieu est accessible par le cœur, sans textes sacrés ni clergé. Elle critique matérialisme et athéisme, et provoquera la condamnation de l'Émile.",
  { a: ['Rousseau'], n: ['la religion'], o: 'Émile', art: 'Rousseau', p: '437' }),
];
