import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Hegel (p. 215-217) ----------
D('d-heg-comprendre', T, "Quelle est, selon Hegel, la tâche du philosophe ?",
  "Comprendre, non juger le bien et le mal ni proposer des idéaux : penser les choses dans leur totalité et leur mouvement de réconciliation (individu/société, croyant/Dieu, citoyen/État).",
  { a: ['Hegel'], n: ['la raison', "l'État"], art: 'Hegel', p: '215-216' }),
D('d-heg-idealisme', T, "En quel sens l'idéalisme hégélien est-il « absolu » et concret ?",
  "Le concept est l'intériorité et la vie même des choses : le contraire de l'Idée n'est pas le concret mais l'abstrait. L'absolu n'est pas un objet réservé de la philosophie mais son élément, son milieu.",
  { a: ['Hegel'], n: ['la vérité', 'la raison'], art: 'Hegel', p: '216' }),
D('d-heg-vrai-devenir', T, "Pourquoi, pour Hegel, la vérité n'est-elle pas donnée d'emblée comme les Idées de Platon ?",
  "Rien n'existe immédiatement : tout doit devenir soi. L'Esprit et la vérité se révèlent progressivement à travers un processus historique nécessaire ; l'identité est conquise, non donnée.",
  { a: ['Hegel', 'Platon'], n: ['la vérité', 'le temps'], art: 'Hegel', p: '216' }),
D('d-heg-dialectique', T, "Qu'est-ce que le mouvement dialectique chez Hegel ?",
  "Non une méthode mais la vie même de l'Esprit : il progresse par le négatif, chaque figure supérieure supposant la suppression de la précédente (fleur/fruit, enfant/adulte), et non par cumul de découvertes.",
  { a: ['Hegel'], n: ['la raison', 'le temps'], o: "Phénoménologie de l'esprit", art: 'Hegel', p: '216' }),
D('d-heg-histoire-raison', T, "Comment Hegel justifie-t-il de voir de la raison dans l'histoire ?",
  "Dans le chaos des intérêts, des passions et des guerres, il observe le travail d'une raison universelle qui utilise la folie des hommes pour se réaliser. L'État moderne est la réalisation effective de la liberté concrète.",
  { a: ['Hegel'], n: ['le temps', "l'État", 'la liberté'], art: 'Hegel', p: '217' }),
D('d-heg-esthetique', T, "Comment l'esthétique hégélienne lit-elle les formes de l'art ?",
  "Comme présentations successives de l'Esprit sous des formes sensibles, de l'architecture des pyramides aux peintures chrétiennes de la Passion.",
  { a: ['Hegel'], n: ["l'art"], o: 'Esthétique', art: 'Hegel', p: '217' }),

// ---------- Nietzsche (p. 355-356) ----------
D('d-niet-aphorisme', T, "Pourquoi Nietzsche écrit-il par aphorismes ?",
  "La dispersion de la forme traduit le soupçon porté sur l'entreprise philosophique, interprétée jusque-là comme recherche désintéressée du vrai. L'unité de l'œuvre est la condamnation de la métaphysique.",
  { a: ['Nietzsche'], n: ['la vérité', 'le langage'], art: 'Nietzsche', p: '355' }),
D('d-niet-monde-vrai', T, "Comment Nietzsche interprète-t-il la métaphysique platonicienne et chrétienne ?",
  "Comme dépréciation de la vie sensible et du corps au profit de vérités supérieures : la fiction d'un « monde vrai » serait le refuge d'organismes malades et lâches devant les passions de la vie.",
  { a: ['Nietzsche', 'Platon'], n: ['la vérité', 'la religion'], art: 'Nietzsche', p: '355' }),
D('d-niet-science-foi', T, "Pourquoi la science est-elle, selon Nietzsche, un dernier rempart de l'esprit religieux ?",
  "Elle suppose une foi inconditionnée dans la vérité : expression laïque de la volonté du « vrai ». De Platon au positivisme, l'Occident produit l'homme du ressentiment et conduit au nihilisme.",
  { a: ['Nietzsche'], n: ['la science', 'la vérité', 'la religion'], art: 'Nietzsche', p: '355' }),
D('d-niet-puissance', T, "Que désigne la volonté de puissance selon le dictionnaire ?",
  "Ce qui traverse l'Univers, monde des rapports de force instables et réversibles, un perpétuel devenir, monde dionysiaque de la douleur et de l'ivresse.",
  { a: ['Nietzsche'], n: ['la nature', 'le temps'], art: 'Nietzsche', p: '355-356' }),
D('d-niet-artiste', T, "Quel rôle Nietzsche donne-t-il à l'artiste face au devenir ?",
  "L'artiste, en créant des formes, s'inscrit dans le mouvement de la volonté de puissance : il répète l'apparence pour elle-même, alors que les fictions du métaphysicien la masquaient au profit d'un être vrai transcendant.",
  { a: ['Nietzsche'], n: ["l'art", 'la vérité'], art: 'Nietzsche', p: '356' }),
D('d-niet-eternel-retour', T, "Que permet l'éternel retour face à la menace de vanité totale ?",
  "Il affirme que tout ce qui est l'objet d'une volonté authentique se répétera indéfiniment ; il ouvre à la volonté de puissance l'espace de s'affirmer en toute innocence.",
  { a: ['Nietzsche'], n: ['le temps', 'la liberté'], o: 'Ainsi parlait Zarathoustra', art: 'Nietzsche', p: '356' }),

// ---------- Freud (p. 196-197) ----------
D('d-freud-hysterie', T, "Comment l'hystérie conduit-elle Freud à l'inconscient ?",
  "Les hystériques souffrent de réminiscences : leurs symptômes sont la résurgence déguisée d'événements que le caractère déplaisant a rendus inaccessibles (refoulement). Leur retour à la conscience atténue les symptômes (catharsis).",
  { a: ['Freud'], n: ["l'inconscient"], o: "Études sur l'hystérie", art: 'Freud', p: '196' }),
D('d-freud-determinisme', T, "Qu'est-ce que le déterminisme psychique ?",
  "Rêves, actes manqués, lapsus s'inscrivent dans une chaîne de causes dont l'origine est une source pathogène refoulée. Il fonde la méthode des libres associations et efface la frontière nette entre normal et pathologique.",
  { a: ['Freud'], n: ["l'inconscient", 'la liberté'], art: 'Freud', p: '196-197' }),
D('d-freud-nevrose', T, "Qu'est-ce que la névrose et comment peut-elle se résoudre selon Freud ?",
  "Une fuite devant la réalité : compromis entre pulsions refoulées et exigences du surmoi (« refuge dans la maladie »). Résolution : satisfaction assumée, refus conscient, ou sublimation.",
  { a: ['Freud'], n: ["l'inconscient", 'le bonheur'], art: 'Freud', p: '197' }),
D('d-freud-religion', T, "Comment Freud explique-t-il la religion (L'Avenir d'une illusion) ?",
  "Comme illusion reproduisant à l'échelle sociale la relation de l'enfant à l'autorité parentale, protectrice et répressive : Dieu est une reproduction du père tout-puissant de l'enfance.",
  { a: ['Freud'], n: ['la religion', "l'inconscient"], o: "L'Avenir d'une illusion", art: 'Freud', p: '197' }),
D('d-freud-art', T, "Quelle fonction Freud donne-t-il à l'art ?",
  "Satisfaire dans l'imaginaire ce que le réel refuse, notamment par la sublimation des pulsions.",
  { a: ['Freud'], n: ["l'art", "l'inconscient"], art: 'Freud', p: '197' }),
D('d-freud-culpabilite', T, "Comment naissent culpabilité et angoisse selon Freud ?",
  "La répression des pulsions produit intériorisation des interdits et agressivité contre ceux qui les formulent ; ceux-ci étant aussi aimés, l'agressivité se retourne contre soi et engendre culpabilité et angoisse.",
  { a: ['Freud'], n: ['le devoir', "l'inconscient"], art: 'Freud', p: '197' }),
];
