import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Bergson (p. 53-54) ----------
D('d-berg-duree-caracteres', T, "Quels sont les trois caractères de la durée bergsonienne ?",
  "Continuité (le temps abstrait se fractionne en moments), indivisibilité (non mesurable, chaque moment est fonction de la totalité du passé) et changement (jamais identique à elle-même, donc imprévisible, lieu de la liberté).",
  { a: ['Bergson'], n: ['le temps', 'la liberté'], art: 'Bergson', p: '53' }),
D('d-berg-temps-spatialise', T, "Pourquoi le temps des physiciens est-il un temps « spatialisé » ?",
  "Il est juxtaposition d'instants immobiles, divisible, réversible, mesurable : il a les caractères de l'espace. La durée est concrète, qualitative, hétérogène et se saisit d'abord dans la vie intérieure.",
  { a: ['Bergson'], n: ['le temps', 'la science', 'la conscience'], art: 'Bergson', p: '53' }),
D('d-berg-deux-memoires', T, "Quelle différence entre mémoire-habitude et mémoire pure ?",
  "La mémoire-habitude est du souvenir converti en action et en présent (le geste du skieur). La mémoire pure, détachée du souci d'agir, est un pur état de conscience qui ramène l'esprit à la durée.",
  { a: ['Bergson'], n: ['le temps', 'la conscience'], o: 'Matière et mémoire', art: 'Bergson', p: '53-54' }),
D('d-berg-intelligence-intuition', T, "Comment Bergson oppose-t-il intelligence et intuition ?",
  "L'intelligence sert l'action : elle découpe le réel et pense l'immobile. L'intuition vise la connaissance : « connaissance directe de l'esprit par l'esprit », sympathie avec l'objet dans son individualité, imparfaitement traduisible par le langage.",
  { a: ['Bergson'], n: ['la vérité', 'le langage', 'la science'], art: 'Bergson', p: '54' }),
D('d-berg-science-philosophie', T, "Quel est le rapport entre science et philosophie chez Bergson ?",
  "Elles ne sont pas concurrentes : la science (intelligence, matière) sert l'action ; la philosophie (intuition, esprit) sert une connaissance pure. Toutes deux atteignent un absolu quant à leur objet propre.",
  { a: ['Bergson'], n: ['la science', 'la vérité'], o: 'La Pensée et le Mouvant', art: 'Bergson', p: '54' }),
D('d-berg-morale-clos-ouvert', T, "Comment Bergson applique-t-il l'opposition clos/ouvert à la morale et à la religion ?",
  "Clos : règles rigides (la morale kantienne) ou pure observance des rituels. Ouvert : élan spirituel, morale du saint ou du héros, rapport personnel et dynamique à Dieu plutôt que culte statique.",
  { a: ['Bergson', 'Kant'], n: ['le devoir', 'la religion'], o: 'Les Deux Sources de la morale et de la religion', art: 'Bergson', p: '54' }),

// ---------- Sartre (p. 445-446) ----------
D('d-sart-contingence', T, "Que révèle la contingence chez Sartre (La Nausée, L'Être et le Néant) ?",
  "L'existence pure, injustifiée (facticité), sans arrière-monde, Dieu ni valeurs préexistantes. L'individu, jeté hors de l'existence par sa conscience, peut lui donner un sens : c'est sa transcendance, sa liberté.",
  { a: ['Sartre'], n: ['la liberté', 'la conscience'], art: 'Sartre', p: '445' }),
D('d-sart-liberte-neant', T, "Pourquoi la liberté est-elle « un trou dans l'être » ?",
  "Elle n'est pas un être mais un néant, toujours à faire : un projet, une visée (intentionnalité). Elle se vit dans l'angoisse et se traduit par des actes dont on est totalement responsable.",
  { a: ['Sartre', 'Husserl'], n: ['la liberté', 'la conscience'], o: "L'Être et le Néant", art: 'Sartre', p: '445' }),
D('d-sart-autrui', T, "Quel double rôle joue autrui pour Sartre ?",
  "L'enfer, c'est les autres qui jugent ; mais autrui est aussi « le médiateur entre moi et moi-même », constitutif de mon être. Ma liberté passe donc par celle de l'autre.",
  { a: ['Sartre'], n: ['la liberté', 'la conscience'], art: 'Sartre', p: '445' }),
D('d-sart-engagement', T, "Que signifie l'engagement chez Sartre ?",
  "La liberté est toujours située (rupture possible d'avec ses conditions). L'engagement est le moment où le mot, l'acte, la création réalisent cette liberté ; pas la liberté du fort contre le faible, qui ferme le champ de l'intersubjectivité.",
  { a: ['Sartre'], n: ['la liberté', 'le devoir', 'la justice'], o: 'Les Temps modernes', art: 'Sartre', p: '445' }),
D('d-sart-morale-concrete', T, "Quelle morale Sartre esquisse-t-il dans les Cahiers pour une morale ?",
  "Une morale concrète : la liberté est le fondement de toutes les valeurs, la morale est création de valeurs, à la manière de l'artiste. Les hommes ne créent que des îlots de liberté : un « optimisme tragique ».",
  { a: ['Sartre'], n: ['le devoir', "l'art", 'la liberté'], o: 'Cahiers pour une morale', art: 'Sartre', p: '446' }),

// ---------- Arendt (p. 29-30) ----------
D('d-aren-prive-public', T, "Pourquoi, selon Arendt, la société moderne confond-elle le privé et le public ?",
  "Elle réduit la politique à la gestion et la vie publique aux activités privées (travail et consommation), par confusion des modalités de l'activité humaine : travail, œuvre et action.",
  { a: ['Arendt'], n: ['le travail', "l'État"], o: "Condition de l'homme moderne", art: 'Arendt', p: '29' }),
D('d-aren-travail-oeuvre-action', T, "Travail, œuvre, action : que désigne chacun chez Arendt (dictionnaire) ?",
  "Travail (labor) : activité de routine soumise aux processus vitaux. Œuvre (work) : fabrication d'un monde humain d'objets durables. Action : politique, liberté et capacité d'innover, débat et espace public.",
  { a: ['Arendt', 'Marx'], n: ['le travail', 'la liberté'], o: "Condition de l'homme moderne", art: 'Arendt', p: '29' }),
D('d-aren-pouvoir', T, "Comment Arendt définit-elle le pouvoir ?",
  "L'expression de l'initiative à plusieurs, non un exercice de puissance ou de souveraineté. Il est action, liberté partagée, contenu et stabilisé par la loi, associé à la mémoire ; son contraire est la violence.",
  { a: ['Arendt'], n: ["l'État", 'la liberté', 'la justice'], art: 'Arendt', p: '29' }),
D('d-aren-totalitarisme-camps', T, "Comment le totalitarisme fonctionne-t-il selon Les Origines du totalitarisme ?",
  "Il vise la domination totale par destruction du tissu social et atomisation en masse inerte ; cohésion par l'idéologie et la terreur, dont les camps sont l'apogée : « tout est permis, tout est possible ».",
  { a: ['Arendt'], n: ["l'État", 'la liberté'], o: 'Les Origines du totalitarisme', art: 'Arendt', p: '29' }),
D('d-aren-eichmann', T, "Comment Arendt décrit-elle Eichmann ?",
  "Comme un fonctionnaire scrupuleux, soucieux de faire son devoir, jusqu'à s'identifier au principe de la loi, non comme un sadique. Sa monstruosité tient à un « vide de pensée » et à l'obéissance consentante.",
  { a: ['Arendt'], n: ['le devoir', 'la conscience'], o: 'Eichmann à Jérusalem', art: 'Arendt', p: '29-30' }),
D('d-aren-pensee', T, "Quel lien Arendt établit-elle entre pensée et conscience morale ?",
  "La pensée n'est pas garantie de bonté, mais l'activité pensante (dialogue, écart de soi à soi visant la réconciliation) reste le seul fondement concevable de la conscience morale.",
  { a: ['Arendt'], n: ['la conscience', 'le devoir'], o: "La Vie de l'esprit", art: 'Arendt', p: '30' }),
];
