import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Spinoza (p. 473-474) ----------
D('d-spin-souverain-bien', T, "Quel est le Souverain Bien cherché par Spinoza ?",
  "Un « bien véritable qui puisse se communiquer » et donne la béatitude : la vie selon la raison, qui sauve du trouble des passions (finalité morale exposée dès le Traité de la réforme de l'entendement).",
  { a: ['Spinoza'], n: ['le bonheur', 'la raison'], o: 'Éthique', art: 'Spinoza', p: '473' }),
D('d-spin-geometrie', T, "Pourquoi l'Éthique est-elle rédigée « selon l'ordre géométrique » ?",
  "Chaque partie procède comme un mathématicien : définitions, axiomes, propositions démontrées, scolies. On part de l'idée de l'être le plus parfait pour en faire découler toutes les idées.",
  { a: ['Spinoza'], n: ['la raison', 'la science'], o: 'Éthique', art: 'Spinoza', p: '473' }),
D('d-spin-substance', T, "Quels sont les principes métaphysiques de Spinoza ?",
  "Il n'existe d'autre substance que Dieu, c'est-à-dire la nature, dont tout est mode ou attribut. Tout découle de la nécessité naturelle : déterminisme strict, pas de causes finales, libre arbitre illusoire ; les idées (pensée) correspondent aux choses (étendue).",
  { a: ['Spinoza'], n: ['la nature', 'la religion', 'la liberté'], o: 'Éthique', art: 'Spinoza', p: '473' }),
D('d-spin-trois-genres', T, "Quels sont les trois genres de connaissance chez Spinoza ?",
  "1. Ouï-dire et expérience vague (passions, superstition). 2. Raison : définir, déduire, former des idées claires et distinctes. 3. Connaissance intuitive : voir chaque chose comme découlant de la nature divine ; joie la plus haute.",
  { a: ['Spinoza'], n: ['la raison', 'la vérité', 'le bonheur'], o: 'Éthique', art: 'Spinoza', p: '473' }),
D('d-spin-vrai-bien', T, "En quoi consiste le vrai bien selon l'Éthique ?",
  "Dans l'extension de la puissance de connaître. Rien n'est plus utile à l'homme qu'un autre homme vivant selon la raison. Crainte, honte, tristesse n'engendrent qu'une fausse concorde. La béatitude est la vertu elle-même (amour intellectuel de Dieu).",
  { a: ['Spinoza'], n: ['le bonheur', 'la liberté'], o: 'Éthique', art: 'Spinoza', p: '473-474' }),
D('d-spin-ttp', T, "Que défend le Traité théologico-politique ?",
  "La tolérance et l'indépendance des pouvoirs religieux et politique ; la liberté de philosopher doit être totale pour la paix dans l'État, garant d'une foi universelle fondée sur la justice et la charité.",
  { a: ['Spinoza'], n: ['la religion', "l'État", 'la liberté'], o: 'Traité théologico-politique', art: 'Spinoza', p: '474' }),
D('d-spin-tp-dictionnaire', T, "Que dit le dictionnaire du Traité politique et de la démocratie ?",
  "Spinoza y définit la fin de la société civile par la paix et la sécurité, le droit par la puissance, et examine monarchie, aristocratie, démocratie. L'ouvrage est inachevé ; la démocratie est le régime « le plus naturel » et « le plus rationnel ».",
  { a: ['Spinoza'], n: ["l'État", 'la justice'], o: 'Traité politique', art: 'Spinoza', p: '474' }),

// ---------- Simondon (p. 462-463) ----------
D('d-simo-humanisme', T, "Quel projet oriente la réflexion de Simondon sur la technique ?",
  "Réconcilier culture et technologie en refusant un « humanisme technophobe ». La technologie n'est pas faite pour être subie : il faut comprendre le progrès technique et apprécier l'innovation.",
  { a: ['Simondon'], n: ['la technique'], o: "Du mode d'existence des objets techniques", art: 'Simondon', p: '462-463' }),
D('d-simo-hylemorphisme', T, "Que critique Simondon dans l'hylémorphisme ?",
  "La théorie d'Aristote selon laquelle tout être résulte de la rencontre de la matière et de la forme. Pour Simondon, les choses sont faites de relations : l'état fondamental de toute réalité est « préindividuel ».",
  { a: ['Simondon', 'Aristote'], n: ['la nature', 'la technique'], o: "L'Individuation à la lumière des notions de forme et d'information", art: 'Simondon', p: '462' }),
D('d-simo-transduction', T, "Qu'est-ce que la transduction chez Simondon ?",
  "Le processus par lequel deux ou plusieurs ordres de réalités s'associent et deviennent commensurables, permettant le passage à un ordre enrichi. Elle fonde une ontologie génétique et antisubstantialiste.",
  { a: ['Simondon'], n: ['la nature'], art: 'Simondon', p: '462-463' }),
D('d-simo-humain-objet', T, "Que veut dire Simondon par « il y a de l'humain dans l'objet technique » ?",
  "Les objets techniques, jugés opaques et jetés avant d'être aimés, portent de l'humain ; il peut être sauvé si l'homme leur est bienveillant. La concrétisation (intégration de fonctions) est à apprécier, non à mépriser.",
  { a: ['Simondon'], n: ['la technique', 'le travail'], art: 'Simondon', p: '463' }),

// ---------- Leibniz (p. 290-291) ----------
D('d-leib-raison', T, "Quelle est la position de Leibniz face au rationnalisme de Descartes ?",
  "Il pense la raison partout présente et la réalité inépuisable : son rationalisme ne répudie pas la réalité sensible et changeante. Exigence : penser l'unité sans renoncer à la diversité, et la diversité sans renoncer à l'unité.",
  { a: ['Leibniz', 'Descartes'], n: ['la raison'], art: 'Leibniz', p: '290' }),
D('d-leib-monade', T, "Qu'est-ce qu'une monade ?",
  "La substance individuelle, unité vraie interne (non simple agrégat), unique, force active, « sans portes ni fenêtres » : elle tire de son propre fonds tout ce qui lui arrive et contient toutes ses déterminations.",
  { a: ['Leibniz'], n: ['la nature'], o: 'Monadologie', art: 'Leibniz', p: '290' }),
D('d-leib-petites-perceptions', T, "Que sont les petites perceptions ?",
  "La perception est la somme de petites perceptions inconscientes : percevoir le bruit d'une vague, c'est percevoir sans s'en rendre compte le bruit de chaque goutte. Chaque monade exprime tout l'Univers de son point de vue.",
  { a: ['Leibniz'], n: ["l'inconscient", 'la conscience'], o: 'Nouveaux Essais sur l’entendement humain', art: 'Leibniz', p: '290-291' }),
D('d-leib-harmonie', T, "En quoi consiste l'harmonie préétablie ?",
  "Sans action d'une monade sur une autre, il y a correspondance entre elles dans un Univers réglé par Dieu. Elle résout l'union âme-corps : ils sont « accommodés » l'un à l'autre.",
  { a: ['Leibniz'], n: ['la conscience', 'la religion'], art: 'Leibniz', p: '291' }),
D('d-leib-meilleur-monde', T, "Pourquoi le monde est-il « le meilleur des mondes possibles » ?",
  "Par le principe de raison suffisante : si tous les mondes étaient également bons, Dieu n'aurait aucune raison de créer l'un plutôt que l'autre. Il allie maximum d'ordre et de variété. Le mal vient de la limitation originelle des créatures.",
  { a: ['Leibniz'], n: ['la raison', 'la religion'], o: 'Essais de théodicée', art: 'Leibniz', p: '291' }),
];
