import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Hobbes (p. 226-227) ----------
D('d-hobb-projet', T, "Quelle est l'ambition de Hobbes dans le Léviathan ?",
  "Élaborer une théorie rationnelle du pouvoir, être le Galilée de la science morale et politique en appliquant la physique mécanique à l'homme et à la société. Le pouvoir est nécessaire mais non naturel, puisque les hommes sont égaux.",
  { a: ['Hobbes'], n: ["l'État", 'la science'], o: 'Léviathan', art: 'Hobbes', p: '226' }),
D('d-hobb-etat-nature', T, "Que désigne l'état de nature chez Hobbes et pourquoi est-il une guerre de tous contre tous ?",
  "Une fiction théorique : les hommes sans pouvoir ni loi, mus par la conservation de soi. Égaux en désirs, droits et moyens, ils entrent en rivalité, méfiance, lutte pour la réputation ; l'angoisse de la mort les fait attaquer les premiers.",
  { a: ['Hobbes'], n: ['la nature', "l'État"], o: 'Léviathan', art: 'Hobbes', p: '226' }),
D('d-hobb-pacte', T, "Comment naît le pouvoir chez Hobbes ?",
  "Par un pacte mutuel : chacun renonce à son droit naturel et en confie l'exercice à un souverain (homme ou assemblée), en échange d'ordre et de sécurité. L'origine du pouvoir est artificielle et humaine, ni naturelle ni divine.",
  { a: ['Hobbes'], n: ["l'État", 'la justice'], o: 'Léviathan', art: 'Hobbes', p: '227' }),
D('d-hobb-absolutisme', T, "Pourquoi le pouvoir doit-il être absolu selon Hobbes ?",
  "Le souverain est hors du contrat, son droit et sa puissance illimités. L'absoluité est condition de stabilité (un pouvoir partagé serait discuté, divisé, détruit) et garantie de légitimité (il s'exerce au nom des sujets qui l'ont autorisé).",
  { a: ['Hobbes'], n: ["l'État", 'la liberté'], o: 'Léviathan', art: 'Hobbes', p: '227' }),

// ---------- Locke (p. 300-301) ----------
D('d-lock-empirisme', T, "Quelle est la réponse de Locke à la question « que pouvons-nous savoir ? »",
  "Toutes nos idées viennent de l'expérience (sensation et réflexion). L'esprit est une « table rase » : Locke refuse les idées innées de Descartes, mais garde la distinction entre qualités premières et secondes.",
  { a: ['Locke', 'Descartes'], n: ['la vérité'], o: 'Essai sur l’entendement humain', art: 'Locke', p: '300' }),
D('d-lock-qualites', T, "Qualités premières et qualités secondes chez Locke : quelle différence ?",
  "Les qualités premières (étendue, mouvement) sont constitutives de la matière ; les qualités secondes (sons, couleurs) sont dans notre âme, causées par les objets mais ne leur ressemblent pas. Cela suppose un monde extérieur.",
  { a: ['Locke'], n: ['la science', 'la nature'], o: 'Essai sur l’entendement humain', art: 'Locke', p: '300' }),
D('d-lock-tolerance', T, "Que dit Locke de la tolérance religieuse ?",
  "Chacun est responsable devant Dieu de ce qu'il croit : le pouvoir politique ne peut imposer un culte. Mais pas de tolérance pour l'athéisme, qui dispenserait de toute obligation et romprait le lien social.",
  { a: ['Locke'], n: ['la religion', "l'État"], o: 'Lettre sur la tolérance', art: 'Locke', p: '300' }),
D('d-lock-etat', T, "Comment Locke fonde-t-il l'État et en quoi diffère-t-il de Hobbes ?",
  "L'état de nature reconnaît liberté et propriété (fondée sur le travail) comme droits naturels ; le contrat crée une loi commune qui garantit ces droits, d'où un droit de résistance aux abus. L'État garantit l'état de nature au lieu d'en rompre.",
  { a: ['Locke', 'Hobbes'], n: ["l'État", 'la liberté', 'le travail'], o: 'Deux Traités du gouvernement civil', art: 'Locke', p: '300-301' }),

// ---------- Hume (p. 232-233) ----------
D('d-hume-science-homme', T, "Quel est le projet de Hume et sa méthode ?",
  "Construire une science de la nature humaine à l'image de la physique de Newton, empiriste : l'expérience fonde l'origine, l'association et la validité des idées.",
  { a: ['Hume'], n: ['la science'], o: 'Traité de la nature humaine', art: 'Hume', p: '232' }),
D('d-hume-impressions', T, "Impressions et idées chez Hume : quelle différence ?",
  "Les impressions (de sensation ou de réflexion) sont vives ; les idées en sont des copies moins vives, traces mentales. Une idée n'a de contenu objectif que si on peut la décomposer en expériences sensibles élémentaires.",
  { a: ['Hume'], n: ['la vérité'], art: 'Hume', p: '232' }),
D('d-hume-imagination', T, "Quel rôle Hume donne-t-il à l'imagination ?",
  "Essence de la pensée : elle combine des idées déjà données (montagne d'or), produit les idées générales (nominalisme) et anticipe l'avenir. Elle suit trois principes d'association : ressemblance, contiguïté, causalité.",
  { a: ['Hume'], n: ['la raison', 'le temps'], art: 'Hume', p: '232' }),
D('d-hume-causalite-habitude', T, "D'où vient l'idée de connexion nécessaire entre cause et effet selon Hume ?",
  "De l'habitude, née de la conjonction constante observée (le soleil et la chaleur), qui nous fait attendre l'effet. Ce n'est pas un principe a priori.",
  { a: ['Hume'], n: ['la science', 'le temps'], o: 'Enquête sur l’entendement humain', art: 'Hume', p: '233' }),
D('d-hume-scepticisme', T, "Quel scepticisme Hume défend-il et que critique-t-il ?",
  "Un scepticisme mitigé (académique), non pyrrhonien : la plupart de nos savoirs se résolvent en croyances. La métaphysique (monde, âme, Dieu) relève de fictions de l'imagination : rien n'assure l'existence d'un moi identique.",
  { a: ['Hume'], n: ['la raison', 'la religion', 'la conscience'], art: 'Hume', p: '233' }),

// ---------- Pascal (p. 374-375) ----------
D('d-pasc-homme-divise', T, "Comment Pascal décrit-il la condition humaine dans les Pensées ?",
  "L'homme, « ni ange ni bête », est un être divisé et contradictoire (sens contre raison), en insatisfaction fondamentale. Il faut considérer ensemble sa misère et sa grandeur.",
  { a: ['Pascal'], n: ['le bonheur', 'la raison'], o: 'Pensées', art: 'Pascal', p: '374' }),
D('d-pasc-stoiciens-sceptiques', T, "Quelles erreurs Pascal reproche-t-il aux stoïciens et aux sceptiques ?",
  "Les stoïciens croient le sage capable de posséder la vérité (orgueil) ; les sceptiques (Pyrrhon, Montaigne) jugent toute certitude impossible (désespoir et paresse). Chacun n'aperçoit qu'un versant de la condition humaine.",
  { a: ['Pascal', 'Montaigne'], n: ['la raison', 'la vérité'], o: 'Pensées', art: 'Pascal', p: '374' }),
D('d-pasc-obstacles', T, "Quels obstacles empêchent l'homme de penser à sa misère ?",
  "L'amour-propre (centré sur soi), l'imagination (qui comble le vide de qualités fictives) et le divertissement (se détourner, du jeu ou de la besogne, de la pensée de la mort). Le repos est insupportable.",
  { a: ['Pascal'], n: ['le bonheur', 'le temps'], o: 'Pensées', art: 'Pascal', p: '374-375' }),
D('d-pasc-limites-raison', T, "Quelles sont dignité et limites de la pensée chez Pascal ?",
  "La pensée fait la dignité de l'homme, capable de méditer sa condition. Mais elle est bornée : on ne peut tout définir ni tout démontrer, et l'infini échappe à l'esprit. Le cœur donne le sentiment de Dieu.",
  { a: ['Pascal'], n: ['la raison', 'la religion'], o: "De l'esprit géométrique", art: 'Pascal', p: '375' }),
D('d-pasc-pari', T, "Qu'est-ce que le pari de Pascal, selon le dictionnaire ?",
  "Gager une vie certaine mais finie et misérable contre un bien incertain mais infini : le seul remède aux contradictions de l'existence, après le péché originel qui explique misère et grandeur.",
  { a: ['Pascal'], n: ['la religion'], o: 'Pensées', art: 'Pascal', p: '375' }),

// ---------- Montaigne (p. 337) ----------
D('d-mont-essais', T, "Que sont les Essais de Montaigne ?",
  "Le projet singulier d'un homme de se peindre, devenu monument de culture : introspection mais aussi considérations sur politique, histoire, religion. Ce qui est en jeu : l'avènement d'une raison moderne, libre et critique.",
  { a: ['Montaigne'], n: ['la raison', 'la liberté'], o: 'Essais', art: 'Montaigne', p: '337' }),
D('d-mont-scepticisme', T, "Comment Montaigne ruine-t-il la raison comme source de vérités ?",
  "Dans l'« Apologie de Raymond Sebond », il montre la faiblesse de l'homme comparé à l'instinct animal et son orgueil de discuter Dieu, alors qu'aucune vérité ne fait accord. Son scepticisme dénonce l'impuissance de l'homme à produire une vérité.",
  { a: ['Montaigne'], n: ['la raison', 'la vérité', 'la religion'], o: 'Essais', art: 'Montaigne', p: '337' }),
D('d-mont-modernite', T, "Quelles valeurs modernes Montaigne défend-il ?",
  "Une éducation qui éveille toutes les facultés de l'enfant, l'amitié (La Boétie), le respect des cultures indigènes (le Nouveau Monde vu comme carnage) et la tolérance religieuse. Sa critique de la raison dogmatique ouvre une sagesse raisonnable.",
  { a: ['Montaigne'], n: ['la raison', 'la justice'], o: 'Essais', art: 'Montaigne', p: '337' }),

// ---------- Machiavel (p. 307-308) ----------
D('d-mach-laicisation', T, "En quoi Machiavel rompt-il avec la conception chrétienne du politique ?",
  "Chez Augustin, l'État est la cité terrestre dominée par le péché, au service de l'autorité spirituelle. Machiavel laïcise le politique : institution purement humaine, autonome ; la religion devient un moyen politique parmi d'autres.",
  { a: ['Machiavel', 'Augustin'], n: ["l'État", 'la religion'], o: 'Le Prince', art: 'Machiavel', p: '307-308' }),
D('d-mach-realisme', T, "En quoi consiste le réalisme politique de Machiavel ?",
  "La grande question est de prendre et conserver le pouvoir. L'homme d'État n'a pas à se conformer à une norme morale contraire aux circonstances. Machiavel condamne au nom de la vérité effective toute cité idéale, comme celle de Platon.",
  { a: ['Machiavel', 'Platon'], n: ["l'État", 'le devoir'], o: 'Le Prince', art: 'Machiavel', p: '308' }),
D('d-mach-morale-politique', T, "Machiavel prône-t-il l'immoralisme ?",
  "Pas exactement : morale et politique sont deux domaines distincts. Le prince doit, selon les circonstances, recourir ou non aux moyens moralement condamnables, en ne considérant que le résultat. La valeur ultime est l'unité et la stabilité de l'État.",
  { a: ['Machiavel'], n: ['le devoir', "l'État"], o: 'Le Prince', art: 'Machiavel', p: '308' }),
D('d-mach-fortune', T, "Que désigne la fortune chez Machiavel ?",
  "Le hasard, les circonstances et la matière qui résiste à l'homme politique : elle régit la prospérité ou la ruine des États. L'histoire est cyclique (idée empruntée à Platon), la nature humaine invariable.",
  { a: ['Machiavel'], n: ['le temps', "l'État"], o: 'Le Prince', art: 'Machiavel', p: '308' }),
];
