import { D } from './dsl.mjs';
const T = 'auteur_oeuvre';
export default [
// ---------- Bacon (p. 46-47), Malebranche (p. 312-313), Vico (p. 518-519), Berkeley (p. 55) ----------
D('d-baco-idoles', T, "Que sont les « idoles » chez Bacon et à quoi servent-elles ?",
  "Les obstacles inhérents à l'esprit, à liquider pour devenir attentif aux choses mêmes : la réforme de l'esprit précède la méthode inductive (Novum Organum).",
  { a: ['Bacon'], n: ['la science', 'la vérité'], o: 'Novum Organum', art: 'Bacon (Francis)', p: '46' }),
D('d-baco-induction', T, "Quelle méthode Bacon propose-t-il ?",
  "Une induction fondée sur l'« expérimentation instruite », attentive à ce qui peut invalider les hypothèses ; seules des expériences cruciales vérifient des axiomes toujours discutables. La vérité est « fille du temps ».",
  { a: ['Bacon', 'Popper'], n: ['la science', 'le temps'], o: 'Novum Organum', art: 'Bacon (Francis)', p: '46-47' }),
D('d-male-vision-en-dieu', T, "Qu'est-ce que la vision en Dieu chez Malebranche ?",
  "Dieu a en lui les idées de toutes choses ; c'est en Dieu que nous connaissons et sentons. L'origine de nos idées est entièrement divine, contre empiristes (externe) et innéistes comme Descartes (en nous).",
  { a: ['Malebranche', 'Descartes'], n: ['la religion', 'la vérité'], o: 'De la recherche de la vérité', art: 'Malebranche', p: '312' }),
D('d-male-simplicite-voies', T, "Que veut dire le principe de la simplicité des voies ?",
  "Dieu, s'il crée, produit l'ouvrage le plus parfait, y compris par des moyens simples et généraux : il ne déroge pas aux lois générales pour épargner telle souffrance ou sauver tel pécheur. Il ne veut pas le mal, il le permet.",
  { a: ['Malebranche'], n: ['la religion', 'la nature'], o: 'Traité de la nature et de la grâce', art: 'Malebranche', p: '312-313' }),
D('d-male-occasionnalisme', T, "Qu'est-ce que l'occasionnalisme ?",
  "Dieu est la cause véritable et efficace de toutes choses ; les causes naturelles n'en sont que les causes occasionnelles (le choc est cause occasionnelle du mouvement, dont la cause efficace est la loi divine).",
  { a: ['Malebranche'], n: ['la nature', 'la science'], art: 'Malebranche', p: '312-313' }),
D('d-vico-histoire', T, "Comment Vico réhabilite-t-il l'histoire contre Descartes ?",
  "Les vérités mathématiques sont hypothétiques et abstraites (théorie, non réalité). Dans l'histoire, l'esprit étudie ses propres œuvres : le « monde des nations » devient l'objet d'une « science nouvelle », avec un sens de l'histoire nommé providence.",
  { a: ['Vico', 'Descartes'], n: ['le temps', 'la vérité', 'la science'], o: 'La Science nouvelle', art: 'Vico', p: '518' }),
D('d-vico-trois-ages', T, "Quels sont les trois âges de Vico ?",
  "L'âge des dieux (théocratique, imagination), des héros (domination des nobles) et des hommes (science et philosophie). À chaque âge correspondent coutumes, lois, gouvernements et représentations du monde.",
  { a: ['Vico'], n: ['le temps', "l'État"], o: 'La Science nouvelle', art: 'Vico', p: '519' }),
D('d-vico-rationalisme', T, "En quoi le rationalisme de Vico est-il « élargi » ?",
  "Toutes les cultures et étapes du devenir humain sont des étapes d'une raison concrète, née d'une lente gestation ; la civilisation trouve sa source dans la barbarie. Vico est progressiste et déjà romantique par son attention aux particularismes.",
  { a: ['Vico'], n: ['la raison', 'le temps'], o: 'La Science nouvelle', art: 'Vico', p: '519' }),
D('d-berk-immaterialisme', T, "Que soutient Berkeley avec « esse est percipi » ?",
  "Exister, c'est être perçu ou percevoir : étendue, mouvement, couleur n'existent pas hors de l'idée qu'on en a. La matière comme substance extérieure est un mot creux.",
  { a: ['Berkeley'], n: ['la vérité', 'la conscience'], o: 'Traité sur les principes de la connaissance', art: 'Berkeley', p: '55' }),
D('d-berk-dieu', T, "Quelle est l'origine des perceptions chez Berkeley ?",
  "Puisqu'elles ne viennent pas de la matière, Dieu en est l'unique source : il assure l'ordre de nos idées et la régularité de nos perceptions.",
  { a: ['Berkeley'], n: ['la religion', 'la nature'], art: 'Berkeley', p: '55' }),

// ---------- Montesquieu (p. 338-339), Diderot (p. 131-132) ----------
D('d-mtsq-lois', T, "Que désigne « loi » dans De l'esprit des lois ?",
  "Deux sens : loi-commandement (établie par une autorité) et rapport causal naturel indépendant de la volonté humaine. Ils sont regroupés : les lois sont « les rapports nécessaires qui dérivent de la nature des choses » ; il s'agit de dégager la logique des institutions.",
  { a: ['Montesquieu'], n: ["l'État", 'la justice', 'la nature'], o: "De l'esprit des lois", art: 'Montesquieu', p: '338' }),
D('d-mtsq-gouvernements', T, "Nature et principe des trois gouvernements chez Montesquieu ?",
  "République : vertu (avec modération). Monarchie : honneur (inégalité, lois fixes). Despotisme : crainte (un seul, sans lois). La classification est dualiste : deux régimes modérés, un régime qui ne l'est pas, le mal politique absolu.",
  { a: ['Montesquieu'], n: ["l'État", 'la liberté'], o: "De l'esprit des lois", art: 'Montesquieu', p: '338' }),
D('d-mtsq-separation', T, "Comment Montesquieu conçoit-il la liberté politique ?",
  "Un État est libre quand le pouvoir arrête le pouvoir : séparation des pouvoirs législatif, exécutif, judiciaire, et corps intermédiaires modérant le pouvoir. Il défend ce qu'on appelle un État de droit.",
  { a: ['Montesquieu'], n: ["l'État", 'la liberté', 'la justice'], o: "De l'esprit des lois", art: 'Montesquieu', p: '338-339' }),
D('d-dide-materialisme', T, "Quelle philosophie Diderot défend-il ?",
  "Un monisme matérialiste et athée : le monde est un tout matériel quasi organique, l'engendrement continu du minéral à la pensée (annonce Lamarck). Un seul critère de connaissance : l'expérience.",
  { a: ['Diderot'], n: ['la nature', 'la science', 'la religion'], o: 'Le Rêve de d’Alembert', art: 'Diderot', p: '131-132' }),
D('d-dide-esthetique', T, "Que signifie « suivre la nature » dans l'esthétique de Diderot ?",
  "Le génie imite la nature (physique et humaine) non en la copiant mais en révélant sa vérité profonde. Le beau n'est pas le vrai mais le vraisemblable. Sa morale est universelle, fondée sur les sentiments naturels et la raison.",
  { a: ['Diderot'], n: ["l'art", 'la nature', 'le devoir'], art: 'Diderot', p: '132' }),
];
