import { D } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Notion du bac : le bonheur (p. 60-62) ----------
D('n-bonh-etymologie', N, "Pourquoi le bonheur pose-t-il d'emblée problème ?",
  "Bon heur (augurium, chance) : il arrive sans maîtrise, alors qu'on le définit comme état durable. « Bon » suggère un bien : agréable ou moral ? Est-il le bien suprême, ou surpassé par la justice ou la liberté ?",
  { n: ['le bonheur'], art: 'bonheur (notion du bac)', p: '60' }),
D('n-bonh-souverain-bien', N, "Comment la philosophie antique conçoit-elle le bonheur ?",
  "Comme Souverain Bien, fin suprême en notre pouvoir, dissocié du plaisir éphémère. Il est indissociable d'une vie vertueuse fondée sur la raison (Aristote, Épicure, stoïciens).",
  { a: ['Aristote', 'Épicure'], n: ['le bonheur', 'la raison'], art: 'bonheur (notion du bac)', p: '60' }),
D('n-bonh-aristote-epicure', N, "Comment Aristote se distingue-t-il d'Épicure et des stoïciens sur le bonheur ?",
  "Épicure : régler ses désirs sur la nature ; stoïciens : accepter l'ordre du monde ; conception presque négative (absence de trouble, renoncement). Aristote : bonheur = activité, vertu = aptitude propre à chaque être (celle de l'homme est de penser).",
  { a: ['Aristote', 'Épicure'], n: ['le bonheur'], art: 'bonheur (notion du bac)', p: '60' }),
D('n-bonh-ideal-imagination', N, "Pourquoi Kant dit-il que le bonheur est un idéal de l'imagination ?",
  "Il ne peut faire l'objet d'une définition universelle (éléments empiriques, sensibilité de chacun) et dépend de conditions qui échappent à la volonté. Il ne peut donc être la fin de l'action morale, qui rend seulement digne d'être heureux.",
  { a: ['Kant'], n: ['le bonheur', 'le devoir'], o: 'Fondements de la métaphysique des mœurs', art: 'bonheur (notion du bac)', p: '60' }),
D('n-bonh-citations-antiques', N, "Comment Épicure, Sénèque et Descartes situent-ils le plaisir et le bonheur ?",
  "Épicure : le plaisir est commencement et fin de la vie heureuse. Sénèque : le plaisir doit être compagnon, non guide, d'une volonté droite. Descartes : le plus grand contentement vient du bon usage du libre arbitre.",
  { a: ['Épicure', 'Sénèque', 'Descartes'], n: ['le bonheur', 'la liberté'], art: 'bonheur (notion du bac)', p: '61' }),
D('n-bonh-schopenhauer', N, "Que dit Schopenhauer du rôle de l'activité dans le bonheur ?",
  "L'activité est indispensable au bonheur : le désœuvrement engendre l'ennui, dont seule l'activité préserve.",
  { a: ['Schopenhauer'], n: ['le bonheur', 'le travail'], art: 'bonheur (notion du bac)', p: '61' }),
D('n-bonh-droit', N, "Que signifie le « droit au bonheur » (Saint-Just) ?",
  "« Le bonheur est une idée neuve en Europe » : il renoue avec le paganisme antique en le posant comme un droit. Exigence de justice si l'État délivre du besoin (biens sociaux de base, Rawls) ; utopie dangereuse s'il définit un bonheur commun.",
  { a: ['Rawls'], n: ['le bonheur', 'la justice', "l'État"], art: 'bonheur (notion du bac)', p: '62' }),
D('n-bonh-spinoza', N, "Quelle conclusion le dictionnaire tire-t-il sur le bonheur ?",
  "Il n'est ni un dû ni un don ; il est passif s'il n'est que rêve, mais s'il consiste en l'exercice de la fonction propre et accroît notre puissance, alors, comme Spinoza, il n'est pas de plus grand bonheur que de comprendre et de penser.",
  { a: ['Spinoza'], n: ['le bonheur', 'la raison'], art: 'bonheur (notion du bac)', p: '62' }),

// ---------- Notion du bac : la conscience (p. 95-97) ----------
D('n-cons-definition', N, "Quelle différence entre conscience immédiate et conscience réfléchie ?",
  "La première est la simple présence à soi quand on pense, sent, agit ; la seconde est la capacité de faire retour sur ses pensées ou actions, pour les analyser ou les juger. Dans tous les cas la conscience est conscience de soi : elle fait de l'homme un sujet.",
  { n: ['la conscience'], art: 'conscience (notion du bac)', p: '95' }),
D('n-cons-pascal', N, "Que dit Pascal du roseau pensant ?",
  "L'homme est le plus faible roseau de la nature mais un roseau pensant : la conscience fait à la fois sa misère et sa grandeur.",
  { a: ['Pascal'], n: ['la conscience'], o: 'Pensées', art: 'conscience (notion du bac)', p: '95' }),
D('n-cons-descartes', N, "Pourquoi la conscience devient-elle un problème philosophique chez Descartes ?",
  "Face à la science moderne mécaniste, il soumet tout au doute ; la seule certitude est le cogito. La conscience devient fondement et modèle de toute connaissance : plus facile à connaître que le corps, elle affirme la transparence du sujet à lui-même.",
  { a: ['Descartes'], n: ['la conscience', 'la vérité'], o: 'Méditations métaphysiques', art: 'conscience (notion du bac)', p: '95' }),
D('n-cons-illusions', N, "Quelles critiques adresse-t-on à la transparence de la conscience ?",
  "Spinoza : la conscience ignore les causes, source d'illusions comme le libre arbitre. Nietzsche : la conscience morale exprime des sentiments non moraux. Marx : les idées reflètent la société. Freud : l'inconscient ruine la transparence.",
  { a: ['Spinoza', 'Nietzsche', 'Marx', 'Freud'], n: ['la conscience', "l'inconscient"], art: 'conscience (notion du bac)', p: '95' }),
D('n-cons-behaviorisme', N, "Que soutient le béhaviorisme sur la conscience ?",
  "Il rend compte du comportement comme réponse à des stimuli, indépendants de toute conscience ; pensée comme une « chose », la conscience est pour la psychologie positive une hypothèse inutile.",
  { n: ['la conscience', 'la science'], art: 'conscience (notion du bac)', p: '96-97' }),
D('n-cons-citations', N, "Que retenir des citations de Rousseau, Kant, Hegel et Bergson sur la conscience ?",
  "Rousseau : instinct divin, juge du bien et du mal. Kant : avoir la notion du Je fait la personne. Hegel : penser élève à l'absolu, d'où un conflit douloureux avec nos limites. Bergson : toute conscience est mémoire et anticipation.",
  { a: ['Rousseau', 'Kant', 'Hegel', 'Bergson'], n: ['la conscience', 'le temps'], art: 'conscience (notion du bac)', p: '96' }),
D('n-cons-intentionnalite', N, "Pourquoi Husserl dit-il que la conscience est intentionnalité ?",
  "Même en suspendant tout jugement d'existence (épochê), la conscience se rapporte au monde comme à son objet : elle n'est ni intériorité ni chose mais « rapport à ». Il y a une distance irréductible entre le sujet et l'objet visé, même si c'est lui-même.",
  { a: ['Husserl'], n: ['la conscience', 'le temps'], o: 'Méditations cartésiennes', art: 'conscience (notion du bac)', p: '97' }),
D('n-cons-sens', N, "Que devient la conscience après Husserl selon le dictionnaire ?",
  "Avant d'être instrument de connaissance, elle est donatrice de sens : tout entière hors d'elle-même (ek-stase), orientée vers le passé retenu ou l'avenir visé. Le sens n'est pas donné mais à construire, tâche de Ricœur.",
  { a: ['Husserl', 'Ricœur'], n: ['la conscience', 'le temps'], art: 'conscience (notion du bac)', p: '97' }),
];
