import { D } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Notion du bac : le devoir (p. 126-128) ----------
D('n-dev-contrainte', N, "Le devoir est-il une contrainte ?",
  "Non : il se distingue de la nécessité (on doit manger pour vivre, qu'on le veuille ou non). L'obligation implique la volonté et la liberté de choix (je pourrais ne pas dire la vérité). Mais toute obligation n'est pas un devoir moral.",
  { n: ['le devoir', 'la liberté'], art: 'devoir (notion du bac)', p: '126' }),
D('n-dev-vrai-devoir', N, "À quoi reconnaît-on le véritable devoir selon Kant ?",
  "Il est distinct de tout mobile sensible et indépendant de tout contexte : impératif catégorique, opposé aux impératifs hypothétiques (règles d'habileté, conseils de prudence). Il est exigence désintéressée, motivée par le respect de la loi et de son universalité.",
  { a: ['Kant'], n: ['le devoir'], o: 'Fondements de la métaphysique des mœurs', art: 'devoir (notion du bac)', p: '126' }),
D('n-dev-citations', N, "Que retenir des citations de Spinoza et Rousseau sur le devoir ?",
  "Spinoza : le devoir de l'homme libre est de vivre selon la raison, sa sagesse est méditation de la vie, non de la mort. Rousseau : « soyez humains » est le premier (et le seul) devoir : se conformer à un idéal d'humanité.",
  { a: ['Spinoza', 'Rousseau'], n: ['le devoir'], art: 'devoir (notion du bac)', p: '127' }),
D('n-dev-nietzsche-arendt', N, "Comment Nietzsche et Arendt éclairent-ils le devoir d'obéissance ?",
  "Nietzsche : appeler « Dieu » celui dont on dit qu'il ordonne la soumission transforme la faiblesse en mérite et l'incapacité d'agir en vertu. Arendt : Eichmann déclare qu'il faisait son devoir, en obéissant aux ordres et à la loi, non sans mauvaise foi (il se réclame de Kant).",
  { a: ['Nietzsche', 'Arendt', 'Kant'], n: ['le devoir', 'la justice'], art: 'devoir (notion du bac)', p: '127' }),
D('n-dev-conflits', N, "Quelle limite rencontre la morale kantienne du devoir ?",
  "Les conflits de devoirs : en bioéthique par exemple, on ne peut résoudre les choix a priori par des principes incontestables ; une approche utilitariste l'emporte parfois. Tous les êtres humains sont fins en soi, mais un choix forcé peut faire prioritaire tel malade.",
  { a: ['Kant'], n: ['le devoir', 'la science'], art: 'devoir (notion du bac)', p: '127-128' }),
D('n-dev-responsabilites', N, "Pourquoi les progrès techniques multiplient-ils les conflits de devoirs ?",
  "Ils nous mettent chaque jour en face de nouvelles responsabilités et de nouveaux devoirs plus souvent incompatibles que conciliables (Jonas).",
  { a: ['Jonas'], n: ['le devoir', 'la technique'], art: 'devoir (notion du bac)', p: '128' }),

// ---------- Notion du bac : l'État (p. 166-169) ----------
D('n-etat-definition', N, "Qu'est-ce que l'État, et que suppose cette notion ?",
  "L'ensemble des institutions (politiques, juridiques, militaires, administratives, économiques) qui organisent une société sur un territoire. Elle suppose la permanence du pouvoir (il n'est plus incorporé dans un chef) et la chose publique (res publica).",
  { n: ["l'État"], art: 'État (notion du bac)', p: '166' }),
D('n-etat-legitimite', N, "Comment l'État moderne se prive-t-il de la légitimation religieuse ?",
  "En affirmant son indépendance à l'égard de l'Église (Bodin, La République, 1576), il perd la légitimation traditionnelle. Machiavel, premier penseur d'un État désacralisé, fait dépendre le pouvoir de l'habileté du Prince ; les contractualistes lui donnent un fondement : le pacte social.",
  { a: ['Machiavel', 'Hobbes', 'Locke', 'Rousseau'], n: ["l'État", 'la religion'], art: 'État (notion du bac)', p: '166-168' }),
D('n-etat-citations', N, "Que retenir des citations d'Aristote, Spinoza et Montesquieu sur l'État ?",
  "Aristote : l'homme est naturellement un animal politique. Spinoza : la fin de l'État est la liberté (délivrer de la crainte). Montesquieu : pour qu'on ne puisse abuser du pouvoir, il faut que le pouvoir arrête le pouvoir.",
  { a: ['Aristote', 'Spinoza', 'Montesquieu'], n: ["l'État", 'la liberté'], art: 'État (notion du bac)', p: '167' }),
D('n-etat-weber-marx-alain', N, "Que retenir des citations de Weber, Marx et Alain sur l'État ?",
  "Weber : monopole de la violence physique légitime, instrument nécessaire de l'ordre. Marx : les luttes dans l'État sont des formes illusoires des luttes de classes ; il représente les intérêts de la classe puissante. Alain : le Léviathan est un enfant ou un sauvage.",
  { a: ['Weber', 'Marx', 'Alain'], n: ["l'État", 'la justice'], art: 'État (notion du bac)', p: '167' }),
D('n-etat-contrat', N, "Que partagent les théoriciens du contrat social ?",
  "Les hommes sont naturellement libres et égaux : le pouvoir repose sur leur consentement. Ils renoncent à leur droit naturel d'agir de leur propre chef, contre paix civile, sûreté et liberté autorisée par la loi. Précurseurs de l'État de droit.",
  { a: ['Hobbes', 'Locke', 'Rousseau'], n: ["l'État", 'la liberté', 'la justice'], art: 'État (notion du bac)', p: '168' }),
D('n-etat-locke-hobbes-rousseau', N, "Locke, Hobbes et Rousseau : quelle différence de conception de l'État ?",
  "Locke : État libéral limité, sauvegarde liberté et propriété, sans intervenir en religion ni en économie. Hobbes : absolutisme (pas despotisme), pour assurer la sécurité. Rousseau : synthèse, la volonté générale exprimée par la loi rend l'obéissance compatible avec la liberté.",
  { a: ['Locke', 'Hobbes', 'Rousseau'], n: ["l'État", 'la liberté'], art: 'État (notion du bac)', p: '168' }),
D('n-etat-raison-violence', N, "Hegel voit-il l'État comme raison ? Quelles inquiétudes en découlent ?",
  "Hegel : « réalité de l'Idée morale », la raison en acte. Mais n'est-ce pas un culte de l'État, dont le totalitarisme fut la manifestation ? Bureaucratie et technostructures rendent l'État étranger au citoyen : « le plus froid des monstres froids » (Nietzsche).",
  { a: ['Hegel', 'Nietzsche'], n: ["l'État", 'la raison'], art: 'État (notion du bac)', p: '168' }),
D('n-etat-anarchisme-marxisme', N, "Anarchisme et marxisme : deux critiques de l'État ?",
  "Anarchisme (Bakounine, Proudhon) : l'État est le mal politique absolu, à supprimer. Marxisme : l'État est au service de la classe dominante ; à détruire par la révolution, avec provisoirement la dictature du prolétariat. L'expérience a plutôt produit un État totalitaire hypertrophié.",
  { a: ['Marx'], n: ["l'État", 'la liberté'], art: 'État (notion du bac)', p: '168-169' }),
D('n-etat-cosmopolite', N, "Vers quel État l'évolution actuelle conduit-elle selon le dictionnaire ?",
  "L'État de droit garantit mieux la liberté que les tentatives d'abolition ; l'artificialité de certains États n'entraîne pas leur disparition mais leur internationalisation (communauté internationale). Perspective kantienne : fédération d'États libres et citoyens du monde.",
  { a: ['Kant'], n: ["l'État", 'la justice'], o: 'Vers la paix perpétuelle', art: 'État (notion du bac)', p: '169' }),
];
