import { D } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Notion du bac : l'inconscient (p. 246-249) ----------
D('n-incs-deux-sens', N, "Quels sont les deux sens du mot « inconscient » ?",
  "Négatif : ce qui n'est pas conscient (non-conscient, surtout adjectif ; le substantif est inconscience). Positif : réalité psychique avec son mode de fonctionnement propre, découverte freudienne (surtout substantif). Il n'est un concept qu'avec Freud.",
  { a: ['Freud'], n: ["l'inconscient"], art: 'inconscient (notion du bac)', p: '246-247' }),
D('n-incs-precurseurs', N, "Quels sont les précurseurs de l'inconscient avant Freud ?",
  "Descartes identifie conscience et pensée (pas d'inconscient). Leibniz : petites perceptions. Bergson : l'oubli chasse hors de la conscience ce qui est inutile à l'action. Toujours un inconscient négatif ; seul Nietzsche soutient une pensée inconsciente et impersonnelle (« quelque chose pense »).",
  { a: ['Descartes', 'Leibniz', 'Bergson', 'Nietzsche'], n: ["l'inconscient", 'la conscience'], art: 'inconscient (notion du bac)', p: '247-248' }),
D('n-incs-citations-classiques', N, "Que retenir des citations de Montaigne et Leibniz sur l'inconscient ?",
  "Montaigne : plus je me connais, plus mon étrangeté m'étonne, une part effrayante du psychisme. Leibniz : les petites perceptions font que le présent est chargé du passé et gros de l'avenir ; arrière-plan permanent de la personnalité.",
  { a: ['Montaigne', 'Leibniz'], n: ["l'inconscient", 'le temps'], art: 'inconscient (notion du bac)', p: '247' }),
D('n-incs-premiere-topique', N, "Quelle est la première topique freudienne (vers 1900) ?",
  "Trois instances : inconscient (Ics), préconscient (Pcs), conscient (Cs). Le préconscient est du conscient latent ; l'inconscient, défini positivement et dynamiquement, est séparé du système Pcs-Cs par la censure et résulte d'un refoulement.",
  { a: ['Freud'], n: ["l'inconscient", 'la conscience'], art: 'inconscient (notion du bac)', p: '248' }),
D('n-incs-deuxieme-topique', N, "Quelle est la deuxième topique (à partir de 1920) ?",
  "Ça (pulsions inconscientes, principe de plaisir), moi (principe de réalité, médiateur, autonomie relative) et surmoi (intériorisation inconsciente des interdits sociaux et parentaux). Elle complète la première sans l'annuler.",
  { a: ['Freud'], n: ["l'inconscient"], o: 'Le Moi et le Ça', art: 'inconscient (notion du bac)', p: '248' }),
D('n-incs-freud-citations', N, "Que retenir des deux citations de Freud du dictionnaire ?",
  "L'hypothèse de l'inconscient est nécessaire et légitime : elle seule ordonne les actes psychiques. L'interprétation des rêves, représentation de désirs refoulés, est la voie royale de la connaissance de l'inconscient.",
  { a: ['Freud'], n: ["l'inconscient"], o: "L'Interprétation du rêve", art: 'inconscient (notion du bac)', p: '247' }),
D('n-incs-liberte', N, "L'inconscient supprime-t-il la liberté ?",
  "Alain réduit l'inconscient à la partie animale et instinctive ; Sartre le ramène à la mauvaise foi (la censure doit connaître ce qu'elle refoule). Mais l'inconscient est le résultat de l'histoire du sujet, qui peut se le réapproprier par le travail analytique : « Là où était du ça, doit advenir du moi ».",
  { a: ['Alain', 'Sartre', 'Freud'], n: ["l'inconscient", 'la liberté'], art: 'inconscient (notion du bac)', p: '247-249' }),

// ---------- Notion du bac : la justice (p. 270-272) ----------
D('n-just-vertu-globale', N, "La justice est-elle une vertu ou une organisation harmonieuse ?",
  "Les deux selon Platon : principe qui maintient chaque instance à sa place et l'harmonie de l'ensemble, dans la cité (magistrats, guerriers, artisans) comme dans l'âme (raison, thumos, epithumia). Vertu globale : à chaque partie sa place, selon son essence.",
  { a: ['Platon'], n: ['la justice'], o: 'République', art: 'justice (notion du bac)', p: '270' }),
D('n-just-biblique', N, "Comment la tradition biblique (Augustin) élargit-elle la justice ?",
  "Aux rapports entre l'homme et Dieu : plus que le respect du bon droit, elle va au-delà du dû (Matthieu 20) et réside dans la pureté intérieure sanctifiée par la grâce. Ricœur étudie la dialectique entre la logique de surabondance (amour) et d'équivalence (justice).",
  { a: ['Augustin', 'Ricœur'], n: ['la justice', 'la religion'], art: 'justice (notion du bac)', p: '270-272' }),
D('n-just-citations', N, "Que retenir des citations de Socrate, Hobbes et Pascal sur la justice ?",
  "Socrate : mieux vaut subir l'injustice que la commettre. Hobbes : sans pouvoir commun, pas de loi, donc pas d'injustice ; la loi instaure le juste. Pascal : ne pouvant faire que le juste soit fort, on a fait que le fort soit juste.",
  { a: ['Platon', 'Hobbes', 'Pascal'], n: ['la justice', "l'État"], art: 'justice (notion du bac)', p: '271' }),
D('n-just-rousseau-alain', N, "Que retenir des citations de Rousseau et d'Alain sur la justice ?",
  "Rousseau : le citoyen consent à toutes les lois, même à celles qui le punissent, la voix du plus grand nombre obligeant tous (contrat social). Alain : est juste d'accepter d'avance l'arbitrage, non l'arbitrage juste.",
  { a: ['Rousseau', 'Alain'], n: ['la justice', "l'État"], art: 'justice (notion du bac)', p: '271' }),
D('n-just-aristote', N, "Quelles formes de justice Aristote distingue-t-il ?",
  "Justice générale ou légale (utilité commune de la cité) et particulière (bien des particuliers) : commutative (transactions, égalité), distributive (proportion aux mérites), corrective (punit les infractions). Objet : un juste milieu fondé sur l'égalité.",
  { a: ['Aristote'], n: ['la justice', 'le devoir'], o: 'Éthique à Nicomaque', art: 'justice (notion du bac)', p: '272' }),
D('n-just-equite', N, "Quel double principe repose sous la justice, et comment Rawls le reprend-il ?",
  "Égalité (la loi est la même pour tous) et équité (à chacun son dû). Rawls, fidèle à Aristote, donne la prééminence à la justice sur l'efficacité ; deux principes : libertés égales pour tous, inégalités acceptables si avantageuses pour chacun et attachées à des positions ouvertes.",
  { a: ['Rawls', 'Aristote'], n: ['la justice', 'la liberté'], o: 'Théorie de la justice', art: 'justice (notion du bac)', p: '272' }),
];
