import { D } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Notion du bac : le langage (p. 285-288) ----------
D('n-lang-sens', N, "Langage, langue, parole : quelles distinctions ?",
  "Le langage est la faculté de constituer un système de signes (au sens large, tout système d'expression ; au sens strict, institution universelle propre à l'homme). La langue est l'instrument d'une communauté. La parole est l'acte individuel qui exerce la fonction linguistique.",
  { n: ['le langage'], art: 'langage (notion du bac)', p: '285' }),
D('n-lang-propre-homme', N, "Le langage est-il le propre de l'homme ?",
  "Descartes : les bêtes ne parlent pas faute de pensée, non faute d'organes. Aujourd'hui on insiste sur le caractère historique et social du langage et sur des activités prélinguistiques de l'enfant ; Benveniste distingue communication animale et langage humain.",
  { a: ['Descartes'], n: ['le langage', 'la raison'], art: 'langage (notion du bac)', p: '285' }),
D('n-lang-double-articulation', N, "Qu'est-ce que la double articulation du langage ?",
  "Première articulation : unités de sens et de sons (monèmes). Seconde : quelques dizaines de phonèmes en nombre fini. Avec une quarantaine de sons, on forme un nombre quasi illimité d'énoncés en épargnant la mémoire.",
  { n: ['le langage', 'la science'], art: 'langage (notion du bac)', p: '285-287' }),
D('n-lang-citations', N, "Que retenir des citations de Descartes, Rousseau, Freud et Bergson sur le langage ?",
  "Descartes : tout homme invente des signes, les bêtes n'ont pas de pensée. Rousseau : le plus énergique est le signe qui a tout dit avant qu'on parle. Freud : la parole est à l'origine un charme magique. Bergson : les mots sont des étiquettes qui font écran aux choses singulières.",
  { a: ['Descartes', 'Rousseau', 'Freud', 'Bergson'], n: ['le langage'], art: 'langage (notion du bac)', p: '286' }),
D('n-lang-saussure-wittgenstein', N, "Que retenir de Saussure et Wittgenstein (citations) sur le langage ?",
  "Saussure : la langue est comme une feuille de papier, la pensée le recto et le son le verso : impossible de séparer les idées des mots. Wittgenstein (Tractatus) : ce dont on ne peut parler, il faut le taire ; bien des problèmes sont sans sens.",
  { a: ['Wittgenstein'], n: ['le langage', 'la vérité'], art: 'langage (notion du bac)', p: '286' }),
D('n-lang-systeme', N, "Pourquoi Saussure compare-t-il la langue à un jeu d'échecs ?",
  "Comme un système d'éléments interdépendants qui se soutiennent mutuellement et ne se comprennent pas isolément (circularité de la signification dans un dictionnaire).",
  { n: ['le langage'], o: 'Cours de linguistique générale', art: 'langage (notion du bac)', p: '287' }),
D('n-lang-pragmatique', N, "Quelle dimension pragmatique du langage Wittgenstein et Austin font-ils apparaître ?",
  "Wittgenstein : les jeux de langage, pratiques collectives aux règles propres ; le langage n'est pas privé. Austin : les énoncés performatifs sont des actes (je lègue ma fortune) qui produisent des effets, avec des conditions d'accomplissement.",
  { a: ['Wittgenstein'], n: ['le langage', 'la vérité'], o: 'Quand dire, c’est faire', art: 'langage (notion du bac)', p: '287' }),
D('n-lang-pouvoir-mots', N, "Quel pouvoir des mots Platon redoute-t-il ?",
  "Dans le Gorgias, il met en garde contre la rhétorique pratiquée par politiciens opportunistes et sophistes. Aujourd'hui, la communication réactualise ce risque de détournement des mots à des fins personnelles ou violentes, qui menace le dialogue et la pensée.",
  { a: ['Platon'], n: ['le langage', 'la justice'], o: 'Gorgias', art: 'langage (notion du bac)', p: '287' }),

// ---------- Notion du bac : la liberté (p. 296-298) ----------
D('n-lib-contrainte', N, "Quel est le sens usuel et originel de la liberté ?",
  "Ne pas être empêché de faire ce que l'on veut, absence de contrainte étrangère. Pour les Anciens, condition de qui n'est ni esclave ni prisonnier : d'abord un statut social et politique. Arendt : sans vie publique garantie, la liberté n'a pas de « réalité mondaine ».",
  { a: ['Arendt'], n: ['la liberté', "l'État"], art: 'liberté (notion du bac)', p: '296' }),
D('n-lib-stoiciens', N, "Comment les stoïciens conçoivent-ils la liberté ?",
  "Comme indépendance intérieure : le sage se détache de ce qui n'est pas en son pouvoir, maîtrise ses passions et comprend la nature. Cela suppose que la liberté ne soit que l'autre nom de la raison, d'où (Spinoza) son identification à la nécessité.",
  { a: ['Spinoza'], n: ['la liberté', 'la raison'], art: 'liberté (notion du bac)', p: '296' }),
D('n-lib-descartes-sartre', N, "Comment Descartes et Sartre conçoivent-ils la liberté ?",
  "Descartes : l'indifférence est le plus bas degré ; la vraie liberté est adhésion de la volonté éclairée par la connaissance du bien. Sartre : libre arbitre originel et créateur, absolue responsabilité.",
  { a: ['Descartes', 'Sartre'], n: ['la liberté'], art: 'liberté (notion du bac)', p: '296' }),
D('n-lib-loi', N, "Pourquoi n'y a-t-il pas de liberté sans loi (Rousseau, Kant, Montesquieu) ?",
  "Si chacun fait ce qui lui plaît, on fait ce qui déplaît à d'autres. La loi limite mais conditionne la liberté : autonomie, obéir à la loi qu'on se prescrit (volonté générale, loi morale). Montesquieu : pouvoir faire ce que l'on doit vouloir.",
  { a: ['Rousseau', 'Kant', 'Montesquieu'], n: ['la liberté', "l'État"], art: 'liberté (notion du bac)', p: '296' }),
D('n-lib-citations', N, "Que retenir des citations sur la liberté (Épictète, Spinoza, Sartre) ?",
  "Épictète : aucun tyran ne peut m'ôter ma pensée ni ma liberté. Spinoza : la liberté du libre arbitre est illusion, ignorance des causes. Sartre : condamné à être libre, l'explication déterministe cherche vainement à fuir la liberté.",
  { a: ['Épictète', 'Spinoza', 'Sartre'], n: ['la liberté'], art: 'liberté (notion du bac)', p: '297' }),
D('n-lib-rousseau-kant-montesquieu', N, "Que retenir des citations de Montesquieu, Rousseau et Kant sur la liberté ?",
  "Montesquieu : le droit de faire tout ce que les lois permettent. Rousseau : renoncer à sa liberté, c'est renoncer à sa qualité d'homme ; un pacte de servitude est nul. Kant : la loi morale est l'autonomie de la raison pure pratique, c'est-à-dire la liberté.",
  { a: ['Montesquieu', 'Rousseau', 'Kant'], n: ['la liberté', 'le devoir'], art: 'liberté (notion du bac)', p: '297' }),
D('n-lib-negative-positive', N, "Quelle différence entre liberté négative et liberté positive (Constant, Berlin) ?",
  "Anciens : participation active à la vie publique ; Modernes : indépendance individuelle, protection des intérêts privés (Constant). Berlin : liberté négative (absence d'entrave) contre positive (prendre part aux décisions). Aron : la seule liberté fondamentale est « ne pas être empêché de ».",
  { a: ['Aron'], n: ['la liberté', "l'État"], o: 'Deux concepts de liberté', art: 'liberté (notion du bac)', p: '298' }),
];
