import { D } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Notion du bac : la nature (p. 349-351) ----------
D('n-nat-sens', N, "Quels sens du mot nature faut-il distinguer ?",
  "Ce qui existe indépendamment de l'homme et du monde humanisé ; le principe de développement autonome d'un être vivant ; la nature humaine (commune à tous) ou la nature d'une personne (tempérament, dispositions innées, opposées à l'acquis). Natura vient de nascor, « naître ».",
  { n: ['la nature'], art: 'nature (notion du bac)', p: '349' }),
D('n-nat-aristote', N, "Comment Aristote définit-il la nature par analogie avec le travail ?",
  "La nature (phusis) est un principe de mouvement et de repos ; les êtres naturels portent en eux-mêmes ce principe, comme l'artisan est cause des objets fabriqués, dont le principe est extérieur. Autonomie locomotrice, croissance et déclin en relèvent.",
  { a: ['Aristote'], n: ['la nature', 'le travail'], o: 'Physique', art: 'nature (notion du bac)', p: '349' }),
D('n-nat-descartes', N, "Quelle conception de la nature découle du mécanisme de Descartes ?",
  "La technique est le modèle de la nature : animaux-machines, physiologie de tuyaux et de ressorts, Dieu artisan parfait. Connaître les lois, c'est dominer la nature : « maîtres et possesseurs de la nature ». Seul l'homme poursuit des fins.",
  { a: ['Descartes'], n: ['la nature', 'la technique', 'la science'], o: 'Discours de la méthode', art: 'nature (notion du bac)', p: '349' }),
D('n-nat-rousseau', N, "Pourquoi Rousseau fait-il de la nature une notion critique ?",
  "La domination de la nature n'augmente pas notre bonheur ni notre liberté ; l'homme l'a transformée jusqu'à la rendre méconnaissable. La nature est une origine perdue que la raison reconstitue et qui sert de modèle pour dénoncer les errements des individus et de la société.",
  { a: ['Rousseau'], n: ['la nature', 'la liberté'], o: "Discours sur l'origine de l'inégalité", art: 'nature (notion du bac)', p: '349' }),
D('n-nat-citations', N, "Que retenir des citations sur la nature (Aristote, Pascal, Hume) ?",
  "Aristote : l'être naturel possède en lui le principe de son mouvement, contrairement au produit de l'art. Pascal : l'homme est un milieu entre rien et tout. Hume : si l'on juge naturel ce qui est habituel, la vertu héroïque est aussi peu naturelle que la barbarie.",
  { a: ['Aristote', 'Pascal', 'Hume'], n: ['la nature'], art: 'nature (notion du bac)', p: '350' }),
D('n-nat-rousseau-kant-jonas', N, "Que retenir des citations de Rousseau, Kant et Jonas sur la nature ?",
  "Rousseau : la pitié, mouvement de la nature, fonde les vertus sociales. Kant : la nature n'est qu'un ensemble de phénomènes, ordonnés par nous. Jonas : la nature menacée lance un appel muet à sa préservation, nouvel objet de la responsabilité.",
  { a: ['Rousseau', 'Kant', 'Jonas'], n: ['la nature', 'le devoir'], art: 'nature (notion du bac)', p: '350' }),
D('n-nat-ecologie', N, "Qu'apporte l'écologie à la réflexion sur la nature ?",
  "La connaissance de la nature libère (Lucrèce : contre les chimères surnaturelles) mais rappelle aussi les limites du pouvoir de l'homme ; elle impose une réforme de l'éthique (Jonas).",
  { a: ['Lucrèce', 'Jonas'], n: ['la nature', 'la science', 'la technique'], art: 'nature (notion du bac)', p: '351' }),

// ---------- Notion du bac : la raison (p. 418-420) ----------
D('n-rais-sens', N, "Que signifie « raison » ?",
  "Bon sens, faculté de connaître, de juger (distinguer le vrai et le faux, Descartes) et de déterminer sa conduite, mais aussi motif ou cause. Ratio : « calcul ». Distincte des sens et de la révélation ; pour tous les philosophes, elle est le propre de l'homme (langage, pensée, connaissance, moralité).",
  { a: ['Descartes'], n: ['la raison'], art: 'raison (notion du bac)', p: '418' }),
D('n-rais-concepts', N, "Quelle est la fonction de la raison comme faculté de combiner des jugements ?",
  "Former concepts et jugements, organiser les connaissances en systèmes et donner un sens à l'Univers en y introduisant de l'ordre. Elle s'oppose à la sensibilité et à la foi, qui répond à la question du sens dans l'ordre de la croyance.",
  { n: ['la raison', 'la vérité'], art: 'raison (notion du bac)', p: '418' }),
D('n-rais-principe-raison', N, "Qu'énonce le principe de raison suffisante de Leibniz ?",
  "Rien n'arrive sans qu'il y ait une cause, ou du moins une raison déterminante qui puisse rendre raison a priori pourquoi cela existe et pourquoi ainsi plutôt qu'autrement : sommet de la tendance de la raison à « rendre raison » du monde.",
  { a: ['Leibniz'], n: ['la raison'], art: 'raison (notion du bac)', p: '418' }),
D('n-rais-pure', N, "Que veut dire Kant en parlant de raison pure, à la fois théorique et pratique ?",
  "Pure car a priori : elle fournit les principes de la connaissance et ceux qui règlent l'action. Il n'y a pas deux raisons mais deux usages d'une faculté unique (connaissance, morale). Elle seule, non l'entendement, peut postuler liberté, immortalité et Dieu.",
  { a: ['Kant'], n: ['la raison', 'le devoir'], art: 'raison (notion du bac)', p: '418' }),
D('n-rais-hegel', N, "Que veut dire Hegel par « la raison gouverne le monde » ?",
  "Tout ce qui arrive a un sens, celui du progrès de la raison ; un Esprit supérieur guide le cours des choses. Les passions sont une « ruse de la raison » : elles servent à réaliser des fins rationnelles (progrès de la liberté, État mondial rationnel).",
  { a: ['Hegel'], n: ['la raison', 'le temps', 'la liberté'], o: "La Raison dans l'histoire", art: 'raison (notion du bac)', p: '418-420' }),
D('n-rais-citations', N, "Que retenir des citations de Thomas d'Aquin, Descartes, Pascal sur la raison ?",
  "Thomas : l'homme est libre parce qu'il est doué de raison. Descartes : le bon sens est également réparti, il faut une méthode. Pascal : la dernière démarche de la raison est de reconnaître qu'une infinité de choses la dépasse.",
  { a: ['Thomas d’Aquin', 'Descartes', 'Pascal'], n: ['la raison', 'la liberté'], art: 'raison (notion du bac)', p: '419' }),
D('n-rais-spinoza-kant-nietzsche', N, "Que retenir des citations de Spinoza, Kant et Nietzsche sur la raison ?",
  "Spinoza : les hommes s'accordent nécessairement en tant qu'ils vivent sous la conduite de la raison. Kant : la raison se pose des questions qu'elle ne peut éviter ni résoudre. Nietzsche : la raison elle-même n'est pas toujours rationnelle.",
  { a: ['Spinoza', 'Kant', 'Nietzsche'], n: ['la raison'], art: 'raison (notion du bac)', p: '419' }),
];
