import { D } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Notion du bac : la religion (p. 426-428) ----------
D('n-reli-etymologie', N, "Quelles sont les deux étymologies de « religion » et que révèlent-elles ?",
  "Relegere, « relire » (Cicéron : comprendre le sens des rites) ; religare, « relier » (Augustin : ce qui unit à Dieu). Double aspect : piété (religion dynamique, Bergson) et pratique rituelle institutionnalisée (religion statique). Un aspect subjectif (foi) et objectif (cérémonies, Église).",
  { a: ['Cicéron', 'Augustin', 'Bergson'], n: ['la religion'], art: 'religion (notion du bac)', p: '426' }),
D('n-reli-sacre-profane', N, "Quelle unité trouve-t-on derrière la diversité des religions (Durkheim) ?",
  "L'opposition entre le sacré et le profane : le profane est la réalité ordinaire, le sacré concentre toute la signification du réel, ambivalent. C'est la « forme élémentaire de la vie religieuse ». Un monde entièrement profane serait irréligieux ; les sociétés laïcisées gardent des résidus de religiosité.",
  { a: ['Durkheim'], n: ['la religion'], art: 'religion (notion du bac)', p: '426' }),
D('n-reli-foi', N, "Qu'est-ce que la foi et quels rapports a-t-elle avec la raison ?",
  "Confiance (fides) : le fidèle s'en remet à Dieu, puissance infinie, devant des vérités mystérieuses au-delà de la raison (« vérités du cœur » de Pascal). Les rapports oscillent entre hostilité et collaboration (Anselme, Thomas : philosophie au service de la théologie). Le Dieu de la religion n'est pas celui des philosophes (Pascal).",
  { a: ['Pascal', 'Anselme', 'Thomas d’Aquin', 'Kierkegaard'], n: ['la religion', 'la raison'], art: 'religion (notion du bac)', p: '427-428' }),
D('n-reli-citations', N, "Que retenir des citations sur la religion (Augustin, Descartes, Spinoza) ?",
  "Augustin : la faim de l'âme ne peut être comblée que par Dieu. Descartes : la foi est un acte de la volonté, non de l'intelligence. Spinoza : croire que Dieu a tout fait pour l'homme détruit sa perfection, car agir en vue d'une fin suppose un manque.",
  { a: ['Augustin', 'Descartes', 'Spinoza'], n: ['la religion'], art: 'religion (notion du bac)', p: '427' }),
D('n-reli-kant-kierkegaard-marx', N, "Que retenir des citations de Kant, Kierkegaard et Marx sur la religion ?",
  "Kant : deux religions, celle du culte qui quémande des faveurs et la religion morale de la bonne conduite. Kierkegaard : la foi donne à l'angoisse une valeur éducative absolue. Marx : le communisme commence avec l'athéisme (réappropriation de l'essence humaine).",
  { a: ['Kant', 'Kierkegaard', 'Marx'], n: ['la religion', 'le devoir'], art: 'religion (notion du bac)', p: '427' }),
D('n-reli-lumieres', N, "Comment le rationalisme classique et les Lumières traitent-ils la religion ?",
  "Descartes et Spinoza ne récusent pas la foi mais affirment l'autonomie de la raison (la foi concerne le salut, la vérité relève de la raison). Les Lumières développent athéisme, matérialisme, hostilité à la révélation et aux dogmes tenus pour superstitions (religion naturelle).",
  { a: ['Descartes', 'Spinoza'], n: ['la religion', 'la raison'], art: 'religion (notion du bac)', p: '428' }),
D('n-reli-alienation', N, "Que disent Marx, Feuerbach, Nietzsche et Freud de la religion ?",
  "Marx : opium du peuple, illusion à signification anthropologique (aliénation, frustrations sociales). Feuerbach : Dieu est la projection des aspirations humaines. Nietzsche : pulsions morbides et culpabilité du péché. Freud : « névrose obsessionnelle de l'humanité ».",
  { a: ['Marx', 'Feuerbach', 'Nietzsche', 'Freud'], n: ['la religion'], art: 'religion (notion du bac)', p: '428' }),
D('n-reli-reduction', N, "Quelle limite commune aux interprétations réductrices de la religion ?",
  "Toutes font de la religion le symptôme d'autre chose (oppression sociale, domination du négatif, souvenir traumatique) et exclusives les unes des autres ; elles négligent la diversité du phénomène et sous-estiment la valeur spirituelle de l'expérience religieuse.",
  { n: ['la religion'], art: 'religion (notion du bac)', p: '428' }),

// ---------- Notion du bac : la science (p. 451-453) ----------
D('n-scie-sens', N, "Comment les Grecs et les Modernes conçoivent-ils la science ?",
  "Grecs : épistêmê, connaissance éminente, universelle et théorique (la philosophie est la science suprême). Modernes : connaissance scientifique positive, expérimentale, avec des critères de vérification garantissant l'objectivité.",
  { a: ['Aristote'], n: ['la science'], art: 'science (notion du bac)', p: '451' }),
D('n-scie-demarcation', N, "Quels sont les problèmes de la philosophie des sciences ?",
  "Démarcation (Popper : contrôle par les faits ; ainsi la philosophie n'est pas une science), unité de la science (unité de méthode, multiplicité des objets), classification (Comte). L'unité de méthode ne concerne que les sciences expérimentales.",
  { a: ['Popper', 'Comte'], n: ['la science', 'la vérité'], art: 'science (notion du bac)', p: '451' }),
D('n-scie-trois-types', N, "Quels trois types de sciences distingue-t-on ?",
  "Expérimentales (objets donnés dans l'expérience, contrôle expérimental) ; formelles (mathématiques et logique, déduction à partir d'axiomes, sans vérification expérimentale) ; humaines (statut controversé : positivisme ou, avec Dilthey, sciences de l'esprit fondées sur l'interprétation).",
  { a: ['Dilthey', 'Comte'], n: ['la science', 'la raison'], art: 'science (notion du bac)', p: '452-453' }),
D('n-scie-citations', N, "Que retenir des citations d'Aristote, Locke, Kant sur la science ?",
  "Aristote : la science passe d'un étonnement à un autre (ouverture d'esprit). Locke : l'expérience est le fondement de toutes nos connaissances. Kant : l'expérience dit ce qui est, non que cela ne puisse être autrement ; la nécessité des lois doit être démontrée.",
  { a: ['Aristote', 'Locke', 'Kant'], n: ['la science', 'la vérité'], art: 'science (notion du bac)', p: '452' }),
D('n-scie-heidegger-bachelard-popper', N, "Que retenir des citations de Heidegger, Bachelard et Popper sur la science ?",
  "Heidegger : « la science ne pense pas » : la réflexion philosophique n'est pas de son ressort. Bachelard : on ne fonde rien sur l'opinion, il faut d'abord la détruire. Popper : une théorie irréfutable n'est pas scientifique ; aucune n'est définitive.",
  { a: ['Heidegger', 'Bachelard', 'Popper'], n: ['la science', 'la vérité'], art: 'science (notion du bac)', p: '452' }),
];
