import { D } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Notion du bac : la technique (p. 487-489) ----------
D('n-tech-definition', N, "Qu'est-ce que la technique et en quoi diffère-t-elle de l'art ?",
  "Tekhnê : savoir-faire permettant d'obtenir volontairement un résultat déterminé (issu de l'expérience, de règles codifiées ou d'un savoir scientifique). À la différence de l'art, à finalité esthétique désintéressée, la technique vise l'utilité et l'efficacité.",
  { n: ['la technique', "l'art"], art: 'technique (notion du bac)', p: '487' }),
D('n-tech-humanite', N, "Pourquoi la technique est-elle un critère d'humanité ?",
  "La fabrication d'outils suppose de se représenter l'action, la forme et les matériaux : comme le langage, la technique est indissociable de la pensée (Leroi-Gourhan). L'outil, prolongement du corps, médiatise notre rapport à la nature et contribue à nous rendre « maîtres et possesseurs de la nature » (Descartes).",
  { a: ['Descartes', 'Aristote'], n: ['la technique', 'la nature'], art: 'technique (notion du bac)', p: '487' }),
D('n-tech-poiesis', N, "Comment les Anciens et les Modernes ont-ils pensé la technique ?",
  "Les Anciens la dévalorisent (poiêsis) au profit de la praxis (action morale, politique) et de la theôria (contemplation). Aux XVIIIe-XIXe siècles, on l'a peu pensée pour elle-même, au nom de la neutralité des outils, tout en déplorant l'impuissance devant les machines (Arendt).",
  { a: ['Arendt'], n: ['la technique', 'le travail'], art: 'technique (notion du bac)', p: '487' }),
D('n-tech-ambivalence', N, "La technique est-elle neutre ?",
  "Non (Marx) : maîtrisée par une minorité, elle peut servir de domination sur la majorité (aliénation des travailleurs). Simondon en propose une pensée positive : l'homme est coordinateur et inventeur des machines, l'objet technique est médiateur entre l'humanité et le monde.",
  { a: ['Marx', 'Simondon'], n: ['la technique', 'le travail'], art: 'technique (notion du bac)', p: '487' }),
D('n-tech-citations', N, "Que retenir des citations d'Aristote, Descartes, Hegel sur la technique ?",
  "Aristote : ce n'est pas parce qu'il a des mains que l'homme est le plus intelligent, mais parce qu'il est le plus intelligent qu'il a des mains. Descartes : les métiers permettraient de devenir maîtres de la nature. Hegel : l'outil, production de l'Esprit, est plus haut qu'une chose de la nature.",
  { a: ['Aristote', 'Descartes', 'Hegel'], n: ['la technique'], art: 'technique (notion du bac)', p: '488' }),
D('n-tech-bergson-heidegger-jonas', N, "Que retenir des citations de Bergson, Heidegger et Jonas sur la technique ?",
  "Bergson : l'intelligence est la faculté de fabriquer des objets artificiels, des outils à faire des outils. Heidegger : la technique déracine l'homme et impose une vision utilitaire de la nature. Jonas : la promesse de la technique s'est inversée en menace.",
  { a: ['Bergson', 'Heidegger', 'Jonas'], n: ['la technique', 'la nature'], art: 'technique (notion du bac)', p: '488' }),
D('n-tech-vigilance', N, "Quelle attitude la réflexion contemporaine adopte-t-elle face à la technique ?",
  "L'inquiétude devant son caractère « impérieux et conquérant » (Heidegger) et, avec Jonas, l'idée d'une éthique de la responsabilité et d'une heuristique de la peur. La maîtrise de l'avenir passe moins par des machines plus complexes que par une réflexion vigilante sur la technique (Ellul).",
  { a: ['Heidegger', 'Jonas'], n: ['la technique', 'le devoir'], art: 'technique (notion du bac)', p: '489' }),

// ---------- Notion du bac : le temps (p. 490-492) ----------
D('n-temp-cycle-ligne', N, "Temps cyclique et temps linéaire : quels enjeux ?",
  "Mythe et religion nient l'irréversibilité en représentant le temps comme cycle (roue des générations, mythe d'Er de Platon) ou éternité. Le cycle ferme l'avenir comme champ de la liberté ; reconnaître la spécificité du temps, c'est accepter l'irréversibilité, qui ouvre le présent à la liberté.",
  { a: ['Platon'], n: ['le temps', 'la liberté'], art: 'temps (notion du bac)', p: '490' }),
D('n-temp-subjectif-objectif', N, "Temps vécu et temps de la science : quelle opposition ?",
  "Le temps de la science est mesurable, quantifiable, homogène, objectif mais existe pour personne ; le temps vécu (« sentiment intérieur de la durée », Bergson) est qualitatif, hétérogène, subjectif. Le chapelier d'Alice : « le temps est une personne ».",
  { a: ['Bergson'], n: ['le temps', 'la science'], art: 'temps (notion du bac)', p: '490-492' }),
D('n-temp-citations-1', N, "Que retenir des citations d'Augustin, Kant, Hegel sur le temps ?",
  "Augustin : je sais ce qu'est le temps tant qu'on ne me le demande pas. Kant : il est la forme réelle de l'intuition intérieure, soumise à la succession. Hegel : le temps est l'être qui, en étant, n'est pas ; passage de l'être au néant, devenir.",
  { a: ['Augustin', 'Kant', 'Hegel'], n: ['le temps'], art: 'temps (notion du bac)', p: '491' }),
D('n-temp-citations-2', N, "Que retenir des citations de Nietzsche, Bergson, Levinas sur le temps ?",
  "Nietzsche : ne pouvoir détruire le temps est la détresse du vouloir (ressentiment). Bergson : la durée est le progrès du passé qui ronge l'avenir. Levinas : l'avenir, c'est l'autre ; le temps ouvre au face-à-face avec autrui.",
  { a: ['Nietzsche', 'Bergson', 'Levinas'], n: ['le temps'], art: 'temps (notion du bac)', p: '491' }),
D('n-temp-histoire-mesure', N, "Le temps mesuré a-t-il une histoire ?",
  "Oui : dans l'Antiquité, l'heure varie selon les saisons ; au Moyen Âge, le temps appartient à Dieu et suit la vie religieuse ; à la fin du XIVe siècle, les instruments de mesure se diffusent pour régler le travail (Le Goff). Le temps réglé est le résultat de l'évolution des rapports de l'homme au monde.",
  { n: ['le temps', 'le travail'], art: 'temps (notion du bac)', p: '492' }),
D('n-temp-temporalite', N, "Que devient le temps chez Kant puis dans les philosophies de l'existence ?",
  "Kant : non une propriété des choses mais une forme a priori de la sensibilité. Heidegger (Dasein), Sartre (réalité humaine) pensent l'existence sur fond de temporalité. Le temps n'est ni ce que mesure la science ni le seul ressenti : un système de relations entre temporalités multiples et hétérogènes.",
  { a: ['Kant', 'Heidegger', 'Sartre'], n: ['le temps', 'la conscience'], art: 'temps (notion du bac)', p: '492' }),
];
