import { D } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Notion du bac : le travail (p. 503-505) ----------
D('n-trav-definition', N, "Quel est le point commun de tous les travaux ?",
  "Non la rémunération, mais le but : transformer la nature dans un sens utile à l'homme, pour satisfaire ses besoins. Cela le distingue du jeu et des loisirs, activités désintéressées. Chez les Grecs, il est le fait des esclaves et des producteurs, non de l'homme d'action, du politique ou du philosophe.",
  { n: ['le travail', 'la nature'], art: 'travail (notion du bac)', p: '503' }),
D('n-trav-arendt', N, "Pourquoi Arendt voit-elle dans le travail l'activité la plus proche de l'animalité ?",
  "Reprenant theôria, praxis, poiêsis, elle note que sa finalité (satisfaire les besoins) est biologique et que ses produits sont destinés à être consommés : répétition monotone du cycle production-consommation.",
  { a: ['Arendt'], n: ['le travail', 'la nature'], o: "Condition de l'homme moderne", art: 'travail (notion du bac)', p: '503' }),
D('n-trav-malediction', N, "Le travail est-il une malédiction ?",
  "Il est peine : la Genèse (« à la sueur de ton front »), nostalgie du paradis ou de l'état de nature (Rousseau), étymologie de tripalium (instrument de contrainte). Il résulte d'une lutte entre l'homme et un environnement primitivement hostile.",
  { a: ['Rousseau'], n: ['le travail', 'la religion'], art: 'travail (notion du bac)', p: '503' }),
D('n-trav-division', N, "Quel problème pose la division technique du travail ?",
  "Théorisée par Smith, la parcellarisation des tâches ôte toute signification à leur exécution (Charlot dans Les Temps modernes) : le travail rationalisé (taylorisme, fordisme) devient répétitif et « bête ». Distincte de la division sociale des métiers, utile.",
  { a: ['Smith'], n: ['le travail', 'la technique'], art: 'travail (notion du bac)', p: '503-505' }),
D('n-trav-citations-1', N, "Que retenir des citations de Rousseau, Kant et Marx sur le travail ?",
  "Rousseau : on travaille pour parvenir au repos, la paresse nous rend laborieux. Kant : par le travail, l'homme s'élève de la rudesse à l'habileté et au bonheur. Marx : le règne de la liberté commence là où cesse le travail déterminé par la nécessité.",
  { a: ['Rousseau', 'Kant', 'Marx'], n: ['le travail', 'la liberté'], art: 'travail (notion du bac)', p: '504' }),
D('n-trav-citations-2', N, "Que retenir des citations de Nietzsche, Freud et Arendt sur le travail ?",
  "Nietzsche : le besoin contraint au travail, qui crée à son tour le besoin de travailler toujours plus. Freud : la majorité ne travaille que par nécessité, naturelle aversion source de problèmes sociaux. Arendt : travail et consommation forment un seul mouvement qui recommence sans cesse.",
  { a: ['Nietzsche', 'Freud', 'Arendt'], n: ['le travail'], art: 'travail (notion du bac)', p: '504' }),
D('n-trav-alienation', N, "Que dénonce la critique marxiste de l'aliénation du travail ?",
  "Non seulement l'exploitation économique (surtravail) mais une situation où l'homme ne se reconnaît pas dans son travail. Elle suppose que le travail doive réaliser l'homme, donc une référence à une essence de l'humanité.",
  { a: ['Marx'], n: ['le travail', 'la liberté'], o: 'Le Capital', art: 'travail (notion du bac)', p: '505' }),
D('n-trav-valeur', N, "Pourquoi le travail peut-il être considéré comme spécifiquement humain (Marx, Hegel) ?",
  "Résultat d'un projet conscient et volontaire (Marx) ; il impose la médiation du temps et de l'outil (Hegel), maîtrise la nature et permet l'objectivation de soi : dans la nature transformée, l'homme se reconnaît et s'affirme.",
  { a: ['Marx', 'Hegel'], n: ['le travail', 'le temps', 'la technique'], art: 'travail (notion du bac)', p: '505' }),
D('n-trav-weil-emploi', N, "Quelle idée du travail Simone Weil défend-elle, et quels problèmes contemporains le dictionnaire soulève-t-il ?",
  "Le travail ne sépare pas pensée et action, intellectuel et manuel : mesure de notre liberté, formateur (Kant). Problèmes : chômage, confusion entre travail et emploi, nécessité de lier travail et formation pour un travail « total », intelligent et actif.",
  { a: ['Weil', 'Kant'], n: ['le travail', 'la liberté'], art: 'travail (notion du bac)', p: '505' }),

// ---------- Notion du bac : la vérité (p. 514-517) ----------
D('n-veri-reel', N, "Le vrai est-il le réel ?",
  "Non : la réalité est indépendante de l'homme, alors que la vérité est du discours ou de la représentation. Elle n'est ni un fait ni un donné : elle doit être recherchée, d'où les questions de ses conditions d'accès et des critères du jugement vrai. C'est aussi une valeur.",
  { n: ['la vérité'], art: 'vérité (notion du bac)', p: '514' }),
D('n-veri-platon-scepticisme', N, "Quelle est la triple idée de Platon sur la recherche de la vérité, et la réponse sceptique ?",
  "1. Cette recherche a un sens. 2. On se l'approprie, on ne la répète pas (maïeutique). 3. Elle est permanente et universelle, non relative comme l'opinion. Le scepticisme (Pyrrhon) lui substitue le doute et la suspension du jugement, valeur de modestie (Montaigne).",
  { a: ['Platon', 'Montaigne'], n: ['la vérité', 'la raison'], art: 'vérité (notion du bac)', p: '514-515' }),
D('n-veri-correspondance', N, "Qu'est-ce que la vérité-correspondance, et de quoi est-elle propriété ?",
  "Adéquation entre l'esprit et la réalité (Thomas d'Aquin) : « il neige » est vrai si et seulement s'il neige. La vérité est une propriété du langage, des propositions, non des choses (l'or faux existe, mais « ceci est de l'or » est faux).",
  { a: ['Thomas d’Aquin'], n: ['la vérité', 'le langage'], art: 'vérité (notion du bac)', p: '515' }),
D('n-veri-coherence', N, "Pourquoi la vérité-cohérence est-elle insuffisante ?",
  "L'accord de la pensée avec elle-même est nécessaire, non suffisant : des pensées cohérentes peuvent contredire le réel. Kant : l'expérience est la « pierre de touche » ; la logique est un canon (critère négatif), non un organon.",
  { a: ['Kant'], n: ['la vérité', 'la science'], art: 'vérité (notion du bac)', p: '515' }),
D('n-veri-pragmatisme', N, "Que reproche-t-on au pragmatisme (James) sur la vérité ?",
  "Il fait du succès la règle du vrai : nos idées augmentent notre puissance d'agir, mais la règle de la vérité est l'art de la preuve. Il n'y a pas de vérité sans vérification. L'idée de correspondance suppose aussi des faits disponibles indépendamment du langage, ce qui n'est pas sûr.",
  { a: ['James'], n: ['la vérité', 'la science'], art: 'vérité (notion du bac)', p: '515' }),
D('n-veri-evidence', N, "L'évidence est-elle le critère de la vérité ?",
  "Descartes et Spinoza : la vérité est index sui, elle se montre par sa clarté ; on connaît les premiers principes par évidence, le reste par déduction (modèle géométrique d'Euclide). Objections : Leibniz (critère trop subjectif, évidences trompeuses) et les sciences expérimentales (l'observation doit être le critère).",
  { a: ['Descartes', 'Spinoza', 'Leibniz'], n: ['la vérité', 'la raison', 'la science'], art: 'vérité (notion du bac)', p: '515-517' }),
D('n-veri-citations', N, "Que retenir des citations de Descartes, Pascal, James, Alain, Russell sur la vérité ?",
  "Descartes : douter une fois en sa vie de toutes choses. Pascal : on connaît la vérité par la raison et par le cœur. James : le vrai est ce qui est avantageux pour la pensée. Alain : toute vérité est fausse dès qu'on s'en contente. Russell : la science vise une vérité « technique ».",
  { a: ['Descartes', 'Pascal', 'James', 'Alain', 'Russell'], n: ['la vérité'], art: 'vérité (notion du bac)', p: '516' }),
D('n-veri-valeur', N, "Pourquoi Nietzsche et Heidegger interrogent-ils la vérité comme valeur ?",
  "Nietzsche : la volonté de vérité est une position morale à retracer, historiquement datée, parfois morbide, qui préfère la vérité à la vie. Heidegger : la vérité originelle est dévoilement, non « certitude de la représentation » ; la poésie est plus vraie que la science.",
  { a: ['Nietzsche', 'Heidegger'], n: ['la vérité', 'la science', "l'art"], art: 'vérité (notion du bac)', p: '517' }),
];
