import { M } from './dsl.mjs';
const R = 'repere';
export default [
// ---------- Repères (manuel, p. 663-741) ----------
M('m-rep-absolu-relatif', R, "Repère « absolu / relatif » : que désigne l'absolu, et que désigne le relatif ?",
  "Absolu (ab-solutus, « délié ») : ce qui existe sans dépendre d'aucune condition, en soi et pour soi. Relatif : ce qui dépend d'autre chose, existe « par un autre et pour un autre ». Ex. : le bonheur est une fin absolue, l'utile une valeur relative (simple moyen).",
  { n: ['la vérité', 'le bonheur'], ref: 'Repères, « Absolu/relatif »', p: '663-665' }),
M('m-rep-absolu-textes', R, "Quels textes le manuel associe-t-il au repère absolu / relatif ?",
  "Descartes (cogito, vérité absolument certaine), Leibniz (Dieu absolument bon), Kant (seule la bonne volonté est bonne sans restriction), Hegel (l'Absolu est résultat, développement de soi), Bergson (justice relative des Anciens, absolue des droits de l'homme).",
  { a: ['Descartes', 'Leibniz', 'Kant', 'Hegel', 'Bergson'], ref: 'Repères, « Absolu/relatif », textes 407-411', p: '664-665' }),
M('m-rep-abstrait-concret', R, "Repère « abstrait / concret » : qu'est-ce qu'abstraire ?",
  "Abstraire, c'est isoler un aspect d'une réalité en négligeant les autres : on produit ainsi un concept général (« arbre » à partir des bouleaux, hêtres, chênes). L'abstrait relève du général et de l'universel, le concret du singulier et de l'expérience. Mais le concret n'est compris qu'au moyen de concepts abstraits.",
  { n: ['la raison', 'le langage'], ref: 'Repères, « Abstrait/concret »', p: '666-667' }),
M('m-rep-abstrait-textes', R, "Que disent Kant, Hegel et Marx du repère abstrait / concret ?",
  "Kant (Logique) : tout concept est abstrait ; abstrait et concret qualifient son usage. Hegel : l'Idée est concrète, l'abstrait n'est pas vrai. Marx (Manuscrits de 1857) : s'élever de l'abstrait au concret est la manière dont la pensée s'approprie le concret.",
  { a: ['Kant', 'Hegel', 'Marx'], ref: 'Repères, « Abstrait/concret », textes 412-414', p: '667-668' }),
M('m-rep-acte-puissance', R, "Repère « en acte / en puissance » : comment le définit-on, avec quel exemple ?",
  "Être en puissance, c'est être capable de faire ou de subir ; être en acte, c'est réaliser effectivement cette capacité (distinction héritée d'Aristote). Ex. : tout être humain est en puissance de parler ; la statue d'Hermès est en puissance dans le bloc de marbre, en acte une fois sculptée.",
  { a: ['Aristote'], ref: 'Repères, « En acte/en puissance »', p: '669-670' }),
M('m-rep-acte-puissance-limites', R, "Pourquoi le couple puissance / acte n'implique-t-il pas toujours un accomplissement ?",
  "Passer à l'acte n'est pas forcément se perfectionner : on peut être en puissance de sa propre destruction (le vivant est en puissance de sa disparition). Et l'historien doit éviter de réduire le passé à ce qu'il est devenu, en oubliant les possibles qu'il portait.",
  { n: ['le temps'], ref: 'Repères, « En acte/en puissance »', p: '670' }),
M('m-rep-analyse-synthese', R, "Repère « analyse / synthèse » : que signifient les deux termes ?",
  "Analyse (analusis, « résolution ») : décomposer un tout en ses éléments. Synthèse (sunthesis, « composition ») : composer ou recomposer un tout à partir d'éléments simples. Les deux sont des opérations fondamentales de l'esprit qui se complètent plus qu'elles ne s'opposent.",
  { n: ['la raison', 'la connaissance'], ref: 'Repères, « Analyse/synthèse »', p: '671-672' }),
M('m-rep-analyse-textes', R, "Quels préceptes de Descartes correspondent à l'analyse et à la synthèse ?",
  "Discours de la méthode, 2e partie : le 2e précepte (diviser chaque difficulté en autant de parcelles que possible) est l'analyse ; le 3e (conduire ses pensées par ordre, du plus simple au plus composé) est la synthèse. Bergson objecte que l'analyse émiette son objet et lui préfère l'intuition.",
  { a: ['Descartes', 'Bergson'], ref: 'Repères, « Analyse/synthèse », textes 417-420', p: '672' }),
M('m-rep-concept-image-metaphore', R, "Repère « concept / image / métaphore » : qu'est-ce qu'un concept, et en quoi diffère-t-il de l'image ?",
  "Le concept est une idée générale (« fleur » n'a ni couleur ni odeur) qui permet de reconnaître et classer les objets perçus ; l'image (perception, imagination) est sensible et particulière. On distingue l'extension (les objets subsumés) et la compréhension (les éléments de son sens).",
  { n: ['le langage', 'la raison'], ref: 'Repères, « Concept/image/métaphore »', p: '673-674' }),
M('m-rep-metaphore', R, "En quoi la métaphore n'est-elle pas une simple comparaison abrégée ?",
  "Elle souligne une ressemblance (« le rossignol milanais » pour la Castafiore) tout en rappelant la différence, et maintient actives plusieurs lignes de pensée. Ce n'est pas l'ennemi du concept, mais son en deçà (préscientifique) ou son au-delà (illustratif).",
  { n: ['le langage'], ref: 'Repères, « Concept/image/métaphore »', p: '674-676' }),
M('m-rep-bachelard-metaphore', R, "Pourquoi Bachelard voit-il dans la métaphore un « obstacle épistémologique » ?",
  "Une métaphore grossière et immédiate (le fer « éponge » du fluide magnétique, l'ovale comme un œuf) séduit la raison et rend aveugle à la spécificité des phénomènes ; il faut la « décolorer » avant d'illustrer les schémas rationnels.",
  { a: ['Bachelard'], n: ['la science', 'le langage'], o: "La Formation de l'esprit scientifique", ref: 'Repères, « Concept/image/métaphore », texte 427', p: '675-678' }),
M('m-rep-cause-fin', R, "Repère « cause / fin » : quelle question pose chacune ?",
  "La cause répond à « pourquoi ? » (ce qui produit l'effet : la boule A pousse la boule B) ; la fin répond à « pour quoi ? » (le but visé, ou l'accomplissement contenu dans la cause). Ex. : les parents sont cause de Socrate, sa fin est d'être philosophe.",
  { n: ['la nature', 'la science'], ref: 'Repères, « Cause/fin »', p: '679-680' }),
M('m-rep-cause-fin-science', R, "Pourquoi la physique classique a-t-elle écarté la finalité ?",
  "La physique aristotélicienne expliquait le mouvement par sa fin : retourner au lieu naturel (fumée vers le haut, pierre vers le bas). En rompant avec ces causes finales, on a pu soumettre légers et graves, mouvements droits et circulaires, aux mêmes lois. Pour le vivant, la question reste plus difficile.",
  { a: ['Aristote'], n: ['la science', 'la nature'], ref: 'Repères, « Cause/fin »', p: '680-681' }),
M('m-rep-cause-fin-textes', R, "Que retenir des textes d'Aristote, Kant et Nietzsche sur cause et fin ?",
  "Aristote (Physique II) : la fin est une cause (la santé est cause de la promenade). Kant (Critique de la faculté de juger) : une fin naturelle est cause et effet d'elle-même. Nietzsche (Aurore) : dans l'œil, la vue n'a pas été le but ; elle est apparue après coup, par hasard.",
  { a: ['Aristote', 'Kant', 'Nietzsche'], ref: 'Repères, « Cause/fin », textes 433-437', p: '681-682' }),
M('m-rep-contingent-necessaire', R, "Repère « contingent / nécessaire / possible » : définitions.",
  "Contingent : ce qui peut être autrement (Leibniz : dont le contraire n'enveloppe pas contradiction). Nécessaire : ce qui ne peut pas être autrement. Possible : ce qui n'est pas nécessairement faux. Ex. : la somme des angles d'un triangle est nécessaire ; qu'il pleuve demain est contingent.",
  { a: ['Leibniz', 'Aristote'], ref: 'Repères, « Contingent/nécessaire/possible »', p: '682-683' }),
M('m-rep-contingent-textes', R, "Quelles distinctions apportent Aristote, Boèce, Leibniz et Boutroux sur le nécessaire ?",
  "Aristote (bataille navale) : il est nécessaire qu'il y en ait une ou non, non qu'il y en ait une. Boèce : nécessité absolue (tous les hommes sont mortels) et conditionnelle (tu sais qu'il se promène, donc il se promène). Leibniz : certain n'est pas nécessaire. Boutroux : les lois de la nature sont contingentes.",
  { a: ['Aristote', 'Boèce', 'Leibniz', 'Boutroux'], ref: 'Repères, « Contingent/nécessaire/possible », textes 438-442', p: '683-684' }),
M('m-rep-croire-savoir', R, "Repère « croire / savoir » : en quoi diffèrent-ils ?",
  "Savoir suppose une activité du sujet, un examen critique, et pouvoir rendre raison de ce qu'on tient pour vrai ; croire renvoie à l'opinion, au préjugé, à un assentiment sans preuve, mais peut aussi être l'adhésion libre qui couronne le savoir. Croire et savoir sont donc opposés et articulés.",
  { n: ['la vérité', 'la raison', 'la religion'], ref: 'Repères, « Croire/savoir »', p: '684-685' }),
M('m-rep-croire-textes', R, "Que retenir de Platon, Hume et Sartre sur croire / savoir ?",
  "Platon (Gorgias) : la croyance que donne la science s'oppose à celle qui en est dénuée. Hume : les raisonnements sur les faits reposent sur l'habitude, ce sont des croyances (le soleil se lèvera demain). Sartre : croire, c'est savoir qu'on croit, et donc ne plus croire tout à fait.",
  { a: ['Platon', 'Hume', 'Sartre'], ref: 'Repères, « Croire/savoir », textes 443-445', p: '685-686' }),
M('m-rep-essentiel-accidentel', R, "Repère « essentiel / accidentel » : que désigne chaque terme ?",
  "Essentiel : ce qui définit un être, sans quoi il ne serait pas ce qu'il est (essentia traduit ousia). Accidentel : ce qui lui arrive occasionnellement et aurait pu ne pas être. Ex. : être une figure à trois côtés est essentiel au triangle ; être isocèle ou rectangle est accidentel.",
  { a: ['Aristote'], n: ['le langage'], ref: 'Repères, « Essentiel/accidentel »', p: '687-688' }),
M('m-rep-essentiel-socrate', R, "Quel lien y a-t-il entre la question socratique « qu'est-ce que X ? » et l'essentiel ?",
  "Elle demande ce qui est essentiel à une chose pour qu'elle soit elle-même, en éliminant l'accidentel par abstraction. Ménon et Hippias se trompent en énumérant des exemples (« qu'est-ce qui est beau ? ») au lieu de donner l'essence (« qu'est-ce que le beau ? »).",
  { a: ['Platon', 'Socrate'], ref: 'Repères, « Essentiel/accidentel »', p: '687-688' }),
M('m-rep-expliquer-comprendre', R, "Repère « expliquer / comprendre » : distinction.",
  "Expliquer (ex-plicare, « déplier ») : exposer objectivement un ensemble de significations, en particulier par des liens de causalité. Comprendre (comprehendere, « saisir ») : se les approprier personnellement. On peut expliquer sans comprendre (l'action à distance de la gravité) et comprendre sans expliquer.",
  { n: ['la science', 'le langage'], ref: 'Repères, « Expliquer/comprendre »', p: '690-691' }),
M('m-rep-fait-droit', R, "Repère « en fait / en droit » : que oppose-t-il ?",
  "Ce qui existe effectivement (le fait, factum, « accompli ») et ce qui est juste, légal ou légitime (le droit). Le fait ne fait pas droit : sous l'Occupation, le régime de Vichy était une « autorité de fait » alors que le pouvoir légitime était à Londres. Mais le droit doit aussi se soucier de sa mise en œuvre.",
  { n: ['la justice', "l'État"], ref: 'Repères, « En fait/en droit »', p: '692-693' }),
M('m-rep-exemple-preuve', R, "Repère « exemple / preuve » : un exemple prouve-t-il quelque chose ?",
  "Un exemple illustre mais ne prouve pas : il ne permet pas d'établir un principe universel (démarche inductive). En revanche un contre-exemple suffit à ruiner un principe universel. C'est le raisonnement, non les exemples, qui doit faire la preuve. En morale, l'exemple est un modèle (Bergson) que Kant conteste.",
  { a: ['Kant', 'Bergson'], n: ['la vérité'], ref: 'Repères, « Exemple/preuve »', p: '694-695' }),
M('m-rep-forme-matiere', R, "Repère « forme / matière » : sens courant et sens philosophique.",
  "Sens courant : la forme est l'apparence extérieure, la matière ce dont l'objet est fait. Sens philosophique : la matière est indéterminée et reçoit sa forme, principe qui détermine l'essence (forme substantielle, chez Aristote ; eidos, forme intelligible, chez Platon, plus réelle que les choses matérielles).",
  { a: ['Aristote', 'Platon'], n: ["l'art", 'la nature'], ref: 'Repères, « Forme/matière »', p: '698-699' }),
M('m-rep-genre-espece-individu', R, "Repère « genre / espèce / individu » : comment s'emboîtent-ils ?",
  "L'individu (cette jonquille-ci) est le plus concret ; l'espèce regroupe des individus ayant des traits communs (les jonquilles) ; le genre regroupe des espèces (la fleur) et est le niveau le plus abstrait. On définit par le genre et la différence spécifique. Ces hiérarchies sont des conventions de classement.",
  { n: ['la nature', 'le langage'], ref: 'Repères, « Genre/espèce/individu »', p: '700-701' }),
M('m-rep-ideal-reel', R, "Repère « idéal / réel » : quel paradoxe le manuel relève-t-il ?",
  "Étymologiquement complémentaires (idea, aspect visible ; res, chose), les deux s'opposent pourtant comme l'abstrait au concret. « L'idéal » désigne aussi une réalité supérieure au réel (idéal communiste / socialisme réel). Platon (Banquet) : l'Idée du beau, éternelle et parfaite, est plus réelle que les belles choses.",
  { a: ['Platon'], n: ['la vérité', "l'art"], ref: 'Repères, « Idéal/réel »', p: '702-703' }),
M('m-rep-identite-egalite', R, "Repère « identité / égalité / différence » : que signifient identité et égalité ?",
  "Identité (idem, « le même ») : absence de différence d'une chose avec elle-même (A = A) ; égalité : absence de différence entre deux choses (A = B). Principe d'identité et de non-contradiction : bases de la logique. Moralement et juridiquement, l'égalité repose sur l'égale dignité des hommes (alter ego).",
  { n: ['la justice', 'la conscience'], ref: 'Repères, « Identité/égalité/différence »', p: '704-705' }),
M('m-rep-intuitif-discursif', R, "Repère « intuitif / discursif » : que désignent-ils ?",
  "Intuitif (intuitio, « vision ») : saisie directe et immédiate d'un objet présent aux sens (intuition sensible) ou à la pensée (intuition intellectuelle). Discursif : connaissance médiate qui procède par étapes successives (raisonnement, démonstration). On parle d'une raison intuitive et d'une raison discursive.",
  { n: ['la raison', 'la connaissance'], ref: 'Repères, « Intuitif/discursif »', p: '706-708' }),
M('m-rep-legal-legitime', R, "Repère « légal / légitime » : la légalité suffit-elle à la légitimité ?",
  "Non : légal = conforme à la loi positive en vigueur ; légitime = juste, fondé sur une justice supérieure à la loi. Antigone enfreint le décret de Créon (acte illégal) sans qu'on le juge illégitime. En morale, la simple légalité de l'action ne suffit pas : il faut agir par devoir.",
  { a: ['Kant'], n: ['la justice', "l'État", 'le devoir'], ref: 'Repères, « Légal/légitime »', p: '709-710' }),
M('m-rep-mediat-immediat', R, "Repère « médiat / immédiat » : définitions.",
  "Immédiat : ce qui se donne directement, sans intermédiaire (l'expérience brute, le réflexe, l'émotion). Médiat : ce qui passe par un intermédiaire, la médiation de la pensée réflexive. Ce qui se donne comme immédiat (les « données immédiates de la conscience », Bergson) l'est souvent moins qu'on ne croit.",
  { a: ['Bergson', 'Descartes'], n: ['la conscience'], ref: 'Repères, « Médiat/immédiat »', p: '711-713' }),
M('m-rep-objectif-subjectif', R, "Repère « objectif / subjectif / intersubjectif » : sens des termes.",
  "Subjectif (sub-jectum) : ce qui dépend du sujet, de sa conscience ou de ses préférences. Objectif (ob-jectum) : ce qui fait face au sujet, existe hors de l'esprit, indépendamment du point de vue. Intersubjectif (Husserl) : la relation des consciences entre elles, constitutive de la subjectivité.",
  { a: ['Husserl'], n: ['la conscience', 'la vérité'], ref: 'Repères, « Objectif/subjectif/intersubjectif »', p: '714-717' }),
M('m-rep-obligation-contrainte', R, "Repère « obligation / contrainte » : quelle différence ?",
  "La contrainte est un obstacle extérieur, éventuellement physique (la barrière baissée ; la torture) ; l'obligation est d'ordre juridique ou moral, un « lien » (ligare) laissant au sujet la possibilité de résister, et se vit comme sentiment intérieur du devoir. « La peur du gendarme » oblige, le « dos d'âne » contraint.",
  { n: ['le devoir', 'la liberté'], ref: 'Repères, « Obligation/contrainte »', p: '718-719' }),
M('m-rep-origine-fondement', R, "Repère « origine / fondement » : pourquoi les distinguer ?",
  "L'origine renvoie au commencement (chronologique, ou provenance) ; le fondement est la raison logique d'une chose. Ce n'est pas le commencement temporel qui fonde : nous apprenons en croyant nos maîtres, mais leur parole n'est pas le fondement de nos connaissances. Distinguer l'origine de l'esclavage et son fondement.",
  { n: ['la vérité', 'la justice'], ref: 'Repères, « Origine/fondement »', p: '720-721' }),
M('m-rep-persuader-convaincre', R, "Repère « persuader / convaincre » : quelle différence ?",
  "Convaincre (convincere, terme juridique, « vaincre ») s'adresse à la raison par des arguments démonstratifs ; persuader (suadere, « conseiller », suave) agit aussi sur l'affectivité, par séduction. On peut être convaincu sans être persuadé, et inversement. Claudel : persuader, c'est éveiller « une complaisance secrète ».",
  { n: ['le langage', 'la raison'], ref: 'Repères, « Persuader/convaincre »', p: '722-723' }),
M('m-rep-principe-consequence', R, "Repère « principe / conséquence » : que signifie principe ?",
  "Principe (principium, arché) : ce qui vient en premier et commande ce qui en découle, avec les idées de primauté et de commandement (monarchie, anarchie, hiérarchie). La relation principe → conséquence est nécessaire : s'il en va autrement, un autre principe est intervenu. Descartes fait du cogito le principe de ses vérités.",
  { a: ['Descartes'], n: ['la raison', 'la vérité'], ref: 'Repères, « Principe/conséquence »', p: '724-725' }),
M('m-rep-public-prive', R, "Repère « public / privé » : que désigne « public » au sens strict ?",
  "Public vient de populus : ce qui relève d'une collectivité politiquement organisée (peuple, nation), donc souvent de l'État ; d'où la distinction droit public / droit privé. Privé : ce qui appartient en propre à un particulier, une famille, une firme. Chez les Anciens, esclaves et femmes étaient cantonnés à la sphère privée.",
  { n: ["l'État", 'la justice'], ref: 'Repères, « Public/privé »', p: '726-727' }),
M('m-rep-ressemblance-analogie', R, "Repère « ressemblance / analogie » : qu'est-ce qu'une analogie ?",
  "La ressemblance souligne une similitude d'apparence entre deux réalités ; l'analogie dégage une identité de rapports entre des termes différents (a/b = c/d, d'après Lalande), avec au moins trois termes : la plume est au pamphlétaire ce que l'épée est au soldat. Elle a une fonction didactique.",
  { n: ['le langage', 'la science'], ref: 'Repères, « Ressemblance/analogie »', p: '728-732 (à préciser)' }),
M('m-rep-theorie-pratique', R, "Repère « en théorie / en pratique » : d'où vient leur opposition ?",
  "Pour les Grecs, la théorie (theoria, contemplation des réalités intelligibles) est une espèce de praxis (action ayant sa fin en elle-même) ; ils opposent la praxis à la poiésis (production d'un objet). L'opposition vie active / vie contemplative vient du christianisme médiéval (vita activa / vita contemplativa).",
  { a: ['Platon', 'Aristote'], n: ['le travail', 'la technique'], ref: 'Repères, « En théorie/en pratique »', p: '733-734 (à préciser)' }),
M('m-rep-transcendant-immanent', R, "Repère « transcendant / immanent » : définitions.",
  "Transcendant (transcendere, « monter au-delà ») : ce qui dépasse l'expérience ou l'ordre des choses considérées (Dieu créateur, cause externe du monde). Immanent (immanere, « résider dans ») : ce qui reste à l'intérieur de cet ordre. Chez Kant : usage immanent de la raison (dans l'expérience) et usage transcendant (métaphysique).",
  { a: ['Kant'], n: ['la religion', 'la raison'], ref: 'Repères, « Transcendant/immanent »', p: '735 (à préciser)' }),
M('m-rep-universel-general', R, "Repère « universel / général / particulier / singulier » : distinction.",
  "Universel : valable pour tous les cas d'une totalité, partout et toujours, sans exception (« tous les hommes sont mortels »). Général : valable le plus souvent, avec des exceptions (règles de grammaire ; « tous les cygnes sont blancs »). Particulier : valable pour une partie (« quelques Grecs… »). Singulier : pour un individu (« Socrate est philosophe »).",
  { n: ['la science', 'la raison'], ref: 'Repères, « Universel/général/particulier/singulier »', p: '735-741 (à préciser)' }),
M('m-rep-vrai-probable-certain', R, "Repère « vrai / probable / certain » : le vrai et le certain sont-ils synonymes ?",
  "Non : la certitude est un état du sujet, qui peut porter sur du faux (on est certain que deux et deux ne font pas cinq). Le vrai est l'accord de l'énoncé avec l'état de choses ; le probable est ce dont on estime la réalisation vraisemblable sans certitude (vivre au-delà de 40 ans à 30 ans, en bonne santé).",
  { n: ['la vérité', 'la science'], ref: 'Repères, « Vrai/probable/certain »', p: '735-741 (à préciser)' }),
M('m-rep-leibniz-verites', R, "Quelle distinction de Leibniz éclaire le repère vrai / certain ?",
  "Les vérités de raison (logique, mathématiques) sont nécessaires et déduites ; les vérités de fait sont contingentes, connues par l'expérience. Descartes voit dans l'arithmétique et la géométrie les fruits spontanés de la raison, à cause de l'évidence de leurs raisons.",
  { a: ['Leibniz', 'Descartes'], n: ['la vérité', 'la raison'], ref: 'Repères, « Vrai/probable/certain »', p: '735-741 (à préciser)' }),
];
