import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- La raison (manuel, p. 435-440) ----------
M('m-rais-ratio-logos', N, "Quelles sont l'origine latine et l'équivalent grec de « raison » ?",
  "Ratio : calcul, puis organisation ou mise en ordre, et la faculté de le faire (d'où une raison calculante, prisonnière de visées utilitaires). Dès Cicéron, ratio traduit le grec logos, rendu tantôt par raison, langage, discours, argument, ou « Verbe » dans l'Évangile de Jean.",
  { a: ['Cicéron'], n: ['la raison', 'le langage'], ref: 'La raison, « De l\'usage du mot à la notion »', p: '435' }),
M('m-rais-bon-sens', N, "Comment Descartes définit-il la raison au début du Discours de la méthode ?",
  "Une capacité « de bien juger, et distinguer le vrai d'avec le faux », qu'il appelle aussi bon sens, qui distingue l'homme des bêtes et est « naturellement égale en tous les hommes ». Mais il précise aussitôt que l'important est de bien l'appliquer, ce qui est moins répandu.",
  { a: ['Descartes'], n: ['la raison'], o: 'Discours de la méthode', ref: 'La raison, « De l\'usage du mot à la notion »', p: '435-436' }),
M('m-rais-theorique-pratique', N, "Dans quelles deux directions la raison se déploie-t-elle ?",
  "Théorique : quête de savoir, raisonnements tirant des conséquences valides de principes connus (démonstrations, lois des sciences), avec la vigilance de la logique contre les sophismes. Pratique : orienter l'action individuelle et collective. Reste à savoir si la raison est immanente à l'histoire et à la morale, et quelles sont ses limites.",
  { a: ['Aristote', 'Kant'], n: ['la raison', 'la science', 'le devoir'], ref: 'La raison, « De l\'usage du mot à la notion »', p: '436-437' }),
M('m-rais-apodictique-axiome', N, "Apodictique et axiome : définitions ?",
  "Apodictique (apodeixis, « démonstration ») : jugement ou raisonnement démonstratif, nécessaire. Axiome : proposition évidente par soi qu'on ne démontre pas, dite aussi « notion commune » (le tout est plus grand que la partie ; deux choses égales à une troisième sont égales entre elles).",
  { n: ['la raison', 'la science'], ref: 'La raison, « Termes essentiels »', p: '438' }),
M('m-rais-deduction-inference', N, "Déduction et inférence : différence ?",
  "Déduction : opération concluant de manière nécessaire une proposition à partir d'une ou plusieurs autres ; elle se distingue de l'intuition, saisie directe. Inférence : acte concluant d'une proposition à une autre, inductive (à partir de quelques cas) ou déductive (à partir de prémisses nécessaires valables dans tous les cas).",
  { n: ['la raison'], ref: 'La raison, « Termes essentiels »', p: '438' }),
M('m-rais-definition', N, "Quels types de définitions distingue-t-on, et quelle est la forme classique ?",
  "Définitions qui donnent l'essence d'une chose et définitions qui donnent le sens d'un terme. Forme classique : par genre prochain et différence spécifique (l'homme est un animal — genre — doué de raison — différence spécifique).",
  { n: ['la raison', 'le langage'], ref: 'La raison, « Termes essentiels » (définition)', p: '438' }),
M('m-rais-dialectique', N, "Quels sont les quatre grands emplois du terme « dialectique » ?",
  "1. Platon : science élevée (République VI) connaissant les Formes par l'art d'interroger et de répondre. 2. Aristote : raisonnement sur des principes non avérés, moins éminent que la démarche du philosophe. 3. Stoïciens et Moyen Âge : synonyme de logique, art de l'argumentation (trivium). 4. Hegel : penser ensemble les contradictoires et dépasser leur opposition.",
  { a: ['Platon', 'Aristote', 'Hegel'], n: ['la raison', 'la vérité'], ref: 'La raison, « Termes essentiels » (dialectique)', p: '438' }),
M('m-rais-jugement-predicat', N, "Jugement, prédicat, proposition, terme : définitions ?",
  "Jugement : acte attribuant un prédicat à un sujet. Prédicat : ce qui est dit du sujet (« blanche » dans « la neige est blanche »), forme « S est P ». Proposition : énoncé susceptible d'être vrai ou faux (pour Aristote, les futurs contingents n'en sont pas). Terme : constituant élémentaire d'une proposition.",
  { a: ['Aristote'], n: ['la raison', 'la vérité'], ref: 'La raison, « Termes essentiels »', p: '438-439' }),
M('m-rais-postulat', N, "Qu'est-ce qu'un postulat, et en quoi diffère-t-il d'un axiome ?",
  "Postulat (postulare, « demander ») : proposition non démontrable et non évidente qu'on demande d'accepter en cours de raisonnement (prolonger une droite indéfiniment ; par un point extérieur à une droite passe une seule parallèle). Euclide distingue axiome et postulat.",
  { a: ['Euclide'], n: ['la raison', 'la science'], ref: 'La raison, « Termes essentiels » (postulat)', p: '438' }),
M('m-rais-principes', N, "Quels sont les principes de contradiction et de raison suffisante ?",
  "Principe : proposition servant de fondement à un raisonnement. Contradiction (Aristote, Métaphysique Γ 3) : impossible que le même prédicat appartienne et n'appartienne pas en même temps à la même chose sous le même rapport. Raison (Leibniz) : « rien n'est sans raison », rien n'échappe à la puissance explicative de la raison.",
  { a: ['Aristote', 'Leibniz'], n: ['la raison'], ref: 'La raison, « Termes essentiels »', p: '438-439' }),
M('m-rais-ruse', N, "Qu'est-ce que la « ruse de la raison » chez Hegel ?",
  "La Raison universelle se sert, à leur insu, des passions individuelles et des buts particuliers des hommes pour accomplir ses desseins. Idées analogues : le Dieu calculateur de Leibniz, la « main invisible » d'Adam Smith, l'« insociable sociabilité » de Kant.",
  { a: ['Hegel', 'Leibniz', 'Smith', 'Kant'], n: ['la raison', "l'État"], ref: 'La raison, « Termes essentiels » (ruse de la raison)', p: '439' }),
M('m-rais-sophisme-syllogisme', N, "Sophisme et syllogisme : définitions ?",
  "Sophisme : raisonnement concluant seulement en apparence, destiné à induire l'interlocuteur en confusion ou à le faire se contredire. Syllogisme : raisonnement en forme où, de prémisses reliées par un terme commun (prédicat dans l'une, sujet dans l'autre), on tire une conclusion.",
  { a: ['Aristote'], n: ['la raison', 'la vérité'], ref: 'La raison, « Termes essentiels »', p: '439' }),
];
