import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- La religion (manuel, p. 461-465) ----------
M('m-reli-usages', N, "Qu'indiquent les expressions figurées « écouter religieusement », « se faire sa religion » ?",
  "Écouter ou faire quelque chose « religieusement » : y mettre une attention et un respect proches du sacré, avec un sentiment d'obligation. « Ne pas s'être fait sa religion » : ne pas avoir de conviction forgée, ce qui suppose la croyance religieuse profondément ancrée dans le sujet.",
  { n: ['la religion'], ref: 'La religion, « De l\'usage du mot à la notion »', p: '461' }),
M('m-reli-diversite', N, "Quels phénomènes différents le mot « religion » amalgame-t-il ?",
  "1) Des systèmes de croyances fondés sur des textes sacrés révélés (judaïsme, christianisme, islam, religions du Livre). 2) Des pratiques rituelles ou cultuelles, notamment funéraires (traces remontant à près de 90 000 ans chez les Néandertaliens), séparant espace sacré et profane. 3) Des sagesses de vie où les dieux comptent peu (bouddhisme, taoïsme).",
  { n: ['la religion'], ref: 'La religion, « De l\'usage du mot à la notion »', p: '461-462' }),
M('m-reli-relegere-religare', N, "Quelles sont les deux étymologies concurrentes de religio ?",
  "Relegere (Cicéron ; Benveniste : legere, « cueillir, revenir sur ce qu'on fait ») : attention, recueillement, sens du sacré — la religion comme disposition du sujet. Religare (Lactance, auteurs chrétiens tardifs) : « relier » : ce qui relie les hommes à Dieu et entre eux (la secte divise, la religion réunit). Grecs et Latins n'avaient pas le concept moderne.",
  { a: ['Cicéron', 'Lactance', 'Benveniste'], n: ['la religion'], ref: 'La religion, « De l\'usage du mot à la notion »', p: '462' }),
M('m-reli-anthropomorphisme', N, "Qu'est-ce que l'anthropomorphisme ?",
  "L'attribution à Dieu de caractéristiques humaines : la tendance à concevoir Dieu à l'image de l'homme (anthropos, morphê).",
  { n: ['la religion'], ref: 'La religion, « Termes essentiels » (anthropomorphisme)', p: '464' }),
M('m-reli-athee-agnostique', N, "Athée, irréligieux, agnostique : quelle différence ?",
  "Athée : sans dieu ; athéisme : doctrine niant l'existence de Dieu. L'irréligieux est sans religion et indifférent à la question. L'agnostique affirme qu'aucun savoir n'est possible en ce domaine.",
  { n: ['la religion', 'la vérité'], ref: 'La religion, « Termes essentiels » (athée, athéisme)', p: '464' }),
M('m-reli-coran-culte', N, "Qu'est-ce que le Coran, et qu'est-ce que le culte ?",
  "Coran : texte sacré des musulmans, révélations faites par Dieu (Allah) à Mahomet, établi vers 650, 114 sourates classées par longueur décroissante. Culte : vénération de la divinité et ensemble des rites qui l'expriment, le plus souvent pratique sociale liant une communauté.",
  { n: ['la religion'], ref: 'La religion, « Termes essentiels »', p: '464' }),
M('m-reli-mono-poly', N, "Monothéisme et polythéisme : définitions ?",
  "Monothéisme (monos, theos) : religion affirmant un seul Dieu (judaïsme, christianisme, islam). Polythéisme : croyance en plusieurs dieux (religion romaine : panthéon des dieux et dieux lares propres à chaque famille).",
  { n: ['la religion'], ref: 'La religion, « Termes essentiels »', p: '464' }),
M('m-reli-mythe', N, "Qu'est-ce qu'un mythe, et à quoi l'oppose-t-on ?",
  "Récit fabuleux rendant compte des origines du monde, mettant en scène des héros fondateurs dans le temps des origines, avec valeur de prescription ou d'explication. On oppose traditionnellement mythe (muthos) et logos, discours rationnel.",
  { n: ['la religion', 'la raison'], ref: 'La religion, « Termes essentiels » (mythe)', p: '464' }),
M('m-reli-sacre-profane', N, "Sacré, profane, sacrilège : définitions ?",
  "Sacré : ce qui est séparé, interdit, inviolable, exigeant le respect. Profane (profanus, « devant le temple ») : ce qui n'est pas sacré. Sacrilège : acte de profanation, de non-respect du sacré.",
  { a: ['Durkheim'], n: ['la religion'], ref: 'La religion, « Termes essentiels »', p: '464' }),
M('m-reli-revelation-rite', N, "Révélation et rite : définitions ?",
  "Révélation : acte par lequel Dieu est supposé se manifester aux hommes. Rite (ritus) : habitude, règle, usage ; ensemble ordonné et codifié des règles de célébration d'un culte ou d'une cérémonie.",
  { n: ['la religion'], ref: 'La religion, « Termes essentiels »', p: '464' }),
M('m-reli-secte-superstition', N, "Secte, superstition, théologie : définitions ?",
  "Secte : d'abord école philosophique, puis hérésie dont la doctrine s'écarte de l'observance commune. Superstition (superstare) : chez Cicéron, celui qui prie sans cesse pour que ses enfants lui survivent ; attitude religieuse vaine (excessive, irrationnelle, ou tournée vers de faux dieux). Théologie : étude de la divinité.",
  { a: ['Cicéron'], n: ['la religion'], ref: 'La religion, « Termes essentiels »', p: '464-465' }),
];
