import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- La science (manuel, p. 489-495) ----------
M('m-scie-revolution', N, "Comment la science moderne est-elle liée à la technique et à la maîtrise de la nature ?",
  "Avec la révolution scientifique (Bacon, Galilée, Descartes) et les Lumières (Encyclopédie de Diderot et d'Alembert), la science est mise en œuvre pour ses bénéfices pratiques. Descartes : généraliser la méthode mathématique à la physique pour des connaissances « fort utiles à la vie », qui nous rendraient « comme maîtres et possesseurs de la nature » (Discours, 6e partie).",
  { a: ['Descartes', 'Bacon', 'Galilée'], n: ['la science', 'la technique'], o: 'Discours de la méthode', ref: 'La science, « De l\'usage du mot à la notion »', p: '489-491' }),
M('m-scie-etymologie', N, "Que révèle l'étymologie de « science » ?",
  "Scientia (de scire, « savoir ») désigne chez Cicéron le savoir théorique et pratique ; il traduit le grec epistêmê (d'où épistémologie). Chez Platon epistêmê est proche de technê ; à partir d'Aristote, il désigne les sciences théorétiques et pratiques, tandis que technê est réservé au savoir-faire. Foucault en tire le concept d'épistémè.",
  { a: ['Aristote', 'Platon', 'Foucault'], n: ['la science'], ref: 'La science, « De l\'usage du mot à la notion »', p: '491' }),
M('m-scie-sens-large', N, "Pourquoi ne faut-il pas réduire « science » aux sciences modernes ?",
  "Depuis Aristote, le terme s'applique aussi aux savoirs pratiques (prattein, « agir ») : science politique, académie des sciences morales et politiques, sciences juridiques. Les sciences modernes se caractérisent par l'usage des mathématiques et des mesures précises, mais tous les emplois du mot n'y renvoient pas.",
  { a: ['Aristote'], n: ['la science'], ref: 'La science, « De l\'usage du mot à la notion »', p: '491' }),
M('m-scie-inquietudes', N, "Quelles inquiétudes la science suscite-t-elle (scientisme, transhumanisme) ?",
  "L'emprise de la science et du scientisme suscite des craintes dès l'époque romantique (« L'apprenti sorcier » de Goethe, Frankenstein, « Prométhée moderne » de Mary Shelley), nourries par la science-fiction. Le transhumanisme soutient que la science pourrait affranchir l'homme de la maladie et même de la mort.",
  { a: ['Goethe', 'Shelley'], n: ['la science', 'la technique'], ref: 'La science, « De l\'usage du mot à la notion »', p: '491-492' }),
M('m-scie-bioethique', N, "Qu'est-ce que la bioéthique ?",
  "Néologisme forgé en 1971 par le cancérologue Van Rensselaer Potter (Bioethics: bridge to the future) pour désigner les questions éthiques soulevées par les sciences du vivant : pratiques expérimentales, recherche médicale, biologie, génétique, thérapies géniques.",
  { n: ['la science', 'le devoir'], ref: 'La science, « Termes essentiels » (bioéthique)', p: '492' }),
M('m-scie-comprendre-expliquer', N, "Quelle distinction Dilthey propose-t-il entre expliquer et comprendre ?",
  "Sciences de la nature (explicatives) : chercher les lois générales rendant raison d'un phénomène (la gravitation explique la chute des corps). Sciences de l'esprit (compréhensives, à peu près les sciences de l'homme) : comprendre dans leur spécificité des phénomènes singuliers (la Révolution française, 1914) en dégageant leur sens.",
  { a: ['Dilthey'], n: ['la science'], ref: 'La science, « Termes essentiels » (compréhension/explication)', p: '492' }),
M('m-scie-epistemologie', N, "Qu'est-ce que l'épistémologie ?",
  "Étymologiquement « science de la science » (epistêmê + logos) : réflexion sur la manière dont la science procède et sur son cheminement (hodos, d'où « méthode »). L'épistémologie générale s'accompagne d'épistémologies régionales ; le terme est ici synonyme de méthodologie.",
  { n: ['la science'], ref: 'La science, « Termes essentiels » (épistémologie)', p: '493' }),
M('m-scie-physicalisme', N, "Qu'est-ce que le physicalisme ?",
  "Doctrine de Neurath (Cercle de Vienne) ramenant toutes les sciences à une base physique commune, garante de l'unité et de la rigueur. En philosophie de l'esprit : assimilation des états mentaux à des processus physiques du cerveau (croyance et désir réductibles à des états cérébraux).",
  { a: ['Neurath'], n: ['la science', 'la conscience'], ref: 'La science, « Termes essentiels » (physicalisme)', p: '494' }),
M('m-scie-positivisme', N, "Qu'est-ce que le positivisme d'Auguste Comte ?",
  "Doctrine du XIXe siècle selon laquelle seule la méthode des sciences positives, référées à des faits réels et certains, est féconde et conduit l'humanité au bonheur ; il faut renoncer aux « fictions » théologiques et aux « abstractions » métaphysiques.",
  { a: ['Comte'], n: ['la science', 'le bonheur'], ref: 'La science, « Termes essentiels » (positivisme)', p: '494' }),
M('m-scie-reductionnisme', N, "Qu'est-ce que le réductionnisme ?",
  "Attitude qui réduit un niveau de phénomènes à un niveau inférieur : la conscience au comportement ou au cerveau (behaviorisme, cybernétique), les lois sociales aux lois biologiques (sociobiologie), le vivant à ses composants chimiques. Critiqué notamment par Sahlins et Searle.",
  { n: ['la science', 'la conscience'], ref: 'La science, « Termes essentiels » (réductionnisme)', p: '494' }),
M('m-scie-rupture-epistemologique', N, "Qu'est-ce que la rupture épistémologique (Bachelard) ?",
  "Modèle discontinuiste du progrès scientifique : la science ne développe sa rationalité qu'en rompant sans cesse avec l'opinion et le savoir ordinaire, mais aussi avec les savoirs scientifiques antérieurs, qui peuvent devenir eux-mêmes des obstacles épistémologiques.",
  { a: ['Bachelard'], n: ['la science', 'la vérité'], ref: 'La science, « Termes essentiels »', p: '494' }),
M('m-scie-cognitives-scientisme', N, "Sciences cognitives et scientisme : définitions ?",
  "Sciences cognitives : élucident la cognition en associant neurosciences, psychologie cognitive, intelligence artificielle, psychologie expérimentale, voire phénoménologie. Scientisme : attitude de confiance en la science pour trancher définitivement des questions métaphysiques et éthiques, apogée dans la seconde moitié du XIXe siècle, liée au positivisme et au matérialisme.",
  { n: ['la science', 'la conscience'], ref: 'La science, « Termes essentiels »', p: '495' }),
M('m-scie-teleologie', N, "Téléologie et téléonomie : quelle différence ?",
  "Téléologie (telos, logos) : doctrine selon laquelle la cause déterminante d'un phénomène est sa fin (le chêne est cause finale du gland). Téléonomie : terme forgé par Jacques Monod (Le Hasard et la nécessité) pour rendre compte des processus finalisés dans l'évolution et le fonctionnement des organismes.",
  { a: ['Monod'], n: ['la science', 'la nature'], ref: 'La science, « Termes essentiels »', p: '495' }),
];
