import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Le temps (manuel, p. 565-569) ----------
M('m-temp-avoir', N, "Que révèlent les expressions « avoir le temps », « prendre son temps » ?",
  "Le temps semble se posséder ou manquer, mais pas comme la faim ou l'argent (« time is money ») ; on manque de temps pour faire quelque chose, et il faut le prendre pour bien faire (le bâcler nuit à l'acquisition des savoirs). En français, « temps » désigne aussi le temps qu'il fait, que l'anglais (weather/time) et l'allemand (Wetter/Zeit) distinguent.",
  { n: ['le temps'], ref: 'Le temps, « De l\'usage du mot à la notion »', p: '565-566' }),
M('m-temp-tempus', N, "Que révèle l'étymologie de « temps » (tempus) ?",
  "Tempus renvoie à une fraction du temps : époque (o tempora, o mores), saison (printemps = primum tempus), moment ou instant, ainsi qu'au temps qu'il fait. Il se distingue d'aevum (durée longue ou sans fin, d'où aetas et aeternus). Racine indo-européenne tem, « couper » (grec temnô).",
  { n: ['le temps'], ref: 'Le temps, « De l\'usage du mot à la notion »', p: '566' }),
M('m-temp-chronos-kairos', N, "Chronos, kairos, aiôn : que désignent ces trois mots grecs ?",
  "Chronos : le temps qui passe (chronique, chronomètre, chronologie). Kairos : l'instant, le moment opportun (occasio en latin). Aiôn : la durée éternelle. Chronos est sans parenté étymologique avec Kronos, le dieu fils d'Ouranos et de Gaia, père de Zeus (Saturne chez les Latins).",
  { n: ['le temps'], ref: 'Le temps, « De l\'usage du mot à la notion »', p: '567' }),
M('m-temp-conscience-historique', N, "Conscience historique et époque : définitions ?",
  "Conscience historique : compréhension qu'un individu ou un peuple a de sa situation dans le cours de l'histoire. Époque (epokhê, « arrêt ») : période historique formant un ensemble qu'on peut envisager comme une totalité unifiée.",
  { n: ['le temps'], ref: 'Le temps, « Termes essentiels »', p: '568' }),
M('m-temp-dasein', N, "Qu'est-ce que le Dasein chez Heidegger ?",
  "Allemand « être-là » (existence) : l'existant humain singulier, dont le mode d'être consiste à se projeter en avant de soi vers un avenir de libres possibilités. « L'essence du Dasein réside dans son existence » (Être et Temps, § 9).",
  { a: ['Heidegger'], n: ['le temps'], o: 'Être et Temps', ref: 'Le temps, « Termes essentiels » (Dasein)', p: '568' }),
M('m-temp-distension', N, "Que signifie la distension de l'âme chez saint Augustin ?",
  "Dans les Confessions (livre XI), l'activité de l'esprit « tendu » vers le passé, le présent et l'avenir, qui rend possible la mesure du temps et conjugue les trois présents de l'âme : présent du futur, présent du passé, présent du présent.",
  { a: ['Augustin'], n: ['le temps', 'la conscience'], o: 'Confessions', ref: 'Le temps, « Termes essentiels » (distension)', p: '568' }),
M('m-temp-duree', N, "Comment définit-on la durée, objectivement et chez Bergson ?",
  "Objectivement : le temps écoulé entre le commencement et la fin d'un phénomène. Subjectivement : le flux temporel constituant la vie de la conscience. Chez Bergson, la durée « pure » s'oppose au temps spatialisé, homogène et quantifiable de la mesure.",
  { a: ['Bergson'], n: ['le temps', 'la conscience'], ref: 'Le temps, « Termes essentiels » (durée)', p: '568' }),
M('m-temp-eternite', N, "Quelles sont les deux conceptions de l'éternité ?",
  "1) Ce qui existe depuis toujours et à jamais, sans naissance ni fin (l'être de Parménide) : compatible avec la durée, c'est la sempiternité. 2) La possession parfaite, totale et simultanée (tota simul) d'une vie infinie, exclusive de tout écoulement (Plotin, Boèce) : « dans l'éternité il n'y a pas de temps » (Augustin).",
  { a: ['Parménide', 'Plotin', 'Boèce', 'Augustin'], n: ['le temps', 'la religion'], ref: 'Le temps, « Termes essentiels » (éternité)', p: '568' }),
M('m-temp-finitude-historialite', N, "Finitude, historialité, historicité : définitions ?",
  "Finitude : caractère de ce qui est assigné à des limites indépassables, la mort en étant la marque. Historialité (Geschichtlichkeit, Heidegger) : rapport authentique à son histoire, non comme passé révolu mais comme ouverture aux possibilités d'existence héritées et à venir. Historicité : appartenance d'un fait à l'histoire.",
  { a: ['Heidegger'], n: ['le temps'], ref: 'Le temps, « Termes essentiels »', p: '569' }),
M('m-temp-present-passe-futur', N, "Présent, passé, futur, avenir : comment distinguer futur et avenir ?",
  "Les trois dimensions du temps (praesens, praeteritum, futurum), horizons dans lesquels les événements se donnent. Le futur désigne ce qui va se produire, avec une détermination implicite à partir du passé et du présent ; l'avenir désigne ce qui peut se produire, laissant place au surgissement du nouveau.",
  { n: ['le temps'], ref: 'Le temps, « Termes essentiels »', p: '569' }),
M('m-temp-sempiternite-temporalite', N, "Sempiternité, perpétuité, temporalité : définitions ?",
  "Sempiternité : ce qui dure toujours (semper + aeternitas). Perpétuité : ce qui dure sans interruption. Temporalité : la condition temporelle de l'existence et de la connaissance humaines, structure fondamentale de la réalité humaine (âme, conscience, pour-soi de Sartre, Dasein de Heidegger, qui distingue Zeitlichkeit et Temporalität).",
  { a: ['Sartre', 'Heidegger'], n: ['le temps', 'la conscience'], ref: 'Le temps, « Termes essentiels »', p: '569' }),
];
