import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Le travail (manuel, p. 605-609) ----------
M('m-trav-sens', N, "Quels sont les différents sens du mot « travail » ?",
  "L'action de transformer un matériau (travail du tailleur de pierre, de l'écrivain sur la langue) ; le résultat de cette activité ; l'emploi (perdre son travail) ; en physique, une grandeur mesurée en joules ; et le tourment ou la peine (être travaillé par une idée, entrer en travail).",
  { n: ['le travail'], ref: 'Le travail, « De l\'usage du mot à la notion »', p: '605' }),
M('m-trav-tripalium', N, "Que révèle l'étymologie de « travailler » ?",
  "Du latin populaire tripaliare, « tourmenter avec le trepalium », instrument de torture à trois pieux : le travail est souvent envisagé comme une activité impliquant une certaine violence, sur le travailleur (il réprime ses inclinations) et sur la nature (déforestation, déchets polluants).",
  { n: ['le travail', 'la nature'], ref: 'Le travail, « De l\'usage du mot à la notion »', p: '605-606' }),
M('m-trav-reflechi', N, "En quoi le travail humain est-il une activité réfléchie et productive ?",
  "Il est d'abord conçu comme un projet, puis réalisé conformément à lui ; sa fin est de produire un nouvel objet plus utile à l'homme. Il se distingue de la chasse et de la cueillette, qui consomment d'emblée les objets, et des jeux, qui visent le délassement et non l'œuvre.",
  { n: ['le travail'], ref: 'Le travail, « De l\'usage du mot à la notion »', p: '606' }),
M('m-trav-conscience-sociale', N, "Qu'est-ce que la conscience sociale ?",
  "Forme de conscience collective propre à un groupe social, manifestée par un ensemble de croyances, de sentiments et d'opinions communément partagés par ses membres.",
  { a: ['Durkheim'], n: ['le travail', 'la conscience'], ref: 'Le travail, « Termes essentiels » (conscience sociale)', p: '608' }),
M('m-trav-esclavage-servage', N, "Comment distinguer esclavage antique, servage et esclavage moderne ?",
  "Le servage remplace peu à peu l'esclavage antique au Moyen Âge : le serf, attaché à la terre (adscriptus glebae), a des droits que l'esclave n'avait pas (fonder une famille, transmettre des biens). À partir des conquêtes coloniales (XVIe siècle), l'esclavage reprend et change de nature : à sa justification économique s'ajoute une dimension raciste.",
  { n: ['le travail', 'la justice'], ref: 'Le travail, « Termes essentiels » (esclavage, servage)', p: '608' }),
M('m-trav-division', N, "Quelles sont les deux formes de la division du travail ?",
  "Division technique : dans une branche déterminée (les ateliers d'une usine). Division sociale : au niveau de la société entière, de l'économie nationale, où elle est source de solidarité sociale.",
  { n: ['le travail', "l'État"], ref: 'Le travail, « Termes essentiels » (division du travail)', p: '608' }),
M('m-trav-interet-labeur', N, "Intérêt et labeur : définitions ?",
  "Intérêt (interesse, « être partie prenante ») : une action intéressée importe à qui l'accomplit ; le travail est d'autant plus productif que le travailleur y trouve son intérêt. Labeur (laborare) : travail pénible, ingrat, lié à l'activité du laboureur.",
  { n: ['le travail'], ref: 'Le travail, « Termes essentiels »', p: '608' }),
M('m-trav-loisir', N, "Que révèle l'étymologie de « loisir » ?",
  "Du latin licere, « permettre » (comme licence) : originellement, une période où l'on pouvait faire ce qu'on voulait. Dans les sociétés anciennes, la distinction entre temps de loisir et temps de travail était moins nette : un travail voulu pouvait équivaloir à un loisir.",
  { n: ['le travail', 'la liberté'], ref: 'Le travail, « Termes essentiels » (loisir)', p: '608' }),
M('m-trav-marchandise-marche', N, "Marchandise et marché : définitions ?",
  "Marchandise : tout ce qui fait l'objet d'un échange ; Marx fonde son analyse (Le Capital) sur la distinction entre valeur d'usage et valeur d'échange. Marché : à la fois la transaction commerciale et l'espace où elle a lieu.",
  { a: ['Marx'], n: ['le travail'], o: 'Le Capital', ref: 'Le travail, « Termes essentiels »', p: '608-609' }),
M('m-trav-production-productivite', N, "Production et productivité : définitions ?",
  "Production : activité de transformation de la nature ; le travail est l'activité productive par excellence, créant des objets plus utiles ou de plus grande valeur. Productivité : rapport entre la quantité de biens ou services produits et les facteurs de production (temps de travail, coût de la main-d'œuvre, capital).",
  { n: ['le travail'], ref: 'Le travail, « Termes essentiels »', p: '609' }),
M('m-trav-reification', N, "Qu'est-ce que la réification ?",
  "Transformation de l'activité humaine en marchandise, aboutissant dans l'économie capitaliste à une véritable fétichisation de l'objet comme valeur d'échange, qui domine et éclipse la valeur d'usage.",
  { a: ['Marx'], n: ['le travail'], ref: 'Le travail, « Termes essentiels » (réification)', p: '609' }),
];
