import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Références culturelles : mythe et tragédie (manuel, p. 776-781) ----------
M('m-myth-definition', N, "Qu'est-ce qu'un mythe, et quel rapport a-t-il avec la vérité ?",
  "Récit légendaire d'événements survenus dans un passé immémorial, mettant en scène héros, dieux, démons. Imaginaire mais non sans rapport à la vérité : il représente de façon figurée des réponses aux questions fondamentales sur la condition humaine. Platon critique les fables des poètes mais recourt lui-même au mythe comme procédé argumentatif.",
  { a: ['Platon'], n: ['la religion', 'la vérité'], ref: 'Références culturelles, « Mythe et tragédie »', p: '776' }),
M('m-myth-muthos-logos', N, "Comment le sens de muthos a-t-il évolué par rapport à logos ?",
  "Chez Homère, muthos est la « parole » rapportant ce qui s'est réellement produit et doit être vénérée. À l'époque classique (Ve s. av. J.-C.), avec les premiers historiens (Hérodote, Thucydide), il signifie « histoire merveilleuse, fable » et s'oppose à logos, le discours vérifiable, raisonnable et argumenté.",
  { n: ['la religion', 'le langage', 'la raison'], ref: 'Références culturelles, « Mythe et tragédie »', p: '776' }),
M('m-myth-otto-veyne', N, "Que soutiennent W. F. Otto et Paul Veyne sur le mythe ?",
  "Otto : logos et ratio n'engagent que notre commerce utilitaire avec les choses ; le mythe s'adresse à l'homme tout entier, à son attitude dans l'existence. Veyne (Les Grecs ont-ils cru à leurs mythes ?) : le mythe est un renseignement sur des événements précis, détenu par des gens « renseignés » (les Muses), avant que l'enquête historique et la physique spéculative ne le concurrencent.",
  { a: ['Otto', 'Veyne'], n: ['la religion', 'la vérité'], ref: 'Références culturelles, « Mythe et tragédie » (textes 563-564)', p: '776-777' }),
M('m-myth-cosmogonies', N, "Quels mythes cosmogoniques le manuel cite-t-il ?",
  "Babylone (vers 1700 av. J.-C.), Poème de la Création : Marduk devient roi des dieux et crée le monde en ouvrant le cadavre de la Mère primordiale. Genèse : deux récits de la Création (Gn I, plus récent ; second, antérieur au VIe s.). Hésiode (Théogonie) : Terre, Chaos, Amour. Platon (Timée) : le démiurge ordonne le chaos sensible en regardant les Formes intelligibles, « mythe vraisemblable ».",
  { a: ['Hésiode', 'Platon'], n: ['la religion', 'la nature'], ref: 'Références culturelles, « Mythe et tragédie »', p: '777-778' }),
M('m-myth-oedipe-legende', N, "Que raconte la légende d'Œdipe (version de Sophocle) ?",
  "Abandonné enfant (« au pied enflé ») car l'oracle annonçait qu'il tuerait son père Laïos et épouserait sa mère Jocaste, il est adopté, débarrasse Thèbes de la Sphinge, puis accomplit la prophétie à son insu. Ses fils Étéocle et Polynice s'entretueront, sa fille Antigone sera murée vivante pour avoir voulu enterrer Polynice malgré Créon.",
  { a: ['Sophocle'], n: ['la religion', "l'inconscient"], o: 'Œdipe-Roi', ref: 'Références culturelles, « Mythe et tragédie »', p: '778' }),
M('m-myth-oedipe-levi-strauss', N, "Comment Lévi-Strauss analyse-t-il le mythe d'Œdipe ?",
  "Il le décompose en « paquets de relations » qui s'opposent deux à deux par analogie : parenté surévaluée / sous-estimée, homme qui doit soumettre la terre / enraciné dans la terre. Le mythe a une logique : « fournir un modèle logique pour résoudre une contradiction » (Anthropologie structurale).",
  { a: ['Lévi-Strauss'], n: ['la religion', 'le langage'], o: 'Anthropologie structurale', ref: 'Références culturelles, « Mythe et tragédie » (texte 566)', p: '778-779' }),
M('m-myth-oedipe-freud', N, "Comment Freud interprète-t-il le mythe d'Œdipe ?",
  "Comme la formulation indirecte d'une loi du psychisme : tout enfant passe par une phase d'attirance pour le parent de sexe opposé et de crainte-jalousie envers l'autre. L'interdit de l'inceste et du meurtre fonde toute civilisation ; qui ne vient pas à bout du complexe d'Œdipe est voué à la névrose (Trois essais, note de 1920).",
  { a: ['Freud'], n: ["l'inconscient", 'la religion'], o: 'Trois essais sur la théorie sexuelle', ref: 'Références culturelles, « Mythe et tragédie » (texte 567)', p: '779' }),
M('m-trag-definition', N, "Qu'est-ce que la tragédie athénienne, et quelle est sa source ?",
  "Genre du Ve siècle av. J.-C. produisant plaisir esthétique et « épuration » (katharsis, Aristote) des passions, mais aussi effort de l'homme pour représenter sa condition souffrante et prendre en charge son destin. Sur 31 tragédies conservées (7 d'Eschyle, 7 de Sophocle, 17 d'Euripide), seules Les Perses (472) portent sur un événement historique ; les autres puisent dans la mythologie.",
  { a: ['Aristote', 'Eschyle', 'Sophocle', 'Euripide'], n: ["l'art", 'la religion'], ref: 'Références culturelles, « Mythe et tragédie »', p: '779-780' }),
M('m-trag-faute-hybris', N, "Quelle est la « faute » du héros tragique ?",
  "Une faute pas nécessairement volontaire (Œdipe ignore l'identité de Laïos et de Jocaste ; Oreste est poussé par Apollon ; Antigone se demande si elle s'est trompée), qui l'oppose aux dieux par démesure (hybris) : il enfreint la sagesse qui veut que l'on se connaisse soi-même et sache que l'on n'est ni animal ni dieu. Il souffre et est châtié.",
  { a: ['Sophocle', 'Eschyle'], n: ['la religion', 'le devoir'], ref: 'Références culturelles, « Mythe et tragédie »', p: '780' }),
M('m-trag-role-politique', N, "Quel est le rôle politique de la tragédie (Œdipe à Colone, Les Euménides) ?",
  "Le héros est sacrifié comme victime pour le bien de la cité (la peste doit cesser à Thèbes) ; dans Œdipe à Colone, il devient une figure bénéfique que les cités se disputent pour l'ensevelir. Dans Les Euménides (Orestie, 458), les Érinyes pardonnent Oreste et deviennent les « Bienveillantes » : réconciliation de la cité et des dieux (cf. o felix culpa).",
  { a: ['Sophocle', 'Eschyle'], n: ['la religion', "l'État"], ref: 'Références culturelles, « Mythe et tragédie »', p: '780-781' }),
];
