import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Références culturelles : histoire des conceptions de la science (manuel, p. 782-793) ----------
M('m-hsci-antique-1', N, "Quelles sont les principales caractéristiques de la conception antique de la science ?",
  "Née en Grèce avec la démonstration mathématique (Euclide, Éléments, IIIe s. av. J.-C.). Pas de science par la sensation (impressions variables, singulières) ; approche presque exclusivement théorique ; recherche des causes plus que des lois. Aristote : l'objet de la science est nécessaire et éternel.",
  { a: ['Aristote', 'Euclide'], n: ['la science'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science »', p: '783' }),
M('m-hsci-antique-2', N, "Comment la science antique se rapporte-t-elle à la technique et au réel ?",
  "Elle se développe de manière autonome, distincte des savoirs techniques (la mécanique est méprisée, Archimède « s'excuse »). Le réel est hiérarchisé, qualitativement différencié (monde supra-lunaire circulaire éternel / monde sub-lunaire). Science, sagesse et philosophie sont liées ; modèles : la géométrie d'Euclide, l'Almageste de Ptolémée.",
  { a: ['Archimède', 'Ptolémée'], n: ['la science', 'la technique'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science »', p: '783-784' }),
M('m-hsci-medievale-salut', N, "Comment la science médiévale se subordonne-t-elle à la foi ?",
  "L'homme est sur terre pour faire son salut, non pour une curiosité savante ; la science est encouragée si elle glorifie la sagesse divine (« Dieu a tout disposé en ordre, nombre et mesure »). Paul oppose la sagesse de Dieu à celle du monde ; Bonaventure voit dans les créatures un chemin vers Dieu. Augustin réserve « sagesse » aux choses divines, « science » aux humaines.",
  { a: ['Paul de Tarse', 'Augustin', 'Bonaventure'], n: ['la science', 'la religion'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science » (textes 570-574)', p: '784-785' }),
M('m-hsci-medievale-doctrinale', N, "Quelle approche du savoir domine au Moyen Âge (vérité révélée, arts libéraux) ?",
  "Le cadre de la vérité est fixé par la science sacrée révélée par les Écritures (Église, synagogue, pouvoirs musulmans) : approche doctrinale, foi avant interprétation rationnelle (théologie). Trivium (grammaire, rhétorique, dialectique) puis quadrivium (arithmétique, géométrie, musique, astronomie) séparent arts libéraux et arts mécaniques, d'où l'éloignement de la science et de la technique.",
  { n: ['la science', 'la religion', 'la technique'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science »', p: '785-786' }),
M('m-hsci-arabe-occultisme', N, "Quel rôle jouent la civilisation arabo-musulmane et l'occultisme dans l'histoire des sciences ?",
  "Du VIIIe au XIIe siècle, la civilisation arabo-musulmane transmet les connaissances antiques à la chrétienté latine (algèbre d'Al-Khwârizmî, numération décimale empruntée à l'Inde). À la Renaissance, alchimie, astrologie, kabbale et magie, postulant un autre ordre de réalité agissant à distance, contribuent au développement des sciences modernes.",
  { a: ['Al-Khwârizmî'], n: ['la science'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science »', p: '784-786' }),
M('m-hsci-classique-maitre', N, "Comment la science de l'âge classique se rapporte-t-elle à l'utilité et à la technique ?",
  "Elle n'est plus désintéressée : elle vise à rendre l'homme « comme maître et possesseur de la nature » (Descartes) ; Bacon : le but vrai de la science est de doter la vie humaine de nouvelles inventions et richesses. Elle accompagne l'imprimerie et l'essor du capitalisme ; Galilée, Descartes, Huygens, Newton ne confondent pourtant pas science et technique (Séris).",
  { a: ['Descartes', 'Bacon', 'Séris'], n: ['la science', 'la technique'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science » (texte 575)', p: '786-787' }),
M('m-hsci-classique-experimentation', N, "Comment l'expérimentation change-t-elle à l'âge classique ?",
  "Elle n'est plus naïve mais liée à la théorie qu'elle confirme, avec des instruments de mesure précis (lunette de 1609, microscope) ; elle devient source de droit pour la connaissance et supplante l'autorité des doctrines reçues (Pascal, expériences sur le vide). On passe « du monde de l'à-peu-près à l'univers de la précision » (Koyré).",
  { a: ['Pascal', 'Koyré'], n: ['la science'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science » (texte 576)', p: '787' }),
M('m-hsci-classique-mathematisation', N, "Que signifie la mathématisation de la nature à l'âge classique ?",
  "Connaître, c'est découvrir la loi universelle réglant un phénomène. Galilée (L'Essayeur) : l'univers est un livre écrit en langue mathématique. Kant : il n'y a de science proprement dite que dans la mesure où il y a de la mathématique. La nature est supposée homogène et quantifiable ; un seul univers régi par la gravitation universelle de Newton ; seul le déplacement local compte comme mouvement.",
  { a: ['Galilée', 'Kant', 'Newton'], n: ['la science', 'la nature'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science » (textes 577-580)', p: '787-788' }),
M('m-hsci-classique-systeme', N, "Quel idéal de système et d'achèvement la science classique poursuit-elle ?",
  "Une présentation ordonnée et rationnelle de l'ensemble des lois de la réalité : un système achevé et limité de principes dont on déduit les lois physiques, sans recherche progressant indéfiniment. Cette conception, reprise par le positivisme, reste vivace.",
  { a: ['Comte'], n: ['la science'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science »', p: '788' }),
M('m-hsci-contemporaine-construit', N, "Pourquoi la science contemporaine construit-elle ses faits (Marx, Bachelard, Popper) ?",
  "Liée à la production industrielle (Marx : la science est mise au service du capital, richesse dépendant du progrès technologique), elle est orientée vers des faits construits, triés et élaborés avec un lourd appareillage (accélérateurs de particules). Bachelard : « un monde à construire ». Popper : les théories sont notre œuvre, nous allons vers le monde avec elles.",
  { a: ['Marx', 'Bachelard', 'Popper'], n: ['la science', 'la technique'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science » (textes 581-583)', p: '789-790' }),
M('m-hsci-contemporaine-lois', N, "Que pense-t-on de l'explication par les lois (Comte, Meyerson) ?",
  "Comte : l'esprit humain renonce à chercher l'origine et les causes intimes pour découvrir les lois effectives, relations invariables de succession et de ressemblance. Meyerson : la loi permet la prévision et l'action, mais ne contente pas l'esprit qui cherche une explication. La prédiction repose sur un déterminisme parfois probabiliste ; théorie et pratique se rapprochent.",
  { a: ['Comte', 'Meyerson'], n: ['la science'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science » (textes 584-585)', p: '790' }),
M('m-hsci-contemporaine-methode', N, "Quelle place la méthode et la spécialisation occupent-elles dans la science contemporaine ?",
  "Primauté de la méthode : Nietzsche voit la victoire de la méthode scientifique sur la science. Hyperspécialisation : Heidegger y voit la raison du progrès de la recherche ; Bachelard, l'actualisation d'une culture plus large ; Heidegger et Hersch déplorent la perte du rapport à la vérité de l'expérience ; Thom note que l'équipement de laboratoire dicte souvent l'expérience.",
  { a: ['Nietzsche', 'Heidegger', 'Bachelard', 'Hersch', 'Thom'], n: ['la science'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science » (textes 586-591)', p: '790-792' }),
M('m-hsci-contemporaine-technoscience', N, "Qu'est-ce que la technoscience, et que dit Putnam du scientisme ?",
  "Amalgame de science et de technique pour qualifier les activités de la science moderne. Ellul : la science est devenue moyen de la technique, qui est au cœur même de la science. Putnam : le scientisme n'est pas le respect de la science, mais l'incapacité de distinguer la science des laboratoires de la plus utopique des réflexions.",
  { a: ['Ellul', 'Putnam', 'Heidegger'], n: ['la science', 'la technique'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science » (textes 593-596)', p: '792-793' }),
M('m-hsci-physique-xx', N, "Quelle remise en cause la physique du XXe siècle apporte-t-elle ?",
  "La physique relativiste et quantique remet en cause les principes de la physique classique. Poincaré (1902) se demande si l'on pourra encore exprimer les lois de la nature sous forme d'équations différentielles, ce qui semblait inséparable de la notion de loi naturelle.",
  { a: ['Poincaré'], n: ['la science'], ref: 'Références culturelles, « Histoire des différentes conceptions de la science » (texte 592)', p: '792' }),
];
