import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- L'art (manuel, p. 102-106) ----------
M('m-art-mot', N, "Quels sens le mot « art » recouvre-t-il, et de quel mot grec hérite-t-il ?",
  "Du latin ars : manière d'être, savoir-faire, talent, métier, science, toujours avec compétence et maîtrise. Il hérite du grec technê (d'où « technique »). Le sens esthétique (plaisir désintéressé devant l'œuvre) a peu à peu pris le pas sur les autres.",
  { n: ["l'art", 'la technique'], ref: 'L\'art, « De l\'usage du mot à la notion »', p: '102' }),
M('m-art-nature', N, "Quelle formule d'Aristote est à l'origine de la doctrine de l'imitation de la nature ?",
  "Dans la Physique, l'art imite la nature (ou l'achève) : les œuvres de l'art n'ont pas en elles le principe de leur existence, contrairement aux êtres naturels. Cette formule est devenue un mot d'ordre de l'histoire de l'art, à l'origine du réalisme au XIXe siècle.",
  { a: ['Aristote'], n: ["l'art", 'la nature'], o: 'Physique', ref: 'L\'art, « De l\'usage du mot à la notion »', p: '102' }),
M('m-art-artiste-artisan', N, "Depuis quand distingue-t-on l'artiste de l'artisan ?",
  "Depuis le XVIIIe siècle : « beaux-arts » (art de l'artiste créateur, génie inimitable) contre « arts et métiers » (savoir technique de l'artisan, transmissible). Le fossé remonte à l'apparition, à la Renaissance, de l'artiste indépendant des corporations. L'allemand Kunst (de können, « savoir ») a pu renforcer la valeur esthétique du mot.",
  { n: ["l'art", 'la technique', 'le travail'], ref: 'L\'art, « De l\'usage du mot à la notion »', p: '102-103' }),
M('m-art-artiste-postures', N, "Entre quelles deux postures l'artiste moderne oscille-t-il ?",
  "Créateur d'un monde séparé (art pour l'art, retrait hors du monde profane, « vie mutilée » selon Adorno) ou artiste « engagé » qui veut révolutionner la société, quitte à nier l'art (refus du chef-d'œuvre et de l'harmonie). S'y ajoute la transformation des œuvres en produits culturels de consommation de masse.",
  { a: ['Adorno'], n: ["l'art"], ref: 'L\'art, « De l\'usage du mot à la notion »', p: '103' }),
M('m-art-aura', N, "Qu'est-ce que l'aura d'une œuvre d'art (Benjamin) ?",
  "La propriété de l'œuvre de ne pouvoir être ni reproduite ni répétée : unique, authentique, parfois sacrée. Elle correspond à une époque où l'art avait une dimension cultuelle, avant les œuvres mécaniquement reproductibles (photographie, cinéma).",
  { a: ['Benjamin'], n: ["l'art", 'la technique'], o: "L'Œuvre d'art à l'époque de sa reproduction mécanisée", ref: 'L\'art, « Termes essentiels » (aura)', p: '104' }),
M('m-art-arts-mecaniques', N, "Que sont les « arts mécaniques » ?",
  "Au départ la photographie et le cinéma (fin du XIXe siècle), fondés sur des opérations accomplies par des machines ; aujourd'hui on y ajoute les arts utilisant vidéo, cédérom, multimédia, internet.",
  { n: ["l'art", 'la technique'], ref: 'L\'art, « Termes essentiels » (arts mécaniques)', p: '104' }),
M('m-art-beau', N, "Comment Kant et Hegel définissent-ils le beau ?",
  "Kant : ce qui plaît universellement sans concept (plaisir de l'esprit, désintéressé, non réductible à l'agréable des sens). Hegel : la beauté, indissociable de l'idée comme idéal, est « le rayonnement sensible de l'idée » (Esthétique).",
  { a: ['Kant', 'Hegel'], n: ["l'art"], ref: 'L\'art, « Termes essentiels » (beau)', p: '104' }),
M('m-art-beaux-arts', N, "Que désignent les « beaux-arts » et quand le concept apparaît-il ?",
  "L'ensemble des pratiques sans visée utilitaire, ayant pour but de représenter le beau : arts plastiques (architecture, sculpture, peinture) et arts musicaux ou rythmiques (musique, danse, poésie). Le concept apparaît au XVIIIe siècle, quand l'art, affranchi de la religion, est contemplé, exposé, enseigné ; le romantisme le conteste dès le XIXe.",
  { n: ["l'art"], ref: 'L\'art, « Termes essentiels » (beaux-arts)', p: '104' }),
M('m-art-esthetique', N, "Que signifie « esthétique » ?",
  "Du grec aisthêsis (sensation) : discipline qui s'occupe de l'art et des jugements sur les œuvres, terme forgé par Baumgarten à la fin du XVIIIe siècle pour la science du beau. Chez Kant, il désigne aussi la doctrine de la sensibilité en général.",
  { a: ['Kant'], n: ["l'art"], ref: 'L\'art, « Termes essentiels » (esthétique)', p: '106' }),
M('m-art-genie', N, "Comment Kant redéfinit-il le génie ?",
  "Du latin genius (dieu propre à chaque homme) : d'abord inspiration divine. Pour Kant, faculté de produire des objets de beaux-arts et de créer les règles de leur exécution : la nouveauté tient au talent, à la capacité de rassembler des formes sous une règle inédite, non à une inspiration surhumaine.",
  { a: ['Kant'], n: ["l'art"], ref: 'L\'art, « Termes essentiels » (génie)', p: '106' }),
M('m-art-gout', N, "Comment Diderot et Kant définissent-ils le goût ?",
  "Diderot (Essai sur la peinture, 1765) : facilité acquise par des expériences répétées à saisir le vrai ou le bon avec la circonstance qui le rend beau. Kant : faculté de juger le beau, sans aucun intérêt, par une satisfaction ou une insatisfaction ; le désintéressement rend le sentiment universellement communicable.",
  { a: ['Diderot', 'Kant'], n: ["l'art"], ref: 'L\'art, « Termes essentiels » (goût)', p: '106' }),
M('m-art-jugement-reflechissant', N, "Qu'est-ce que le jugement réfléchissant chez Kant ?",
  "Type de jugement qui remonte du particulier au général et qui s'applique à la faculté du sujet de ressentir du plaisir : le jugement esthétique.",
  { a: ['Kant'], n: ["l'art"], o: 'Critique de la faculté de juger', ref: 'L\'art, « Termes essentiels » (jugement réfléchissant)', p: '106' }),
M('m-art-medium-sublime', N, "Que sont le médium (Greenberg) et le sublime (Kant) ?",
  "Médium : le support propre à chaque art (surface, lignes et couleurs pour la peinture ; mot pour la littérature ; son pour la musique). Sublime : sentiment esthétique, avec le beau, où l'on éprouve les limites de l'imagination devant l'immensité (sublime mathématique) ou la puissance (sublime dynamique).",
  { a: ['Greenberg', 'Kant'], n: ["l'art"], ref: 'L\'art, « Termes essentiels » (médium, sublime)', p: '106' }),

// ---------- Le bonheur (manuel, p. 143-146) ----------
M('m-bonh-fin-derniere', N, "Pourquoi le bonheur est-il une fin dernière ?",
  "Il est désiré pour lui-même, non comme moyen d'autre chose (on désire l'argent pour le luxe, le luxe pour le plaisir). Fin en soi, il réside dans le contentement de la totalité des désirs, au-delà de la visée immédiate de chacun.",
  { n: ['le bonheur'], ref: 'Le bonheur, « De l\'usage du mot à la notion »', p: '143' }),
M('m-bonh-kant-definition', N, "Quelle définition du bonheur Kant donne-t-il, et pourquoi n'est-il qu'un « idéal de l'imagination » ?",
  "Critique de la raison pure : satisfaction de toutes nos inclinations en extension (multiplicité), en intensité (degré) et en protension (durée). Mais l'homme ne peut cesser durablement de désirer : le bonheur ainsi conçu est un idéal de l'imagination (Fondements de la métaphysique des mœurs).",
  { a: ['Kant'], n: ['le bonheur'], ref: 'Le bonheur, « De l\'usage du mot à la notion »', p: '143' }),
M('m-bonh-etymologie', N, "Que révèle l'étymologie de « bonheur » ?",
  "Bonum augurium (« de bon augure ») : lien avec le hasard et la chance, comme pour « malheur ». Le bonheur semble un don reçu plus que le fruit de la conduite. Mais en entendant augere (« augmenter »), on y lit aussi l'idée d'accroissement.",
  { n: ['le bonheur'], ref: 'Le bonheur, « De l\'usage du mot à la notion »', p: '143' }),
M('m-bonh-ascese', N, "Que désigne l'ascèse dans la philosophie ancienne ?",
  "Du grec askêsis, « exercice » : discipline de vie visant l'autarcie de l'âme par l'expérimentation sur soi et l'indifférence aux plaisirs et aux peines. Ce n'est pas le rigorisme du salut par la souffrance : le stoïcien se concentre sur l'instant présent, l'épicurien discipline ses désirs (tétrapharmakos).",
  { n: ['le bonheur'], ref: 'Le bonheur, « Termes essentiels » (ascèse)', p: '144' }),
M('m-bonh-autarcie-ataraxie', N, "Autarcie et ataraxie : définitions ?",
  "Autarcie (autos, arkein) : état d'autosuffisance d'un individu ou d'un groupe qui satisfait ses besoins sans aide extérieure. Ataraxie (a privatif + tarassô, « troubler ») : absence de troubles ; sceptiques, stoïciens et épicuriens y voient le bonheur.",
  { n: ['le bonheur'], ref: 'Le bonheur, « Termes essentiels » (autarcie, ataraxie)', p: '144' }),
M('m-bonh-beatitude-felicite', N, "Béatitude, félicité, contentement, bienheureux : nuances ?",
  "Béatitude : satisfaction complète et permanente (l'état du sage, puis du bonheur éternel en théologie chrétienne). Félicité : contentement intense qui dépendrait des circonstances extérieures (féliciter). Contentement : satisfaction, parfois restrictive (« se contenter de »). Bienheureux : profondément heureux.",
  { n: ['le bonheur'], ref: 'Le bonheur, « Termes essentiels »', p: '144' }),
M('m-bonh-eudemonisme-hedonisme', N, "Eudémonisme, hédonisme, utilitarisme : définitions ?",
  "Eudémonisme : le bonheur est la fin ultime de la vie (morales antiques ; Kant critique : la morale enseigne à s'en rendre digne, non à l'atteindre). Hédonisme (hédonê) : le plaisir est le souverain bien. Utilitarisme : l'utilité fonde toutes les valeurs (Bentham, Stuart Mill).",
  { a: ['Kant', 'Bentham', 'Mill'], n: ['le bonheur'], ref: 'Le bonheur, « Termes essentiels »', p: '144-146' }),
M('m-bonh-fortune-souverain-bien', N, "Que signifient fortune et souverain bien ?",
  "Fortune (fortuna) : le sort, ce qui arrive par hasard ; « faire fortune » : maîtriser le hasard par la richesse. Souverain bien : le bien le plus haut, fin ultime et en soi de l'activité humaine, souvent identifié au bonheur, conçu comme état intérieur au sujet.",
  { n: ['le bonheur'], ref: 'Le bonheur, « Termes essentiels »', p: '144-145' }),
M('m-bonh-vertu-sagesse', N, "Vertu, sagesse, rigorisme, modération : définitions ?",
  "Vertu : force intérieure qui rend apte à bien remplir son rôle, qualité morale conforme aux règles religieuses et sociales. Sagesse (sophia) : idéal de perfection intellectuelle et morale, figure du sage bienheureux. Rigorisme : primat de la vertu sur le plaisir. Modération : limitation de ses désirs.",
  { n: ['le bonheur', 'le devoir'], ref: 'Le bonheur, « Termes essentiels »', p: '145-146' }),
];
