import { M } from './dsl.mjs';
const T = 'methode';
export default [
// ---------- Conseils pour la dissertation et l'explication de texte (manuel, p. 807-812) ----------
M('m-meth-diss-face', T, "Que signifie « faire face à la question » dans une dissertation ?",
  "Ne pas réciter son cours ni dresser un catalogue de références, ne pas esquiver la question en la déplaçant, ni ramener trop vite le sujet à des éléments connus (fiches, manuels). Il faut un effort de problématisation propre au sujet, et chaque moment de la copie doit pouvoir être relié à la question posée.",
  { n: ['la raison'], ref: 'Conseils pour la dissertation et l\'explication de texte, « La dissertation »', p: '807-808' }),
M('m-meth-diss-problematique', T, "Qu'est-ce que la problématique d'une dissertation, et d'où part-elle ?",
  "La manière dont la question va être traitée et approfondie, qui donne au sujet son sens philosophique et détermine le plan et l'ordre logique des questions. Elle part d'une analyse préalable (non écrite dans la copie) de tous les termes du sujet, le libellé étant une donnée brute à interpréter. Un même sujet admet des problématisations très différentes.",
  { n: ['la raison'], ref: 'Conseils pour la dissertation et l\'explication de texte, « La dissertation »', p: '808' }),
M('m-meth-diss-petits-mots', T, "Pourquoi analyser les « petits mots » du sujet (« peut-on », « doit-on ») ?",
  "Ils servent de clé pour construire la problématique. Ex. « peut-on » : possibilité contingente, aptitude ou faculté (réalisée ou non chez le sujet), faculté qui définit l'être (l'homme peut parler). Il faut aussi distinguer la question posée de questions voisines (« peut-on souhaiter accomplir tous ses désirs ? » n'est pas « peut-on les accomplir ? »).",
  { n: ['le langage', 'la raison'], ref: 'Conseils pour la dissertation et l\'explication de texte, « La dissertation »', p: '808' }),
M('m-meth-diss-plan', T, "Quels plans faut-il éviter, et que doit être un bon plan ?",
  "Éviter le plan par auteurs (doctrine après doctrine), les plans passe-partout (« oui-non-mais », thèse-antithèse-synthèse) et la simple définition des termes par partie (qu'est-ce que la vérité ? qu'est-ce qu'une preuve ?). Viser un parcours dont les étapes procèdent logiquement l'une de l'autre, du plus évident au moins évident, en critiquant l'opinion spontanée.",
  { n: ['la raison', 'la vérité'], ref: 'Conseils pour la dissertation et l\'explication de texte, « La dissertation »', p: '808' }),
M('m-meth-diss-introduction', T, "Quelles sont les trois étapes de l'introduction d'une dissertation ?",
  "1. Amener le sujet en montrant en quoi le problème se pose. 2. Recopier la question dans les termes mêmes du sujet (la modifier risque de changer les données). 3. Expliquer comment le sujet sera traité, éventuellement en développant la problématique sous forme de questions, en montrant où l'on va et dans quel ordre.",
  { n: ['la raison'], ref: 'Conseils pour la dissertation et l\'explication de texte, « La rédaction »', p: '809' }),
M('m-meth-diss-developpement', T, "Quels conseils donne-t-on pour le développement et la conclusion d'une dissertation ?",
  "Développement : avancer des hypothèses et les discuter plutôt que d'asséner des évidences ; caractériser les concepts de façon provisoire ; utiliser les exemples pour approfondir la question ; ne pas se ranger derrière une doctrine ni ramener le sujet à l'actualité. Conclusion : faire le bilan de ce qui a été gagné et formuler nettement une réponse.",
  { n: ['la raison'], ref: 'Conseils pour la dissertation et l\'explication de texte, « La rédaction »', p: '809-810' }),
M('m-meth-texte-attentes', T, "Que doit rendre compte l'explication de texte ?",
  "Du texte dans sa logique générale et dans le détail de son argumentation : lecture analytique (le texte a été travaillé dans le détail) pour en dégager la problématique (aspect synthétique), identifier la thèse centrale et la structure argumentative. On ne demande pas de reconstituer la doctrine de l'auteur : le texte doit être intelligible par lui-même.",
  { n: ['le langage', 'la raison'], ref: 'Conseils pour la dissertation et l\'explication de texte, « L\'explication de texte »', p: '811' }),
M('m-meth-texte-questions', T, "Quelles six questions se poser avant de rédiger une explication de texte ?",
  "1. De quoi parle le texte (thème précis) ? 2. Quel est son problème central (la question à laquelle il répond) ? 3. Quelle est sa thèse ? 4. Quelles sont les étapes de l'argumentation ? 5. Quels procédés d'argumentation (déduction, analogie, réfutation, exemple, raisonnement par l'absurde…) ? 6. Quels présupposés et quels enjeux ?",
  { n: ['le langage', 'la raison'], ref: 'Conseils pour la dissertation et l\'explication de texte, « L\'explication de texte »', p: '812' }),
M('m-meth-texte-redaction', T, "Comment rédiger une explication de texte (introduction, développement, conclusion) ?",
  "Introduction : le thème précis, le problème philosophique (sous forme de question), la progression du texte. Développement : suivre l'ordre du texte, commenter le détail de l'argumentation, faire ressortir les arguments implicites (présupposés), se demander pourquoi tel terme plutôt qu'un autre, avancer objections et contre-exemples. Conclusion : récapituler les acquis, les enjeux et la spécificité du traitement.",
  { n: ['le langage', 'la raison'], ref: 'Conseils pour la dissertation et l\'explication de texte, « L\'explication de texte »', p: '812' }),
M('m-meth-texte-lecture', T, "Comment lire le texte avant l'explication ?",
  "Attentivement et plusieurs fois, de manière d'abord synthétique, sans souligner dès les premières lectures (pour ne pas figer sa première impression) ; le sens ne « saute » pas aux yeux, et il faut se méfier du sentiment d'avoir immédiatement compris : la compréhension résulte d'un effort de clarification.",
  { n: ['le langage'], ref: 'Conseils pour la dissertation et l\'explication de texte, « L\'explication de texte »', p: '811-812' }),
];
