import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- La conscience (manuel, p. 171-176) ----------
M('m-cons-deux-sens', N, "Quelles sont les deux grandes significations de la conscience ?",
  "Sens psychologique : représentations portant sur des faits (ce qui est, a été, pourrait être). Sens moral : jugements de valeur sur ce qui doit être (bien/mal, juste/injuste), « juge intérieur ». La conscience morale présuppose la première : l'immoral n'est pas privé de conscience psychologique, il ne discerne plus le bien du mal.",
  { n: ['la conscience', 'le devoir'], ref: 'La conscience, « De l\'usage du mot à la notion »', p: '171-172' }),
M('m-cons-etymologie', N, "Que suggère l'étymologie de « conscience » ?",
  "Conscientia (cum + scientia) : « accompagné de savoir ». La conscience ajoute à un fait (état du corps, action) une connaissance immédiate de ce fait : quand j'agis, je sais que j'agis. On peut toutefois parler de faits psychiques accompagnés de conscience plutôt que d'une entité autonome.",
  { n: ['la conscience'], ref: 'La conscience, « De l\'usage du mot à la notion »', p: '172' }),
M('m-cons-behaviorisme', N, "Que pense le behaviorisme de la notion de conscience ?",
  "Watson, son fondateur, tient la conscience pour un « vieux concept » inutile, dernier avatar de l'âme : le béhavioriste n'a pas plus à s'en occuper que le chimiste de l'alchimie. La psychologie doit étudier les conduites objectivement constatables, les phénomènes internes n'étant que des faits corporels.",
  { a: ['Watson'], n: ['la conscience'], ref: 'La conscience, « Termes essentiels » (behaviorisme)', p: '172-174' }),
M('m-cons-ame', N, "Que désigne « âme » et pourquoi le mot a-t-il été supplanté ?",
  "Anima (grec psychê) : principe vivant distinguant un corps animé d'un corps inerte, fortement connoté métaphysiquement et religieusement (immortalité, métempsycose). Il a été supplanté au XIXe siècle, sous l'influence de la psychologie positive, par conscience, représentation, psychisme.",
  { n: ['la conscience', 'la religion'], ref: 'La conscience, « Termes essentiels » (âme)', p: '174' }),
M('m-cons-aperception', N, "Qu'appelle-t-on aperception (Leibniz, Kant) ?",
  "Mot forgé par Leibniz : faculté de prendre conscience de ses perceptions. Comme elle suppose une connaissance réflexive, Kant l'a repris pour désigner la conscience de soi.",
  { a: ['Leibniz', 'Kant'], n: ['la conscience'], ref: 'La conscience, « Termes essentiels » (aperception)', p: '174' }),
M('m-cons-cogito', N, "Que désigne le cogito et quelle formule de Descartes l'exprime ?",
  "Le « je pense » : principe fondamental de la philosophie cartésienne, souvent associé à l'autonomie de la conscience. Méditations métaphysiques : « Je suis, j'existe » est nécessairement vrai chaque fois que je le prononce ou le conçois.",
  { a: ['Descartes'], n: ['la conscience', 'la vérité'], o: 'Méditations métaphysiques', ref: 'La conscience, « Termes essentiels » (cogito)', p: '174' }),
M('m-cons-conscience-de-soi', N, "Qu'est-ce que la conscience de soi en philosophie, et quelle formule de Kant l'illustre ?",
  "La dimension de toute conscience d'être conscience d'un moi qui se saisit comme sujet de ses représentations. Kant : le « je pense » doit pouvoir accompagner toutes mes représentations ; il est dit transcendantal.",
  { a: ['Kant'], n: ['la conscience'], ref: 'La conscience, « Termes essentiels » (conscience de soi)', p: '174' }),
M('m-cons-doute', N, "Quels sont les trois sens du doute ?",
  "1) Psychologique : incertitude subie. 2) Sceptique (Pyrrhon, Montaigne) : suspension volontaire du jugement, visant l'indifférence. 3) Cartésien : méthodique, instrument de connaissance qui rejette comme faux tout ce qu'on peut supposer douteux ; il dégage le cogito, première vérité indubitable.",
  { a: ['Pyrrhon', 'Montaigne', 'Descartes'], n: ['la conscience', 'la vérité'], ref: 'La conscience, « Termes essentiels » (doute)', p: '174' }),
M('m-cons-intersubjectivite', N, "Qu'est-ce que l'intersubjectivité (Husserl) ?",
  "La dimension de la vie psychique qui ouvre le sujet aux autres subjectivités : elle appartient structurellement à toute vie consciente. Husserl : si l'on éliminait par la pensée tous les autres hommes, le monde perdrait son sens d'être pour moi.",
  { a: ['Husserl'], n: ['la conscience'], ref: 'La conscience, « Termes essentiels » (intersubjectivité)', p: '174' }),
M('m-cons-phenomenologie', N, "Qu'est-ce que la phénoménologie selon Husserl ?",
  "La science qui décrit, par la réflexion, l'essence des vécus de conscience (perception, imagination, souvenir), leur constitution universelle, indépendamment de toute affirmation sur l'existence d'un objet correspondant hors de la conscience.",
  { a: ['Husserl'], n: ['la conscience'], ref: 'La conscience, « Termes essentiels » (phénoménologie)', p: '174' }),
M('m-cons-solipsisme-subjectivite', N, "Solipsisme et subjectivité : que désignent-ils ?",
  "Solipsisme (solus, ipse) : thèse niant que le moi puisse accéder à la réalité d'autrui ; on serait seul au monde. Subjectivité : (1) sens courant, ce qui est relatif au sujet, opposé à l'objectivité ; (2) sens technique, la dimension dans laquelle l'homme fait l'expérience du monde, qui inclut des règles objectives (l'ordre de succession dans le temps).",
  { n: ['la conscience'], ref: 'La conscience, « Termes essentiels »', p: '174-175' }),
M('m-cons-substance', N, "Qu'est-ce que la substance ?",
  "Étymologiquement « ce qui se tient au-dessous » : ce qui n'a besoin d'aucun autre être pour être ce qu'il est, alors qu'une qualité (le blanc) suppose un sujet substantiel (une table). Elle est aussi caractérisée comme essence : ce qu'est une chose, perçue quand je reconnais « cet homme, c'est Socrate ».",
  { n: ['la conscience'], ref: 'La conscience, « Termes essentiels » (substance)', p: '175-176' }),
M('m-cons-transcendantal', N, "Transcendantal et transcendant chez Kant : quelle différence ?",
  "Transcendantal : ce qui concerne les règles selon lesquelles se forment les représentations, conditions de l'expérience (espace, temps, causalité), qui dépassent l'expérience sans être hors d'elle. Transcendant : ce qui est au-delà de toute expérience possible (les Idées de moi ou âme, Dieu, monde). Ne pas les confondre.",
  { a: ['Kant'], n: ['la conscience', 'la raison'], ref: 'La conscience, « Termes essentiels »', p: '176' }),
];
