import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Le devoir (manuel, p. 209-213) ----------
M('m-dev-definition', N, "Qu'est-ce qu'un devoir, et est-il contraignant au sens fort ?",
  "Toute action qu'on est obligé d'accomplir en vertu d'une règle obligatoire (obligation). Il ne s'impose qu'à des êtres conscients et raisonnables. La contrainte n'est pas irrésistible : le sujet reste libre de s'y soustraire, si bien que le devoir est toujours volontaire jusqu'à un certain degré.",
  { n: ['le devoir', 'la liberté'], ref: 'Le devoir, « De l\'usage du mot à la notion »', p: '209-210' }),
M('m-dev-trois-types', N, "Quels sont les trois types de devoirs, et qu'est-ce qu'une obligation parfaite ?",
  "Juridique, moral et religieux. Une obligation est parfaite quand elle donne à autrui le droit d'en exiger l'accomplissement sous peine de poursuites (devoir juridique) ; le devoir moral est une obligation imparfaite, sans contrainte extérieure. Le devoir religieux peut être l'un ou l'autre.",
  { n: ['le devoir', 'la justice', 'la religion'], ref: 'Le devoir, « De l\'usage du mot à la notion »', p: '210' }),
M('m-dev-regle-or', N, "Quelle maxime le manuel donne-t-il comme pierre de touche du devoir moral ?",
  "« Ne fais pas à autrui ce que tu ne veux pas qu'il te fasse » : le devoir moral ordonne de suivre des règles qu'on voudrait voir les autres observer. Ex. : s'interdire le mensonge, parce que si tous mentaient, on ne pourrait plus faire confiance à personne.",
  { n: ['le devoir'], ref: 'Le devoir, « De l\'usage du mot à la notion »', p: '210-211' }),
M('m-dev-autonomie', N, "Autonomie et hétéronomie chez Kant : que signifient-elles ?",
  "Autonomie (autos, nomos) : se diriger par des lois qu'on se donne soi-même. Le devoir exige une volonté autonome, qui refuse de se laisser entraîner par les désirs et les lois naturelles, lesquelles la soumettent à une législation autre que la sienne : l'hétéronomie (hetero, « autre »).",
  { a: ['Kant'], n: ['le devoir', 'la liberté'], ref: 'Le devoir, « Termes essentiels » (autonomie)', p: '212' }),
M('m-dev-imperatif', N, "Impératif catégorique et impératif hypothétique : différence ?",
  "Tout devoir est un impératif (commandement que l'esprit se donne). Catégorique : ordonne sans condition (« Fais ceci sans discuter ! »). Hypothétique : commande sous condition (« Fais ceci, si tu veux cela ! »). Distinction de Kant.",
  { a: ['Kant'], n: ['le devoir'], ref: 'Le devoir, « Termes essentiels » (impératif)', p: '212' }),
M('m-dev-ethique-morale', N, "Éthique et morale : quelle différence le manuel propose-t-il ?",
  "Éthique (ethos, « mœurs ») : discipline descriptive qui étudie les mœurs et vise la connaissance du bien et du mal. Morale (mos) : étude du bien et du mal dans une perspective universaliste, avec un caractère normatif marqué. Les deux termes ont souvent été identifiés.",
  { n: ['le devoir'], ref: 'Le devoir, « Termes essentiels » (éthique, morale)', p: '212' }),
M('m-dev-maxime', N, "En quoi la maxime diffère-t-elle du devoir (Kant) ?",
  "La maxime est une règle qu'une personne juge très importante pour sa conduite ; elle est subjective (son importance varie selon les individus). Le devoir a valeur de loi, de règle objective valable pour tous.",
  { a: ['Kant'], n: ['le devoir'], ref: 'Le devoir, « Termes essentiels » (maxime)', p: '212' }),
M('m-dev-respect', N, "Qu'est-ce que le respect chez Kant ?",
  "Un sentiment moral pur, produit uniquement par la raison (à la différence de l'inclination ou de la crainte, qui viennent de la sensibilité) : l'effet de la loi morale sur le sujet, indépendamment de l'expérience. Il ne s'applique jamais qu'à des personnes, êtres rationnels capables de liberté.",
  { a: ['Kant'], n: ['le devoir'], ref: 'Le devoir, « Termes essentiels » (respect)', p: '212-213' }),
M('m-dev-deontologie-commandement', N, "Déontologie, commandement, obligation, légalisme : définitions ?",
  "Déontologie (deon, logos) : théorie des devoirs, puis règles morales d'une profession (serment d'Hippocrate). Commandement : synonyme de devoir (voix intérieure qui ordonne). Obligation (ob + ligare) : lien juridique qui contraint à une prestation. Légalisme : obéir à la lettre sans examen critique.",
  { n: ['le devoir', 'la justice'], ref: 'Le devoir, « Termes essentiels »', p: '212-213' }),
M('m-dev-sanction-tabou-rigorisme', N, "Sanction, tabou, rigorisme (moral) : définitions ?",
  "Sanction : au sens juridique, peine ou récompense assurant l'application de la loi ; au sens courant, mesure répressive. Tabou (polynésien tapu) : interdit sacré, puis tout interdit religieux, social ou moral. Rigorisme : morale rigoureuse qui exclut tout mobile subjectif ou intérêt (contraire : laxisme).",
  { n: ['le devoir', 'la justice'], ref: 'Le devoir, « Termes essentiels »', p: '213' }),
];
