import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- L'État (manuel, p. 235-242) ----------
M('m-etat-etymologie', N, "Que révèle l'étymologie du mot « État » ?",
  "Latin status (de stare, « se tenir debout ») : ce qui est mis en place par une décision, « institué », puis le rang ou statut. Le sens politique se diffuse en français à la fin du XVe siècle. La fonction de l'État serait d'instituer la société, de l'aider à tenir debout.",
  { n: ["l'État"], ref: 'L\'État, « De l\'usage du mot à la notion »', p: '235-236' }),
M('m-etat-phenomene-historique', N, "L'État a-t-il existé de tout temps ?",
  "Non, c'est un phénomène historique : la polis grecque, la res publica ou la civitas romaine ne sont pas à proprement parler des États, pas plus que la société féodale (liens de vassal à suzerain). La notion moderne suppose de distinguer les rapports d'autorité sur les affaires communes des rapports privés, et un pouvoir doté d'une personnalité juridique.",
  { n: ["l'État"], ref: 'L\'État, « De l\'usage du mot à la notion »', p: '236-237' }),
M('m-etat-ambivalence', N, "Pourquoi le discours sur l'État est-il ambivalent ?",
  "L'État doit maintenir l'unité de la société en contenant les intérêts particuliers. Il apparaît tantôt comme l'ennemi de la société et des individus, tantôt comme un mal nécessaire protégeant les hommes contre eux-mêmes, tantôt comme l'objet d'une vénération presque sacrée, seule source de liberté, de justice et d'égalité.",
  { n: ["l'État", 'la liberté'], ref: 'L\'État, « De l\'usage du mot à la notion »', p: '237' }),
M('m-etat-anarchie', N, "Qu'est-ce que l'anarchie, et quelle définition Proudhon en donne-t-il ?",
  "Anarchie (an-arkhê, « sans commandement ») : doctrine rejetant toute organisation d'État s'imposant à l'individu (Godwin, Proudhon, Stirner, Bakounine). Proudhon : forme de gouvernement où la conscience publique ou privée, formée par la science et le droit, suffit seule au maintien de l'ordre et à la garantie des libertés.",
  { a: ['Proudhon'], n: ["l'État"], ref: 'L\'État, « Termes essentiels » (anarchie)', p: '238' }),
M('m-etat-artifice-communaute', N, "Artifice et communauté (Tönnies) : que signifient-ils ?",
  "Artifice : moyen de parvenir à une fin (si la nature n'engendre pas la société, un artifice juridique comme le contrat associe les individus). Communauté : groupe fondé sur l'instinct et le sentiment (parenté) ; la société, elle, naît de la volonté réfléchie, de l'articulation des fins et des moyens (échange, commerce) (Tönnies).",
  { a: ['Tönnies'], n: ["l'État"], ref: 'L\'État, « Termes essentiels »', p: '238' }),
M('m-etat-droit-isonomie', N, "État de droit et isonomie : définitions ?",
  "État de droit : situation où l'action de l'État est soumise à des limites juridiques, donc légitime. Isonomie (isos, nomos) : égalité de tous devant la loi, sans acception de personne ni tenue compte de la fonction ou de l'origine sociale ; caractéristique des déclarations des droits de l'homme.",
  { n: ["l'État", 'la justice'], ref: 'L\'État, « Termes essentiels »', p: '238' }),
M('m-etat-gouvernement-institution', N, "Gouvernement et institution : définitions ?",
  "Gouvernement : ensemble des institutions permettant au souverain d'exercer son autorité. Institution : au sens large, lois et principes régissant la vie sociale ; plus restreint, formes d'exercice des fonctions publiques (école, administration, justice) ; aussi coutumes et manières de penser.",
  { n: ["l'État"], ref: 'L\'État, « Termes essentiels »', p: '238' }),
M('m-etat-liberalisme', N, "Que distingue-t-on dans le libéralisme ?",
  "Libéralisme économique : limitation de l'intervention de l'État dans l'économie. Libéralisme politique : défense des libertés politiques (expression, mouvement, presse).",
  { n: ["l'État", 'la liberté'], ref: 'L\'État, « Termes essentiels » (libéralisme)', p: '238' }),
M('m-etat-nation-puissance', N, "Nation, puissance, souveraineté : définitions ?",
  "Nation : groupe déterminé par des conditions naturelles et spirituelles (langue, valeurs, histoire), identifié depuis la Révolution française au peuple seul souverain. Puissance : capacité d'agir ; détentrice de l'autorité dans l'État, elle est le pouvoir. Souveraineté : pouvoir détenu de droit, avec deux caractères : légitimité et étendue.",
  { n: ["l'État"], ref: 'L\'État, « Termes essentiels »', p: '239' }),
M('m-etat-representation-republique', N, "Représentation et république : que désignent-elles ?",
  "Représentation : technique instituant un souverain ou un gouvernement à l'image des gouvernés, qui confèrent à leur représentant la capacité de vouloir en leur nom (sans identité stricte des volontés). République (res publica) : « la chose publique », donc l'État ; sens moderne : régime représentatif, sans chef héréditaire.",
  { n: ["l'État"], ref: 'L\'État, « Termes essentiels »', p: '239' }),
M('m-etat-sociabilite-socialisme', N, "Sociabilité et socialisme : définitions ?",
  "Sociabilité : capacité de vivre en société. Socialisme : ensemble de doctrines nées au début du XIXe siècle, préconisant une société moins égoïste : mise en commun des instruments de production, gestion ouvrière, partage du profit.",
  { n: ["l'État"], ref: 'L\'État, « Termes essentiels »', p: '239' }),
M('m-etat-totalitarisme', N, "Qu'est-ce que le totalitarisme d'après le manuel ?",
  "Régime où un parti unique, dirigé par un chef omnipotent, règne par la terreur au nom d'une idéologie (lutte des classes, lutte des races), en atomisant la société et en fédérant les masses contre des « ennemis objectifs ». Marqué par les camps de concentration ou d'extermination. Ex. : nazisme, stalinisme, Chine de Mao, Cambodge de Pol Pot.",
  { a: ['Arendt'], n: ["l'État", 'la liberté'], ref: 'L\'État, « Termes essentiels » (totalitarisme)', p: '240' }),
M('m-etat-societes-animales', N, "En quoi les sociétés humaines diffèrent-elles des sociétés animales ?",
  "Les sociétés animales (ruche, fourmilière) sont dictées par un instinct héréditaire immuable et sont statiques. Les sociétés humaines reposent sur des institutions imposées de l'extérieur et évoluent historiquement. Platon retrace la genèse de la cité à partir de la division du travail (République).",
  { a: ['Platon', 'Mandeville'], n: ["l'État", 'le travail'], ref: 'L\'État, Problématiques : origines de la société et de l\'État', p: '241-242' }),
M('m-etat-animal-politique', N, "En quel sens l'homme est-il « par nature » un animal politique (Aristote) ?",
  "Non que les sociétés poussent comme des champignons, mais que son essence ne se réalise pleinement qu'au sein de la Cité : par le langage et la raison, citoyen libre égal à ses pairs devant la loi (isonomie), il s'élève au-dessus de la bête et de l'esclave. Cette conception est solidaire de la polis grecque du Ve siècle av. J.-C.",
  { a: ['Aristote'], n: ["l'État", 'le langage'], o: 'Politique', ref: 'L\'État, Problématiques (texte 170)', p: '242' }),

// ---------- L'inconscient (manuel, p. 269-276) ----------
M('m-inc-usages', N, "Comment le langage courant emploie-t-il « inconscient », et pourquoi cela fait-il écran à la notion ?",
  "Pour qualifier l'irresponsable qui ne voit pas le danger, ou celui qui a perdu connaissance ou dort. Or le préfixe in- peut marquer l'opposition, non la simple privation : l'inconscient est quelque chose de positif (une représentation psychique non consciente) et de dynamique (une force active).",
  { n: ["l'inconscient", 'la conscience'], ref: 'L\'inconscient, « De l\'usage du mot à la notion »', p: '273' }),
M('m-inc-histoire-mot', N, "Comment le terme « inconscient » s'est-il diffusé avant Freud ?",
  "Première occurrence en anglais (unconscious) au milieu du XVIIIe siècle, en français au XIXe. Sa diffusion est liée à la Philosophie de l'inconscient (1868) d'Eduard von Hartmann, traduite en 1877, synthèse de l'idéalisme et du romantisme allemands (Fichte, Schelling, Hegel, Schopenhauer).",
  { a: ['Hartmann'], n: ["l'inconscient"], ref: 'L\'inconscient, « De l\'usage du mot à la notion »', p: '273' }),
M('m-inc-freud-lacan', N, "En quoi l'inconscient freudien diffère-t-il de l'inconscient philosophique ?",
  "Pour Freud, c'est une hypothèse scientifique liée à une pratique clinique (hystérie, troubles psychiques). Lacan (1964) : l'inconscient de Freud n'a rien à voir avec l'inconscient romantique de la création imaginante, ni avec le lieu des divinités de la nuit.",
  { a: ['Freud', 'Lacan'], n: ["l'inconscient"], ref: 'L\'inconscient, « De l\'usage du mot à la notion »', p: '273' }),
M('m-inc-oedipe', N, "Qu'est-ce que le complexe d'Œdipe ?",
  "Ensemble d'affects de désir et d'hostilité que l'enfant éprouverait entre trois et cinq ans envers ses parents : désir de mort du parent de même sexe, désir sexuel pour l'autre. Il structure le psychisme, refoulé dans l'inconscient, et est normalement surmonté à l'adolescence ; non liquidé, il peut causer des troubles. Il reproduit le mythe d'Œdipe-Roi de Sophocle.",
  { a: ['Freud', 'Sophocle'], n: ["l'inconscient"], ref: 'L\'inconscient, « Termes essentiels »', p: '274' }),
M('m-inc-hypnose-hysterie', N, "Hypnose et hystérie : quel rôle dans la découverte de Freud ?",
  "Hystérie : à la fin du XIXe siècle, troubles corporels (paralysie, aphasie, toux nerveuse…) sans lésion anatomique, parfois levés sous hypnose. L'hypnose, abandonnée par Freud pour sa technique propre, lui a fait comprendre l'origine psychique de certains troubles et l'influence de la parole du thérapeute, mais sans effet durable.",
  { a: ['Freud'], n: ["l'inconscient"], ref: 'L\'inconscient, « Termes essentiels »', p: '274' }),
M('m-inc-libido-nevrose', N, "Libido, névrose, psychose, phobie : définitions ?",
  "Libido : pulsion sexuelle postulée par Freud, équivalent pour le besoin sexuel de la faim pour la nutrition. Névrose : troubles d'origine psychique, expression d'un conflit lié à des traumatismes d'enfance. Psychose : maladies mentales (paranoïa, schizophrénie…), trouble profond du rapport à la réalité ; Freud a renoncé à les traiter. Phobie : peur intense et obsédante.",
  { a: ['Freud'], n: ["l'inconscient"], ref: 'L\'inconscient, « Termes essentiels »', p: '274' }),
M('m-inc-psychanalyse', N, "Qu'est-ce que la psychanalyse ?",
  "Discipline fondée sur l'hypothèse de l'inconscient : procédé d'investigation des processus psychiques inconscients et technique de traitement des troubles névrotiques par la méthode de la libre association.",
  { a: ['Freud'], n: ["l'inconscient"], ref: 'L\'inconscient, « Termes essentiels » (psychanalyse)', p: '274' }),
M('m-inc-refoulement', N, "Qu'est-ce que le refoulement, et comment le refoulé revient-il ?",
  "Processus de défense qui tient à distance de la conscience une émotion, un souvenir ou une pensée liés à une pulsion inconsciente : l'attirance devient répulsion, le désir dégoût. Il agit à l'insu de la conscience ; le refoulé revient dans le rêve, les lapsus, les méprises, les actes manqués.",
  { a: ['Freud'], n: ["l'inconscient"], ref: 'L\'inconscient, « Termes essentiels » (refoulement)', p: '274' }),
M('m-inc-premiere-topique', N, "Quelles instances distingue la première topique freudienne (1900) ?",
  "L'inconscient (siège des pulsions, presque toujours sexuelles, refoulées) ; le préconscient (tendances non refoulées, non censurées) ; la conscience, qui ne concerne qu'une petite partie de la vie psychique.",
  { a: ['Freud'], n: ["l'inconscient", 'la conscience'], ref: 'L\'inconscient, « Termes essentiels » (topiques)', p: '274-275' }),
M('m-inc-seconde-topique', N, "Quelles instances distingue la seconde topique freudienne (à partir de 1920) ?",
  "Le ça (siège des pulsions qui revendiquent satisfaction) ; le moi (en partie inconscient, il arbitre le conflit entre le ça et le surmoi) ; le surmoi (intériorisation des interdits parentaux et sociaux, il juge et critique les représentations).",
  { a: ['Freud'], n: ["l'inconscient"], ref: 'L\'inconscient, « Termes essentiels » (topiques)', p: '275' }),
];
