import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- La justice (manuel, p. 303-308) ----------
M('m-just-droit-morale', N, "Pourquoi le droit et la justice peuvent-ils entrer en conflit ?",
  "Le droit exige l'obéissance extérieure aux règles en vigueur (conduites observables), non la pureté d'intention que demande la morale. On peut trouver injuste l'application de la loi (Jean Valjean condamné pour un pain) ou voir un coupable échapper à la sanction par la procédure. Antigone oppose à Créon les exigences de la piété et de l'amour.",
  { a: ['Sophocle', 'Hugo'], n: ['la justice', 'le devoir'], ref: 'La justice, « De l\'usage du mot à la notion »', p: '303-304' }),
M('m-just-ulpien', N, "Quelle définition de la justice attribue-t-on au juriste romain Ulpien, et que lui oppose Jésus ?",
  "Ulpien : une volonté constante et perpétuelle d'attribuer à chacun son droit (jus). Jésus (Matthieu XXIII, 28) réclame une justice qui aille au-delà du droit positif et se fonde sur la rectitude intérieure : « à l'extérieur vous paraissez justes, à l'intérieur vous êtes pleins d'iniquité ».",
  { a: ['Ulpien'], n: ['la justice', 'la religion'], ref: 'La justice, « De l\'usage du mot à la notion »', p: '304' }),
M('m-just-droit-pouvoir', N, "Le droit est-il l'application d'une justice idéale ?",
  "Non : le droit est indissociable du pouvoir. La puissance publique (l'État) le promulgue, la force publique le rend applicable. Jus dériverait de jussum (« ce qui est commandé ») plutôt que de justitia : c'est l'autorité, non la justice, qui fait la loi.",
  { n: ['la justice', "l'État"], ref: 'La justice, « De l\'usage du mot à la notion »', p: '304-305' }),
M('m-just-democratie-republicain', N, "Démocratique et républicain : quelle différence ?",
  "Démocratie : régime où le peuple exerce le pouvoir souverain, directement ou par représentants. Républicain : moins un régime qu'une manière d'exercer le pouvoir (pour le bien commun, selon la loi, avec séparation des pouvoirs) ; il s'oppose à despotique. Une démocratie peut ne pas être républicaine ; un monarque éclairé peut régner républicainement.",
  { n: ['la justice', "l'État"], ref: 'La justice, « Termes essentiels »', p: '306' }),
M('m-just-despotisme-tyran', N, "Despotisme et tyrannie : quelle distinction Rousseau propose-t-il ?",
  "Despotisme (despotês, maître de maison) : pouvoir arbitraire du chef d'État, sans souci de l'intérêt public ni des lois, quasi-synonyme de tyrannie. Rousseau (Contrat social, III, 10) : le tyran s'ingère contre les lois à gouverner selon les lois ; le despote se met au-dessus des lois mêmes.",
  { a: ['Rousseau'], n: ['la justice', "l'État"], o: 'Du contrat social', ref: 'La justice, « Termes essentiels » (despotisme)', p: '306' }),
M('m-just-droit-naturel-positif', N, "Droit naturel et droit positif : définitions ?",
  "Droit naturel : maximes fondées sur la nature de l'homme, censées universelles et immuables (interdiction de l'inceste, du meurtre) ; chez les modernes, droit de l'état de nature. Droit positif : prescriptions effectivement en vigueur dans une société, renforcées par des sanctions, et qui évoluent avec l'histoire. Rousseau : le contrat transforme l'indépendance naturelle en liberté civile.",
  { a: ['Rousseau'], n: ['la justice', 'la nature'], ref: 'La justice, « Termes essentiels »', p: '306' }),
M('m-just-penal-public-prive', N, "Droit pénal, droit public, droit privé : définitions ?",
  "Droit pénal : branche du droit positif réglant la répression des crimes et délits (poursuites, sanction ; grec poinê, « peine »). Droit public : fonctionnement de l'État et relations avec l'individu (constitutionnel, administratif). Droit privé : rapports entre particuliers. Distinction commode mais philosophiquement fragile (Kelsen ; les libéraux y tiennent).",
  { a: ['Kelsen'], n: ['la justice', "l'État"], ref: 'La justice, « Termes essentiels »', p: '306-307' }),
M('m-just-droit-subjectif', N, "Qu'est-ce qu'un droit subjectif ?",
  "Notion apparue au XIVe siècle : faculté ou pouvoir du sujet de mettre en œuvre sa liberté. Il s'oppose aux obligations juridiques comme l'activité à la passivité. Ex. : les droits de la Déclaration de 1789, que les lois ont pour fonction de protéger.",
  { n: ['la justice', 'la liberté'], ref: 'La justice, « Termes essentiels »', p: '307' }),
M('m-just-polis', N, "Que désignent polis, politeia et politikê ?",
  "Polis : la Cité, communauté de citoyens (politai) avec leurs femmes, enfants et esclaves privés de droits civiques, autour d'une ville. Politeia : son organisation institutionnelle (« constitution »). Politikê : l'activité organisatrice de la Cité, « science directive » selon Platon, qui unit les citoyens par la concorde et l'amitié (Le Politique).",
  { a: ['Platon'], n: ["l'État", 'la justice'], ref: 'La justice, « Termes essentiels » (polis)', p: '307' }),
M('m-just-raison-etat', N, "Qu'est-ce que la raison d'État ?",
  "Au Moyen Âge (ratio status rei publicae), le souci de l'intérêt commun, supérieur aux lois positives mais soumis aux lois divines. Par glissement, à partir de la ragione di Stato (della Casa, 1547), une technique de gouvernement recourant aux moyens de la tyrannie, que l'on prêtait à Machiavel (Le Prince). Botero (1589) y voit plutôt une science des moyens de fonder, conserver, agrandir l'État.",
  { a: ['Machiavel', 'Botero'], n: ["l'État", 'la justice'], ref: 'La justice, « Termes essentiels » (raison d\'État)', p: '307' }),
];
