import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- Le langage (manuel, p. 337-344) ----------
M('m-lang-langue-parole', N, "Langage, langue, parole : comment les distinguer ?",
  "Le langage est la faculté (fixe, universelle) d'exprimer des pensées distinctes par des signes distincts ; les langues sont innombrables et propres à une communauté ; la parole est l'acte individuel par lequel un locuteur use de la langue. On peut dire : la langue, c'est le langage moins la parole.",
  { n: ['le langage'], ref: 'Le langage, « De l\'usage du mot à la notion »', p: '337-338' }),
M('m-lang-communication', N, "Pourquoi la communication par le langage n'est-elle jamais immédiate ?",
  "Communiquer (communicare, « mettre en commun »), c'est transmettre une information ; comme il n'existe pas de transmission directe de pensées, la « communication des consciences » passe par des signes, par le détour d'un discours. Rimbaud rêvait d'une langue « de l'âme pour l'âme ».",
  { a: ['Rimbaud'], n: ['le langage', 'la conscience'], ref: 'Le langage, « De l\'usage du mot à la notion »', p: '338-339' }),
M('m-lang-double-articulation', N, "Double articulation : en quelles unités (monèmes, phonèmes) un énoncé se décompose-t-il ?",
  "Tout énoncé se décompose (1re articulation) en monèmes, unités dotées d'une forme (signifiant) et d'un sens (signifié) — dans « révoltez » : ré, volt, -ez — puis (2e articulation) en phonèmes, unités sonores minimales, en nombre limité et propres à chaque langue. D'où une richesse expressive indéfinie avec un nombre fini de signes.",
  { n: ['le langage'], ref: 'Le langage, « Termes essentiels » (double articulation)', p: '339-340' }),
M('m-lang-apophantique', N, "Qu'appelle-t-on discours apophantique chez Aristote ?",
  "Le discours propositionnel (apophansis), qui « fait apparaître » la chose à partir d'elle-même : tout énoncé qui dit quelque chose de quelque chose, susceptible d'être vrai ou faux, à la différence de la question ou de la prière.",
  { a: ['Aristote'], n: ['le langage', 'la vérité'], ref: 'Le langage, « Termes essentiels » (apophantique)', p: '340' }),
M('m-lang-discours-logos', N, "Discours, discursif, logos : définitions ?",
  "Discours : expression verbale de la pensée, assemblage de mots doté de signification ; discursif : pensée qui s'exprime par les mots (opposé à intuitif). Logos (grec) : selon le contexte, langage, discours, argument, énoncé, raison, ou Verbe divin en théologie.",
  { n: ['le langage', 'la raison'], ref: 'Le langage, « Termes essentiels »', p: '340' }),
M('m-lang-equivoque-univoque', N, "Équivoque (plurivoque), univoque, ineffable : définitions ?",
  "Équivoque ou plurivoque (polysémique) : terme ou discours qui peut être compris de plusieurs manières ; univoque : à signification unique et fixe. Ineffable (in-fari, « dire ») : ce qui serait inexprimable par le langage.",
  { n: ['le langage'], ref: 'Le langage, « Termes essentiels »', p: '340-341' }),
M('m-lang-langue-naturelle-universelle', N, "Langue naturelle et langue universelle : différence ?",
  "Langue naturelle : constituée peu à peu dans l'histoire (français, allemand ; l'espéranto est artificiel) ; le langage ordinaire est son usage quotidien. Langue universelle : projet du XVIIe siècle (Leibniz : « alphabet des pensées humaines », grammaire rationnelle) visant à écarter l'équivoque et à être utilisable par tous.",
  { a: ['Leibniz'], n: ['le langage', 'la raison'], ref: 'Le langage, « Termes essentiels »', p: '340' }),
M('m-lang-linguistique', N, "Quelle est la différence entre linguistique synchronique et diachronique ?",
  "La linguistique est la science de la langue. La synchronique étudie une langue à un moment donné, en faisant abstraction de ses variations dans le temps ; la diachronique étudie ces variations.",
  { n: ['le langage', 'la science'], ref: 'Le langage, « Termes essentiels » (linguistique)', p: '340' }),
M('m-lang-performatif', N, "Qu'est-ce qu'un énoncé performatif ?",
  "Un énoncé qui, à la différence des énoncés constatifs, ne décrit pas un état de choses mais le fait advenir (to perform). « La séance est ouverte » est performatif dans la bouche du président, constatif dans celle d'un témoin (Austin).",
  { a: ['Austin'], n: ['le langage'], ref: 'Le langage, « Termes essentiels » (performatif)', p: '340' }),
M('m-lang-signe-saussure', N, "Signe, signifiant, signifié, symbole : quelles définitions (Saussure) ?",
  "Signe : chose qui en désigne une autre, par rapport naturel (fumée/feu) ou par convention (mots). Signifiant : face vocale du signe linguistique ; signifié : idée associée ; l'ensemble forme le signe. Symbole : signe où subsiste un rudiment de lien naturel (la balance pour la justice, non un char).",
  { a: ['Saussure'], n: ['le langage'], ref: 'Le langage, « Termes essentiels »', p: '341' }),
M('m-lang-systeme-univocite', N, "Qu'entend-on par « système » en linguistique ?",
  "Un ensemble structuré d'éléments dont les relations sont régies par des lois : pour les linguistes, la langue est un système de signes.",
  { n: ['le langage', 'la science'], ref: 'Le langage, « Termes essentiels » (système)', p: '341' }),
M('m-lang-propre-homme', N, "Le langage est-il le propre de l'homme ? Quels arguments s'opposent ?",
  "Aristote : l'homme est le vivant doué de logos. Montaigne : les animaux expriment leurs passions par la voix. Descartes : communiquer une émotion n'est pas exprimer une pensée ; les bêtes sont comme des automates, privées de conscience réfléchie. Benveniste : le « langage des abeilles » est programmé, limité à deux données, sans dialogue.",
  { a: ['Aristote', 'Montaigne', 'Descartes', 'Benveniste'], n: ['le langage'], ref: 'Le langage, Problématiques (textes 221, 222, 224)', p: '342' }),
M('m-lang-penser-mots', N, "Pense-t-on dans les mots ? Quelles positions ?",
  "Port-Royal : on pourrait considérer les pensées sans les revêtir de parole. Bergson : le langage, outil utilitaire, ne reflète pas fidèlement la pensée. Platon : la pensée est un dialogue intérieur de l'âme avec elle-même. Leibniz : les signes servent à penser. Hegel : « c'est dans le nom que nous pensons ». Wittgenstein : la pensée est un jeu de langage.",
  { a: ['Bergson', 'Platon', 'Leibniz', 'Hegel', 'Wittgenstein'], n: ['le langage', 'la raison'], ref: 'Le langage, Problématiques (textes 223, 225, 231-233)', p: '343-344' }),
M('m-lang-domination', N, "Comment Orwell montre-t-il que le langage peut être un instrument de domination ?",
  "Dans 1984, Big Brother substitue à la langue naturelle un code artificiel, la « novlangue », pour rendre incompréhensibles les textes antérieurs (droit, littérature) et impossible toute pensée hérétique : la déclaration des droits de l'homme ne se traduirait plus que par « crimepensée ».",
  { a: ['Orwell'], n: ['le langage', "l'État"], o: '1984', ref: 'Le langage, Problématiques (texte 235)', p: '344' }),
];
