import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- La liberté (manuel, p. 367-372) ----------
M('m-lib-usages', N, "Que révèlent les usages courants du mot « liberté » ?",
  "Connotation positive (liber désignait l'homme libre, par opposition à l'esclave), mais le mot a gagné en extension ce qu'il a perdu en précision (Valéry : « plus de valeur que de sens »). Voisins : licence (excès de liberté), libertin, licencieux (manque de retenue), libéral (ouvert d'esprit ; généreux), libéralisme.",
  { a: ['Valéry'], n: ['la liberté'], ref: 'La liberté, « De l\'usage du mot à la notion »', p: '367-368' }),
M('m-lib-toute-puissance', N, "Pourquoi la liberté n'est-elle pas la toute-puissance de la volonté ?",
  "Si être libre, c'est accomplir tous ses désirs, seuls les dieux le seraient : l'homme subit des contraintes externes (physiques, sociales) et internes (instincts, habitudes, passions). Nerval : « le dernier mot de la liberté, c'est l'égoïsme ». Platon : l'excès de liberté tourne en excès de servitude (République VIII).",
  { a: ['Nerval', 'Platon'], n: ['la liberté'], ref: 'La liberté, « De l\'usage du mot à la notion »', p: '368' }),
M('m-lib-positive', N, "Quelle conception positive de la liberté le manuel oppose-t-il à la toute-puissance ?",
  "Une « liberté pour… » : décider et agir conformément aux résolutions prises, dans une situation déterminée pour un projet déterminé. Elle est compatible avec la finitude humaine et prend la forme du libre arbitre de la volonté, qui fait de l'agent l'auteur responsable de son action.",
  { n: ['la liberté'], ref: 'La liberté, « De l\'usage du mot à la notion »', p: '368' }),
M('m-lib-authenticite-autodetermination', N, "Authenticité et autodétermination : définitions ?",
  "Authenticité (authenticus, « original ») : qualité d'un être qui affirme librement sa personnalité. Autodétermination : pouvoir de la volonté de se déterminer elle-même par sa raison, en résistant aux inclinations de la sensibilité. Autonomie : se diriger selon des lois qu'on se donne.",
  { n: ['la liberté'], ref: 'La liberté, « Termes essentiels »', p: '370' }),
M('m-lib-causalite-contingence', N, "Causalité, contingence, nécessaire : définitions dans le cadre de la liberté ?",
  "Causalité : tout effet a une cause (une décision ou un phénomène physique). Contingence : ce qui peut être autrement (prendre ou non son parapluie) ; nécessaire : ce qui ne peut pas être autrement (la somme des angles d'un triangle).",
  { n: ['la liberté'], ref: 'La liberté, « Termes essentiels »', p: '370' }),
M('m-lib-destin-fatalisme', N, "Destin, fatalité, fatalisme, providence : définitions ?",
  "Destin : puissance supérieure qui fixerait irrévocablement le cours des événements (divination des Anciens). Fatalité (fatum, fari) : le destin annoncé par la parole ou l'oracle. Fatalisme : doctrine du destin, ou attitude de résignation. Providence : prévoyance divine par laquelle Dieu gouverne le monde.",
  { n: ['la liberté', 'la religion'], ref: 'La liberté, « Termes essentiels »', p: '370-371' }),
M('m-lib-determinisme', N, "Qu'est-ce que le déterminisme ?",
  "La doctrine selon laquelle tous les événements de l'univers, y compris les actions humaines, découlent de causes qui entraînent nécessairement les mêmes effets dans les mêmes conditions.",
  { n: ['la liberté', 'la science'], ref: 'La liberté, « Termes essentiels » (déterminisme)', p: '370' }),
M('m-lib-libre-arbitre', N, "Qu'est-ce que le libre arbitre (Descartes) ?",
  "La faculté de choisir sa manière d'agir sans être contraint par aucune force étrangère. Selon Descartes, tout homme peut arbitrer librement, c'est-à-dire trancher souverainement dans les débats de sa propre conscience. Le for intérieur est ce « tribunal intime de la conscience » où il s'exerce.",
  { a: ['Descartes'], n: ['la liberté', 'la conscience'], ref: 'La liberté, « Termes essentiels »', p: '371' }),
M('m-lib-hasard-prudence', N, "Hasard et prudence : définitions ?",
  "Hasard (azar, « jeu de dés ») : concours de circonstances imprévisible produisant un événement qui ne résulte pas d'une intention. Prudence : au sens moderne, réserve face au risque ; au sens ancien, vertu de la partie pensante de l'âme qui fixe la fin bonne et les moyens adaptés, condition de l'acquisition des autres vertus.",
  { n: ['la liberté', 'le bonheur'], ref: 'La liberté, « Termes essentiels »', p: '371' }),
M('m-lib-responsabilite-volonte', N, "Responsabilité et volonté : définitions, et différence entre volonté et désir ?",
  "Responsabilité (respondere) : capacité de répondre de ses actes, de se reconnaître comme leur auteur et d'en assumer les conséquences ; elle suppose la liberté de choix. Volonté : pouvoir de résister à ses désirs immédiats dans la durée, supposant un effort ; le désir, lui, est éprouvé, voire subi (passivité).",
  { n: ['la liberté', 'le devoir'], ref: 'La liberté, « Termes essentiels »', p: '371' }),
];
