import { M } from './dsl.mjs';
const N = 'notion';
export default [
// ---------- La nature (manuel, p. 403-408) ----------
M('m-nat-ambiguite', N, "Quelle ambiguïté fondamentale le mot « nature » présente-t-il ?",
  "Il désigne d'une part un domaine de choses que l'homme n'a pas fabriquées (opposé à la ville) ; d'autre part le principe de production ou puissance créatrice (natura, de nascor, « naître ») qui fait naître et donne ses dons. Nature s'oppose aux artefacts, l'art étant la cause propre à l'homme.",
  { n: ['la nature', "l'art"], ref: 'La nature, « De l\'usage du mot à la notion »', p: '403-404' }),
M('m-nat-questions', N, "Quelles questions la notion de nature ouvre-t-elle ?",
  "La nature est-elle capricieuse ou régie par des lois intangibles (objet des sciences de la nature) ? Poursuit-elle des fins ? Existe-t-il un ordre naturel rationnel, immuable, juste, avec une loi naturelle inscrite dans le cœur de l'homme ? Ou l'homme, engagé dans la culture et l'histoire, est-il sourd à son appel ?",
  { n: ['la nature', 'la science'], ref: 'La nature, « De l\'usage du mot à la notion »', p: '404-405' }),
M('m-nat-a-priori', N, "A priori et a posteriori : définitions ?",
  "A priori : antérieurement à toute expérience ; a posteriori : ce qui vient de l'expérience.",
  { n: ['la nature', 'la raison'], ref: 'La nature, « Termes essentiels » (a priori)', p: '406' }),
M('m-nat-artefact-abstraction', N, "Artefact et abstraction : définitions ?",
  "Artefact (factum + ars) : objet fabriqué, par opposition à ce que produit la nature. Abstraction : acte par lequel l'esprit isole un élément ou un aspect qui n'est pas donné séparément (la blancheur tirée de plusieurs objets blancs) ; essentielle à la formation des concepts.",
  { n: ['la nature', 'la raison'], ref: 'La nature, « Termes essentiels »', p: '406' }),
M('m-nat-causalite', N, "Que pose le principe de causalité ?",
  "a) tout phénomène a une cause ; b) toute cause est suivie du même effet dans des circonstances semblables.",
  { n: ['la nature', 'la science'], ref: 'La nature, « Termes essentiels » (causalité)', p: '406' }),
M('m-nat-empirique-empirisme', N, "Empirique et empirisme : définitions ?",
  "Empirique : ce qui est relatif à l'expérience ou en provient (empeiria ; les médecins « empiriques » se fondaient sur la comparaison des cas, non sur le raisonnement). Empirisme : toute connaissance vient de l'expérience ; rien dans la pensée qui n'ait son origine dans les observations extérieures ou intérieures (Locke).",
  { a: ['Locke'], n: ['la nature', 'la science'], ref: 'La nature, « Termes essentiels »', p: '406' }),
M('m-nat-entendement', N, "Comment Kant distingue-t-il entendement et raison ?",
  "À l'âge classique, entendement (intellectus) est synonyme de raison et de bon sens. Kant : l'entendement organise le donné sensible selon des règles, il ramène les phénomènes à l'unité ; la raison est la faculté des principes, qui ramène à l'unité les règles de l'entendement.",
  { a: ['Kant'], n: ['la raison', 'la nature'], ref: 'La nature, « Termes essentiels » (entendement)', p: '406' }),
M('m-nat-falsification', N, "Qu'est-ce que la falsification chez Popper ?",
  "Procédure qui ne tient pour scientifiques que les énoncés susceptibles d'être réfutés, c'est-à-dire confrontés à l'expérience ou à l'observation. « Il pleuvra demain » n'est pas falsifiable ; « il pleuvra ici demain » l'est.",
  { a: ['Popper'], n: ['la science', 'la vérité'], ref: 'La nature, « Termes essentiels » (falsification)', p: '406' }),
M('m-nat-induction-loi', N, "Induction et loi scientifique : définitions ?",
  "Induction : acte de l'esprit qui établit à partir de cas individuels une proposition universelle, souvent conjecturale. Loi : énoncé général formulant des rapports constants entre choses ou propriétés (invariabilité, régularité), souvent exprimé par des fonctions ou équations mathématiques.",
  { n: ['la science', 'la nature'], ref: 'La nature, « Termes essentiels »', p: '406' }),
M('m-nat-modele-phenomene', N, "Modèle (paradigme), phénomène, phénoménal / nouménal : définitions ?",
  "Modèle : représentation condensant, souvent mathématiquement, les composantes d'un système. Phénomène (phainesthai) : ce qui se manifeste aux sens ou à la conscience. Kant : monde phénoménal = tel qu'il apparaît au sujet ; monde nouménal = tel qu'il est en soi, conçu par l'intellect, au-delà de l'espace et du temps.",
  { a: ['Kant'], n: ['la nature', 'la connaissance'], ref: 'La nature, « Termes essentiels »', p: '406-407' }),
M('m-nat-experimentation', N, "Quelle différence entre expérience et expérimentation ?",
  "Dans l'expérience, le sujet observateur est passif ; dans l'expérimentation, il devient actif en faisant varier les paramètres à sa guise et en répétant la procédure, dans le cadre d'un protocole défini à l'avance, pour contrôler une hypothèse, établir une théorie ou valider une connaissance.",
  { n: ['la science', 'la nature'], ref: 'La nature, « Termes essentiels » (protocole d\'expérimentation)', p: '407' }),
];
